### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by mitchellknight** [Microsoft/ChakraCore#103]

**Comment by ljharb** [comment]
(added in #54)

That's not accurate imo. The purpose of the Code of Conduct to me is to help ensure a level playing field and **fair** treatment of everybody. Since the playing field is already not level, that *requires* placing the rights of disadvantaged groups over the rights of advantaged groups so as to make things [**fair** - not equal](http://twitter.com/haytibbs/status/634084533000896512/photo/1).

This kind of discussion is never productive, so please let's let it rest at that.

**Comment by mitchellknight** [comment]
> Since the playing field is already not level, that requires placing the rights of disadvantaged groups over the rights of advantaged groups so as to make things fair - not equal.

I completely disagree with this. Everyone should be treated equally and fairly. Placing the rights of any group over another is appalling.

> This kind of discussion is never productive, so please let's let it rest at that.

I've made my point. The ChakraCore team is welcome to address it or ignore it. If they chose to ignore it, they should understand that some people will feel unwelcome to contribute because the Code of Conduct uses unnecessarily inflammatory language that places the rights of some people over others.

**Comment by RyanCavanaugh** [comment]
I think you've missed some words when reading this.

The statement is:
> We will prioritize marginalized people**'s safety** over privileged people**'s comfort**.

See also: We prioritize the safety of pedestrians over the comfort of car drivers by having crosswalks. We prioritize the safety of consumers over the comfort of restaurateurs by requiring food inspections.

This shouldn't be controversial, unless you really think that privileged people deserve comfort more than marginalized people deserve safety.

Can you make a case for why that should happen? In what cases should we make something *less safe* for one group so that another group can be *more comfortable*?

**Comment by mitchellknight** [comment]
Shouldn't you prioritize the *safety of anyone* over another persons *comfort*? This can be said without placing people in to groups based on their perceived status in society.

**Comment by RyanCavanaugh** [comment]
> Shouldn't you prioritize the safety of anyone over another persons comfort?

Absolutely. [Everyone's safety matters](http://chainsawsuit.com/tag/all-lives-matter/). The statement speaks to the fact that, historically, *this has not been the case*, and the CoC intends to be part of changing that.
