### ISSUE TITLE
Support of `JsVariantToValue` and `JsValueToVariant` methods

### ISSUE THREAD

**Issue by Taritsyn** [Microsoft/ChakraCore#104]
Do you plan to implement `JsVariantToValue` and `JsValueToVariant` methods? In general, will there be added any possibility to embed custom .NET objects into JavaScript engine?

**Comment by robpaveza** [comment]
Variant is a [COM Automation concept](https://msdn.microsoft.com/en-us/library/windows/desktop/ms221627(v=vs.85).aspx) that is primarily around the IDispatch interface.  ChakraCore is very much intended to be specifically geared towards going cross-platform, and probably won't incorporate such Windows-specific APIs into the main branch.

Embedding custom .NET objects is a different problem, though.  I have written [a wrapper](https://github.com/robpaveza/jsrt-dotnet) that provides a higher-level wrapper of the hosting interface into .NET; I've been experimentally working on enabling .NET-to-JavaScript object concurrency ("projections").  The "most stable" version of that is the ["projections" branch at commit b62f0009](https://github.com/robpaveza/jsrt-dotnet/commit/b6f20009e0b5a148bd60eca7eed73d4b5f8f83b4#diff-25d902c24283ab8cfbac54dfa101ad31), which enables converting a .NET object to a JavaScript object from `engine.Converter.ToObject(myClrObject)`, which retains identity (changes to the JavaScript object are reflected in the corresponding .NET object).  I've been having trouble getting events working just right, which is why I haven't merged back into master.  You can also use the `dynamic` keyword to interact with JavaScript objects from C#.

**Comment by Taritsyn** [comment]
Thanks for information!

**Comment by smourier** [comment]
You're wrapper is fine, but what logic should we use if we want to implement the equivalent of JsValueToVariant (the reverse is easier)? That is, if I follow your JavaScriptConverter.cs sample, how should I implement a method such as `public object ToObject(JavaScriptValue value)` method? especially if I want to be compatible with legacy IE9x/Jscript9 API? For example, if I have a js number, when should I return a long/int/double, etc? again, I want to be compatible with legacy JsRt API
