### ISSUE TITLE
"new ArrayBuffer()" should throw a RangeError

### ISSUE THREAD

**Issue by suwc** [Microsoft/ChakraCore#105]
Per ECMA262:
24.1.2.1ArrayBuffer( length )#

ArrayBuffer called with argument length performs the following steps:
1.If NewTarget is undefined, throw a TypeError exception.
2.Let numberLength be ? ToNumber(length).
3.Let byteLength be ToLength(numberLength).
4.If SameValueZero(numberLength, byteLength) is false, throw a RangeError exception.
5.Return ? AllocateArrayBuffer(NewTarget, byteLength). 

When length == undefined, step 2 returns NaN while step 3 returns 0, therefore step 4 should throw a RangeError.

This behavior is not implemented in ChakraCore.

**Comment by jordonwii** [comment]
Hi folks,
Can I take this issue, or has it not yet been accepted (since it's missing "accepting-prs")?

I have a draft PR nearly ready, but this looks like it would be a breaking change - code that currently works would now be crashing.

**Comment by obastemur** [comment]
> When length == undefined, step 2 returns NaN while step 3 returns 0, therefore step 4 should throw a RangeError.

I don't agree.

Let's start with the part we all agree. numberLength = NaN.

> 3.Let byteLength be ToLength(numberLength).

`numberLength` was `NaN`. Looks like ToLength(NaN) should define the result.

*7.1.15 ToLength (https://tc39.github.io/ecma262/#sec-tolength)*

1.    Let len be ? ToInteger(argument).
2.    If len ≤ +0, return +0.
3.    If len is +∞, return 2^53-1.
4.    Return min(len, 2^53-1). 

1. > len = NaN, ToInteger(NaN) ==> NaN , 2. pass, 3. pass, 4. min(NaN, 2^53-1) ==> NaN

So, what is the result for SameValueZero(NaN,NaN) ?

*7.2.10 SameValueZero(x, y) (https://tc39.github.io/ecma262/#sec-samevaluezero)*

Skipping 1 and 2 since it's not a number, 
3. Return SameValueNonNumber(x, y). 

*7.2.11 SameValueNonNumber(x, y) (https://tc39.github.io/ecma262/#sec-samevaluenonnumber)*

8. Return true if x and y are the same Object value. Otherwise, return false. 

Returns true.. IMO it shouldn't throw a RangeError.

> 5.Return ? AllocateArrayBuffer(NewTarget, byteLength). 

*24.1.1.1 AllocateArrayBuffer( constructor, byteLength )https://tc39.github.io/ecma262/#sec-allocatearraybuffer*

This part indeed a bit interesting and looks like no one cares about it. 

1.    Let obj be ? OrdinaryCreateFromConstructor(constructor, "%ArrayBufferPrototype%", « [[ArrayBufferData]], [[ArrayBufferByteLength]] » ).
2.    Assert: byteLength is a positive integer.
3.    Let block be ? CreateByteDataBlock(byteLength).
4.    Set obj's [[ArrayBufferData]] internal slot to block.
5.    Set obj's [[ArrayBufferByteLength]] internal slot to byteLength.
6.    Return obj. 

Assert at (2.) should fail for new ArrayBuffer(undefined) 

One issue or shortcut to mention though. Internally ChakraCore does not care about the possibility of NaN for `new ArrayBuffer`

**Comment by ljharb** [comment]
@obastemur NaN is indeed a number - see `typeof NaN`.

**Comment by obastemur** [comment]
> @obastemur NaN is indeed a number - see typeof NaN.

@ljharb you got me. But that doesn't change the result

7.2.10 SameValueZero(x, y) (https://tc39.github.io/ecma262/#sec-samevaluezero)

2 . If Type(x) is Number, then
    If x is NaN and y is NaN, return true.

**Comment by ljharb** [comment]
Definitely. both `ToLength` and `toInteger` of `NaN` return `+0`. `ToNumber(undefined)` returns `NaN`. Step 4 of https://tc39.github.io/ecma262/#sec-arraybuffer-constructor indeed says that since `NaN` is not SameValueZero to `+0` that a RangeError should be thrown.

**Comment by ljharb** [comment]
I will point out that Safari, Chrome, and Firefox all do not throw when `new ArrayBuffer()` is invoked - they just return a buffer with a byteLength of zero. It's possible that this part of the spec is (or has become) web-incompatible, which may necessitate a spec change.

**Comment by obastemur** [comment]
@ljharb Makes sense. Although abstract `toInteger` returning 0 for `NaN` is just another exception.

Suggested PR #131 optionally fixes this issue along with the others.

**Comment by ljharb** [comment]
Linking to https://github.com/tc39/ecma262/issues/265

**Comment by dilijev** [comment]
@jordonwii The `Accepting PRs` tag is something we add to issues we believe the community could reasonably tackle, but it's not an exhaustive list of such issues (since if someone looks at an issue and thinks they know what to do, then that's perfectly fine). Typically if an issue is assigned to someone it means they're working on it or planning to work on it soon, for those issues you should ask before you dive in. Otherwise, it should be okay to take it.

**Comment by bterlson** [comment]
This is not true anymore, ToIndex is used to coerce the first (possibly undefined) object and the result should be a 0-length array buffer. Looks like we're correct here?
