### ISSUE TITLE
Plug in ChakraCore to the Windows Script host so it/Chakra can replace JScript 5.8 [suggestion]

### ISSUE THREAD

**Issue by metathinker** [Microsoft/ChakraCore#108]
Many Windows applications such as AutoCAD have long embedded the Windows Script Host to allow scripting in VBScript, JavaScript, and other installed Windows Script languages, and there are a lot of system administration scripts written in JavaScript to run under WSH.

But Chakra has never been a Windows Script script engine since it was introduced in Internet Explorer 9. As a result, while IE 9-11 and Edge and now ChakraCore have leaped ahead in JavaScript support to ECMAScript 6th Edition, other Windows apps have to either adopt the new JSRT API which only came out with Chakra for IE 11, or stay stuck with JScript 5.8 and ECMAScript 3rd Edition. And adopting JSRT means either extra work to indefinitely support two embedded script subsystems, or dropping support for VBScript, perl, and other Windows Script languages.

So, I suggest the above in the title - make ChakraCore a Windows Script engine, either through internal code or a thin wrapper around JSRT that implements [the IActiveScript API](https://msdn.microsoft.com/library/xawadt95%28v=vs.94%29.aspx), and perhaps even give it the same COM ProgID as JScript 5.8 with a higher version number, so that apps can get access to Chakra when they ask for JScript.

This is big, and perhaps too big for a single work item, but I hope it can be considered nonetheless.

**Comment by tcare** [comment]
@curtisman @Yongqu

**Comment by gabereiser** [comment]
Another recommendation, static link ChakraCore with a "ChakraScriptHost" or some other bridge that will provide this functionality to those who need it while still keeping Core clean of legacy win32 stuff.  That way, the IActiveScript API can be provided but as a separate lib and can keep Core on track to be cross-platform.

**Comment by robpaveza** [comment]
There are a lot of difficulties with using WSH as the desired programming model, which are things that we've learned as part of evolving jscript and IE/Edge.

One of these is the security model.  WSH didn't enforce any kind of security around what was required; IE added this (if I recall correctly) around the IE 5.5 timeframe, which was well after WSH first shipped.  It was done [via the IObjectSecurity interface](https://blogs.msdn.microsoft.com/ericlippert/2004/01/13/script-and-ie-security-part-two-digging-deeper/), which required security to be determined per-native-object.  It's fairly complicated.

Another is performance.  The Active Scripting interfaces rely on `IDispatch`, the ABI of which is based around `VARIANT` and looking up functions by names and then invoking them.  Because of [some of the mechanics around IDispatch](https://blogs.msdn.microsoft.com/ericlippert/2003/09/16/why-do-the-script-engines-not-cache-dispatch-identifiers/), it's impossible to make calls from script to native fast.  Without getting too deep into it, part of the migration from jscript to Chakra involved changing how IE's DOM implementation called into JavaScript.  Previously, the DOM had been exposed entirely via IDispatch (you see a lot of that around how the DOM documentation used to be written out).  Today, marshalers use WebIDL to create fast-path translations between JavaScript and DOM objects, which makes the performance better by an order of magnitude.

Yet another is compatibility.  Because of security concerns around (for example) script files being attached to emails and these then being executed in WSH without a security sandbox, antimalware vendors would occasionally overwrite the JScript registration, substituting their own IActiveScript registration, which would intercept and wrap access to the JScript one.  (Remember that COM component registration is done globally via the system registry).  The problem was that those vendors would not do the work in a compatible way, which would sometimes lead to websites failing to work or other hosts failing in difficult-to-diagnose ways.

[JsRT](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Reference) is the preferred hosting model for Chakra (and ChakraCore) in modern applications.  It's designed to be fast and avoid the problems I outlined above.

I could imagine bridging the gap with an implementation of IActiveScript that called into JsRT, but you still then have the global registration and you have to pay the penalty of working via IDispatch.  I don't think that would be a good fit for ChakraCore, either, being that IActiveScript and IDispatch are very much Windows-centric technologies.

**Comment by metathinker** [comment]
@robpaveza, your first two concerns - the difficult security model of scripting and the performance loss due to the Automation/IDispatch dependency - are valid, but they become much less important if you do not have the luxury to start from scratch in choosing an embedded script engine.

The hosting apps for which plugging in Chakra to Windows Script would be helpful are the ones which are already loading wscript.dll/WSH. For these apps, the choice right now is:

1. Stick with Windows Script alone, and tell your customers that if they want to extend your app with JavaScript, then they'll have to stick to JavaScript the way it was in 1999, when ECMAScript 3rd edition came out.

2. Do the work to embed another script engine, which could be Chakra through JSRT, or SpiderMonkey, or V8, or whatever, and spend lots of work to both host the script engine and expose your app's programmatic interfaces to script using whatever API the script engine provides for this. After doing all this work, you can tell your customers they can use modern JavaScript.

Neither is a great choice. But choice 1 is the zero-cost option, and the benefit of choice 2 might be too small to justify the work required. And if you are using script as an extension language for your app rather than an essential part of an app framework, the way Edge and other browsers use JavaScript, then the performance benefit in particular of using more statically bound script APIs is almost irrelevant.

With regard to the app compat issue, it seems that if antivirus vendors want to intercept calls to the script engine, then merely not exposing the engine API through a COM cointerface is a terribly weak way to stop them from doing so. But that is a pure hypothetical for which I don't have any evidence either way.

> I could imagine bridging the gap with an implementation of IActiveScript that called into JsRT, [...] I don't think that would be a good fit for ChakraCore, either, being that IActiveScript and IDispatch are very much Windows-centric technologies.

A Windows Script wrapper for JSRT was indeed just what I had in mind. I'm fine with it not being part of ChakraCore, since it is an adapter from the "native" Chakra API to another API. But not having it _at all_ is the feature lack I am concerned about.

And given that JSRT is a Chakra-specific script API, it makes sense for it to be at least developed in coordination with Chakra and ChakraCore, if not strictly as part of the latter two or by the same people.

**Comment by dilijev** [comment]
If the various security concerns are not an issue and you're looking for a console app from which to run ChakraCore's implementation of JavaScript, you can build ChakraCore, copy `ChakraCore.dll` and `ch.exe` into a directory and add that directory to your `%PATH%`, and use `ch.exe` as your script host. It's not the ideal solution but you have the advantage that ch.exe is literally the executable we run our tests against, so no extra testing is needed.

**Comment by metathinker** [comment]
That doesn't cover the scenario of another app hosting the script engine to provide extensibility. I am also not sure if it would work as well as cscript.exe/wscript.exe  for the kinds of ad hoc scripts used in system administration.

**Comment by Yongqu** [comment]
To me, there are two Javascript extensibility stories: developers can use either node.js, or Windows Scripting Host+ActiveX. In general, we are more concern about the backward compatibility in WSH. We don't want to see factory floor stop working when they upgrade to a newer version of script engine and break their automation. On the other hand, in node.js, we do provide node+chakracore support to enable great extensibility leveraging the large number of npm out there. New ES features will be available to node components automatically when they are implemented and released. 

When we started chakra project back in IE9 timeframe, we made a conscious decision not to use chakra in WSH because we cannot guarantee backward compatibility going forward. Fast forward to current state, when we open source chakracore, we leave out the windows related host binding mechanism, including IActiveScript support, IDispatch support, to name a few. It would require some work to make WSH use chakracore directly.

That said, with JSRT APIs, the community is welcome to create new extension host based on ChakraCore. IActiveScript, ActiveX object, and other host integrations, are doable using JSRT APIs.

**Comment by EdMaurer** [comment]
I can say from the team's experience with Node.js, that writing a robust shim is not cheap. We've spent well over ten months of dev time building up our V8 shim.

Another thing to consider is debugging. My guess is that it would be challenging to bridge IActiveScript debug APIs to JSRT. Plus we've got to finish the JSRT debugging APIs in the first place!

I agree that there is a useful project suggestion here that would build a way forward for those apps that host WSH, but I don't see the ChakraCore team having capacity to dedicate to this in the next six months. We certainly have experts who could advise though.

**Comment by EdMaurer** [comment]
Thanks for the good discussion, y'all. If there's nothing more to discuss on this topic, tomorrow I'll close it as "out of scope" for ChakraCore.

**Comment by EdMaurer** [comment]
Out of scope for ChakraCore.

**Comment by Fred-Vatin** [comment]
Well if any plan to natively add another language than VBS and JScript or an updated version of JScript, let me know.
