### ISSUE TITLE
Handling UTF-8 conversion/normalization internally

### ISSUE THREAD

**Issue by obastemur** [Microsoft/ChakraCore#1098]
Source buffer may have a broken/unsupported unicode entry that we could normalize / convert into UTF-8. At the moment, this is considered as a consumer problem rather than a feature that ChakraCore provides cross platform.

**Comment by digitalinfinity** [comment]
@yongqu @liminzhu  @curtisman @abchatra thoughts? The current model we have is, we have two APIs supported in Jsrt- either you pass in a valid UTF8 string, or a valid UTF16-LE string- the host is responsible for any conversions from other encodings into one of these encodings. 
@obastemur points out that v8 is more generous in terms of the utf8 inputs they accept- for example, if a BOM is in the middle of the source buffer, the input script is still accepted. It's unclear to me how relaxed the input requirements are- @obastemur, do you know if they accept for example, UTF16 and just convert to UTF8 internally?

The question for us is, should we be more relaxed with the input source buffers- @obastemur notes that this issue is motivated by an actual customer reported issue in node that I think he had to deal with.

**Comment by abchatra** [comment]
+ @bterlson

**Comment by obastemur** [comment]
@digitalinfinity has already briefly explained what we had discussed prior to sharing this issue on Github.

Couple of extra pointers;

- We are/were unable to run one of the test cases or match the outputs of others on posix. (Aside from CRLF issues). Indeed, re-formatting them etc. should solve the issue but IMO it is not that developer friendly.

 - JSRT asks for wchar_t for some of the API while we use char16 internally and most of the OS tooling on posix etc is simply char.

**Comment by obastemur** [comment]
Closing this one. At the moment there is no further discussion is needed. Over time we will be improving the experience as the issues appear.
