### ISSUE TITLE
let vs var and closures

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/ChakraCore#1106]
In Chrome, using V8, using a **let** rather than **var** to declare a variable avoids a JavaScript closure behavior that often surprises developers.   In browsers based on Chakra, this distinction between **let** and **var** does not seem to apply.

The following fiddle demonstrates: http://jsfiddle.net/rmXcF/4/.   In Chrome, clicking on the red "3" div alerts with the number 3, but in IE and edge, the displayed number is 6.  

I'm really not sure which behavior is correct per the specification, but Chrome's behavior is certainly less surprising.

**Comment by bterlson** [comment]
You are likely testing with an older version of Edge. This is fixed in the latest version (v. 25 at least).

**Comment by dilijev** [comment]
Tagged as fixed and will close soon unless @BurtHarris reconfirms that this is a current issue.

**Comment by BurtHarris** [comment]
The version of edge I repro this on is 52.10586.0.0

**Comment by ianwjhalliday** [comment]
Thanks for reporting @BurtHarris.  I fixed this back in December IIRC, so indeed Windows 10 Nov update does not include the fix and has the bug.  This should be fixed in latest preview builds of Windows 10, and the next public release of Windows 10.

**Comment by dilijev** [comment]
So that everyone is on the same page:

Version 25.10586.0.0 is the version of Edge released with Windows 10 November Update (i.e. 1511 Build 10586.*). If you use the run box (WinKey+R) and run `winver` you will see something like the following if you're running the November Update:

![image](https://cloud.githubusercontent.com/assets/494055/16018819/072b5a18-315b-11e6-91e2-643e032a7240.png)

Not sure what major version we're reporting for Edge in preview builds at the moment, but it helps to be precise here that the issue was not yet fixed in 25.10586.0.0, but is fixed in later builds which are available in the Windows insider program.

Thanks again for bringing this to our attention!

**Comment by BurtHarris** [comment]
Your are welcome.  I trust you're right that it's fixed in pre-release, but the version number situation has gotten really out-of-hand, making words like "current" quite ambiguous.      The old RAID based three-state model of bugs being OPEN, RESOLVED, or CLOSED is really not enough when something has been open-sourced.   Seems like a state of FIXED (or similar) needs to be inserted before CLOSED.   

To be clear, I'm running MSDN released "1511", everywhere this has occurred, but what to call that number, but even that's not sufficient to identify a release these days.   MSDN downloads calls it "(Updated Apr 2016)", which is clearly different from the December 1511 mess that broke windows update.     On freshly installed copy from MSDN and with system updates, he "ver" command and "winver" produce different numbers, the proliferation of which complicating what's meant by "current".   

 - Ver: Microsoft Windows [Version 10.0.10586]
 - Winver: Microsoft Windows Version 1511 (OS Build 10586.420)

**Comment by dilijev** [comment]
@BurtHarris Thanks for that feedback. We'll see if there's anything we can do to help the situation of knowing what is fixed in a given version of Windows or ChakraCore but this is a hard problem as there is some process between checking code into our repo and that code ending up in any particular Windows release.

Do note that keeping issues open (tagged as "Fixed") that are no longer actionable by developers would just create a lot of noise for the developers in managing which issues are closed upon which release, especially since the meaning of "released" is a bit nebulous with the various preview packages of ChakraCore and preview builds of Windows via the Insider program. For Chakra in Windows, whether something is fixed depends on what release you are using (official releases only, Windows Insider Slow ring / Fast ring, etc.). It is a hazard of preview/beta/insider programs that it's sometimes difficult to always know what is fixed or what features are in which versions.

As for interpreting these numbers, both `ver` and `winver` output give us basically the same information: you are running OS Build 10586. The second number in winver (.420) indicates where you are patched to via Windows Update (important security fixes only).

The Version 1511 you are seeing can be interpreted as 2015-11 (November 2015) so this means you are running the Windows 10 November Update. The OS Build number is the most important information for us.

**Comment by BurtHarris** [comment]
The approach I'm suggesting would simply require developers to add '**no:fixed**' to their default issue query to exclude issues in a Fixed state.   

As you probably know, the MS RAID model, developers generally only cared about bugs in the "Open" state, transitioning it to 'Resolved' meant it was out of the developer's hands and now belonged to test.   The tester would then "Close" the bug to mark it tested.   The problem with that model is that it doesn't track the work queue of Release Managment, which is what I'm suggesting Fixed should indicate.   If there are multiple release mechanisms, fast prerelease, slow prerelease, and released, release management might add more tags for filtering, but my suggestion is that "Closed" should indicate a fix is either in the official released channel, or is just not needed.

**Comment by ianwjhalliday** [comment]
We have been using GitHub issue labels to reflect the state of these issues with respect to ChakraCore's master branch or release/<milestone> branches so far.  They do not reflect at all what state Chakra in Windows releases is.  Once an issue is complete with respect to ChakraCore, we close the issue.  We separately track scheduling of payloads to Windows, but do not track the state of individual GitHub issues relative to Windows releases.  ChakraCore is its own project.

That said, the lag time from changes in ChakraCore making their way into preview builds of Windows shouldn't be too long (a few weeks?).

@BurtHarris are you still seeing this bug in the Apr 2016 update build?

I just built latest ChakraCore and modified the repro to work with the console host, ch.exe, and confirmed that the correct capture semantics are exhibited:

```javascript
'use strict';

let a = [];

for (let i=1; i<6; i++) {
    print(i);
    a.push(function () { print(i); });
}

for (let i=0; i<5; i++) {
    a[i]();
}
```

output:
```
1
2
3
4
5
1
2
3
4
5
```
