### ISSUE TITLE
[Test failure] [Daily] [Dev12 x64_debug] Test timeouts are causing the legacy daily build to fail on x64_debug

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#115]
https://github.com/Microsoft/ChakraCore/wiki/Build-Status#legacy-builds

It seems specific to x64_debug.

While we investigate why they are timing out after 60s (despite running individually in under 10s), we will disable these tests in this configuration.

Tests I've seen affected so far:
```
d:\j\workspace\Private\Microsoft_ChakraCore_daily_x64_debug\test\typedarray\allocation.js
d:\j\workspace\Private\Microsoft_ChakraCore_daily_x64_debug\test\typedarray\allocation2.js
d:\j\workspace\Private\Microsoft_ChakraCore_daily_x64_debug\test\bailout\bailout7.js 
d:\j\workspace\Private\Microsoft_ChakraCore_daily_x64_debug\test\bailout\bailout-argobj.js
d:\j\workspace\Private\Microsoft_ChakraCore_daily_x64_debug\test\bailout\bailout-args.js
d:\j\workspace\Private\Microsoft_ChakraCore_daily_x64_debug\test\bailout\bailout-throw.js
```

Edit 3/7/16: We did not end up disabling the tests because we wanted to monitor the failures and having that build flavor green was not high priority. The problem seems to have spontaneously improved. We will monitor for a while and re-evaluate whether there is any further action to be taken on this issue.

**Comment by ianwjhalliday** [comment]
Sounds like this might be a bug in the way rl.exe does its timeout.  I believe I have a consistent repro on my laptop fortunately.

**Comment by ianwjhalliday** [comment]
Turns out my consistent repro was a legitimate timeout.  On my laptop and actually my desktop, our internal unit test `Debugger\promise_deferNestedAttach.js` takes almost two minutes to run to completion for `x64debug`.  I'm not sure why it doesn't time out on the internal CI machines.  Perhaps they are faster CPUs.

@satheeshravi had a repro where a test that was timing out did allegedly run way under 60 perhaps.  I'll work with him to do more investigation.

**Comment by satheeshravi** [comment]
In my case, they were Date\parseISO.js and typedarray\samethread.js. Both timed out under rl.exe.

**Comment by ianwjhalliday** [comment]
@satheeshravi and I took a look and it turned out that the `Date\parseISO.js` test took longer than 60 seconds on his machine and so it legitimately timed out.  The `typedarray\samethread.js` test appeared to take around 25-30 seconds, so my suspicion is that it occasionally gets stalled off the CPU and trips over the 60 second threshold.

I'll look at the Jenkins failure to see if that test might also just be a longer runner that gets tripped up.

rl.exe uses wall clock time for the timeout which of course means that if the test process gets stalled it might timeout.  I'm not sure if we can do better since 1) rl.exe runs ch.exe via cmd.exe so rl.exe does not have direct access to the ch.exe process for querying cpu time and 2) in general a test might be a batch script that starts and waits for numerous processes.  Thus we'd have to query the cpu time of the tree of processes spawned by the test and Windows does not provide APIs afaik for easily getting this information or even the handles of the descendant processes.

I think the solution we need to go for here is to mark these particular tests as slow and increase their timeout threshold.

Our original criteria for moving tests to the slow group was if they run longer than 5 seconds on our dev machines, so these tests are clearly failing that and should be moved.

**Comment by dilijev** [comment]
Added a list of tests I've seen affected by this issue so far (I haven't checked in about a week, but that's from my notes).

**Comment by dilijev** [comment]
@ianwjhalliday Sounds good about moving them to slow tests. Still, we might try decreasing the number of CPUs used by rl.exe on those test machines first and see if that helps with any potential hypervisor-related CPU reclamation or stalling out.

**Comment by dilijev** [comment]
Just observed another file timing out:

`d:\j\workspace\Private\Microsoft_ChakraCore_daily_x64_debug\test\bailout\bailout-args.js`

**Comment by dilijev** [comment]
This build has been green for a few days. But since we didn't intentionally fix it I want to leave this issue open to track it until we figure out why the problem seems to be gone (or in case in comes back).

FYI @ianwjhalliday

**Comment by dilijev** [comment]
Information on the first build where the issue went away:

http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/daily_dev12_x64_debug/44
http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/daily_dev12_x64_debug/44/changes#detail8

**Comment by ianwjhalliday** [comment]
@dilijev do we think this issue has gone away now that it has been a few months?

**Comment by dilijev** [comment]
@ianwjhalliday Yeah I haven't seen the issue in a while. We can reopen this bug if it comes back.
