### ISSUE TITLE
Are public nightly builds of ChakraCore available somewhere?

### ISSUE THREAD

**Issue by iskiselev** [Microsoft/ChakraCore#1180]
It would be great, if Chakra will provide nightly builds (with ch), same as do Firefox SpiderMonkey (https://ftp.mozilla.org/pub/firefox/nightly/latest-mozilla-central/jsshell-win64.zip and others).
It will provide simple way to test big libraries with nightly builds and react early on potential Chakra, library or compatibility issues.

**Comment by dilijev** [comment]
@iskiselev see #85 https://www.myget.org/feed/chakracore-preview/package/nuget/Microsoft.ChakraCore

We publish ch.exe and ChakraCore.dll for both x64 and x86 in those packages.

We are basically using those packages as a publication mechanism for the binaries since NuGet packages are just zip files with some metadata and standard arrangement of files inside the archive.

They are intended to be nightly, but those builds are from branch release/1.2, which is in stabilization mode, and since there hasn't been much movement on that branch recently we haven't published that package for a couple of weeks.

I'm working on enabling publication of those packages from multiple branches so we can have the stabilization branch as well as the WIP branch, `master`, published there as preview packages.

**Comment by dilijev** [comment]
@liminzhu Maybe we can add a link to the MyGet feed https://www.myget.org/feed/chakracore-preview/package/nuget/Microsoft.ChakraCore added to the README?

**Comment by iskiselev** [comment]
@dilijev, thank you for provided information. It is what I've looked for!

**Comment by dilijev** [comment]
Great!

**Comment by dilijev** [comment]
I've rephrased the title and tagged as Question so that this is easy to find in the future for people looking for info.

**Comment by dilijev** [comment]
@iskiselev Just published a new one since you're looking for latest. See https://www.myget.org/feed/chakracore-preview/package/nuget/Microsoft.ChakraCore
