### ISSUE TITLE
Is it possible to build ChakraCore into .so and .a to use it on Android and iOS?

### ISSUE THREAD

**Issue by monutam91** [Microsoft/ChakraCore#1237]
Hi!

I have an application in which I have to run JavaScript code and I intend to use ChakraCore to do so. My problem is that this application is a cross-platform Xamarin app, thus I should build ChakraCore into a Shared Object (.so) and into a static library (.a)

Is it possibly to build ChakraCore like this? If it is, could somebody help me in this, just a little direction would be much appreciated!

**Comment by obastemur** [comment]
@monutam91 you can build ChakraCore for Ubuntu/Debian and very soon for OSX. https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore#linux 

At the moment ChakraCore may not work on Android and currently there is no IOS support. We will soon  update our cross platform roadmap (/cc @digitalinfinity )

/cc @jasongin since he has been working on Xamarin/Cordova and combined JavaScript cross platform.

**Comment by dilijev** [comment]
FWIW I believe we already have the ability to build either static or dynamic libraries on Linux. Dynamic is the default. Try running `build.sh` on Linux with `--static` flag.

**Comment by dilijev** [comment]
Updated title to rephrase as a question and make it easier for others to find the answer later.

**Comment by dilijev** [comment]
@monutam91 Did we answer your question?

**Comment by dilijev** [comment]
Adding the waiting tag to track the OS X portion of this question.

**Comment by dilijev** [comment]
We can now build ChakraCore on OS X: https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore#os-x

Removing the Waiting label.

**Comment by dilijev** [comment]
Closed because it is possible to build .so and .a on Linux and OS X. Whether they can be linked in Android and iOS apps seems like a separate question. If anyone has been able to do it, please let us know! If you know of any issues preventing those builds being used for that purpose (which we can help with) please open a new issue :)

**Comment by obastemur** [comment]
Just for a clarification; CC doesn't support iOS at the moment and same for Android.

We will need ARMv7 xplat support at least for Android (in general) and x86/arm64 for iOS. CC supports ARM on Windows and anyone looking into porting and/or contributing should fine lots of useful information available within the project.

ARMv7 and arm64 (xplat) are on my list but no timeline promises at the moment (unless CC roadmap says otherwise)
