### ISSUE TITLE
a question about JsDeleteProperty

### ISSUE THREAD

**Issue by gxlmyacc** [Microsoft/ChakraCore#128]
<pre>/// &lt;summary&gt;
    ///     Deletes an object&#39;s property.
    /// &lt;/summary&gt;
    /// &lt;remarks&gt;
    ///     Requires an active script context.
    /// &lt;/remarks&gt;
    /// &lt;param name=&quot;object&quot;&gt;The object that contains the property.&lt;/param&gt;
    /// &lt;param name=&quot;propertyId&quot;&gt;The ID of the property.&lt;/param&gt;
    /// &lt;param name=&quot;useStrictRules&quot;&gt;The property set should follow strict mode rules.&lt;/param&gt;
    /// &lt;param name=&quot;result&quot;&gt;Whether the property was deleted.&lt;/param&gt;
    /// &lt;returns&gt;
    ///     The code &lt;c&gt;JsNoError&lt;/c&gt; if the operation succeeded, a failure code otherwise.
    /// &lt;/returns&gt;
    STDAPI_(JsErrorCode)
        JsDeleteProperty(
            _In_ JsValueRef object,
            _In_ JsPropertyIdRef propertyId,
            _In_ bool useStrictRules,
            _Out_ JsValueRef *result);</pre>
result should be the <b>bool</b> type?

**Comment by ianwjhalliday** [comment]
The API returns an error code in case there is a failure or runtime error is thrown etc.  The bool result from the delete operation regarding whether or not the property was deleted is returned in the `result` parameter as a javascript value, `JsValueRef`. This value can be converted to C++ bool via `JsBooleanToBool`.

**Comment by gxlmyacc** [comment]
OK, I just want to make sure that the interface is not wrong. because the result of other functions are directly returned to the bool type,such as JsSetProperty, JsDefineProperty, JsHasIndexedProperty etc.

**Comment by ianwjhalliday** [comment]
@gxlmyacc ah interesting. It looks like this might have just been an artifact of the fact that the delete API is just a wrapper around our implementation of the javscript delete operator, which returns a javascript boolean, whereas the other APIs are wrappers of internal functions that are not tied to a javascript operator and happen to return BOOL.

Perhaps an unfortunate inconsistency.  However, since the API is already public it shouldn't be changed that this point.
