### ISSUE TITLE
Intl.DateTimeFormat adds extra unicode empty characters in Edge

### ISSUE THREAD

**Issue by laskoviymishka** [Microsoft/ChakraCore#1282]
Related to _https://github.com/angular/angular/issues/10080_
Seems like for formatting any component from `Intl.DateTimeFormat` it add and empty unicode character before result `&#x200E;`.
Reproduced in plnkr _http://plnkr.co/edit/57fHqSmRBsESgtJw79pq?p=preview_
In chrome - length of 19 is 2.
In edge - length of 19 is 3.
If you try to conert edge displayed result you may see `&#x200E;19`

**Comment by bterlson** [comment]
See also: https://github.com/Microsoft/ChakraCore/issues/599

Summary: Intl formatters insert bidi control characters so that appending strings in mixed-direction scenarios (eg. appending an en-us formatted date in some RTL text) just works. In general, the strings retrieved from Intl APIs should be treated as opaque because you are actually not guaranteed per spec that the format you request will be available on all platforms (let alone the strings be byte-for-byte identical).

**Comment by dilijev** [comment]
Closing as duplicate.
