### ISSUE TITLE
Add ability to create an ES6 class using JSRT APIs

### ISSUE THREAD

**Issue by joduskame** [Microsoft/ChakraCore#132]
Hello,

how would one approach creating a ES6 class using the JSRT C++ API? I've looked through the sample codes, no luck tho.

Thanks

**Comment by kunalspathak** [comment]
@joduskame , Thanks for the interest. Currently there is no way of creating ES6 classes using JSRT APIs. I will mark this as a Suggestion so we can re-evaluate this task.

**Comment by Yongqu** [comment]
Agree we should take a look to support class construction in JSRT.

**Comment by robpaveza** [comment]
An ES6 class is really just syntactic sugar for a constructor function and prototype inheritance.  The really special thing you get with class is access to the `super` keyword, but since the host can't access 'super' via native, that's kind of pointless.

It seems like the best way to define an ES6 class would be just to execute some script code that defines the class.  What is special about defining a class via native that you couldn't do with script?

**Comment by ianwjhalliday** [comment]
Agree with Rob.  Is there a strong motivating usage case for needing such an API?

I'm not intimately familiar with the JsRT APIs yet.  Are there analogous APIs for creating functions and objects?

**Comment by kunalspathak** [comment]
@ianwjhalliday  - There are APIs like `JsCreateObject` , `JsCreateArray`, `JsCreateFunction`.
I somewhat agree with @robpaveza , but curious to know from @joduskame  about the use case.

**Comment by joduskame** [comment]
Hello,

I guess I will just follow @robpaveza approach and assign the object a prototype.
