### ISSUE TITLE
Implementing js-style callbacks in C# using async/await

### ISSUE THREAD

**Issue by frabert** [Microsoft/ChakraCore#134]
I'm trying to implement js callbacks (à la [node.js fs API](https://nodejs.org/api/fs.html) ) using async/await in C#, but I'm having difficulties due to threading. This is my situation: I have a method
```c#
async Task<string> ReadFile(string path)
{
  return await DoWhatever(path);
}
```
which I would like to use in a non blocking manner like this:
```js
readFile(path, (err, content) =>
{
  trace(content);
});
trace('Hello, World!');
```

For this reason I set up my context like this:
```c#
global.SetProperty(JavaScriptPropertyId.FromString("readFile"), JavaScriptValue.CreateFunction((JavaScriptValue callee, bool isConstructCall, JavaScriptValue[] arguments, ushort argumentCount, IntPtr callbackData) =>
{
  var args = arguments.Skip(1);
  var path = args.First().ToString();
  var callback = args.Skip(1).First();

  var task = ReadTextAsync(path);

  task.ContinueWith((content) =>
  {
    JavaScriptContext.Current = context; // This is the incriminating line
    if (task.Status == TaskStatus.RanToCompletion)
    {
      callback.CallFunction(JavaScriptValue.Undefined, JavaScriptValue.FromString(task.Result));
    }
    else
    {
      callback.CallFunction(JavaScriptValue.False);
    }
   });
  return JavaScriptValue.Undefined;
}), true);
```
If I omit that line, I get an exception because there is no current context set, but if I put that line, I get an exception about the code being executed in another thread, which is apparently illegal. What can I do? I've already tried doing `.ContinueWith(..., TaskScheduler.FromCurrentSynchronizationContext());`, but then I get an exception because the continuation cannot be run from the same scheduler.

**Comment by liminzhu** [comment]
JSRT is [rental-threaded](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview#concepts), i.e. a runtime can only live on one thread at a time. What you can do is before jumping to another thread with Task.ContinueWith, let the current thread give up its control on the runtime by ```JavaScriptContext.Current = JavaScriptContext.Invalid;```. Before Task.ContinueWith finishes, you probably want to give up the runtime control again so that other threads can use the runtime later. Let me know if it works for you.

**Comment by frabert** [comment]
Will try that as soon as I can... However I don't understand how this can be nonblocking: if I invalidate the main thread to run the async one, how is the main thread supposed to continue running even when the other is blocked? Wouldn't that throw another exception?

**Comment by liminzhu** [comment]
Yeah sorry you're right. In this case, you only get your code to not throw but it's not really non-blocking.

A better solution I can think of is instead of running the callback on a spawned thread, you can dispatch the callback back to main thread, queue it and run it after your current script is finished. This mechanism is similar to [handling promises](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview#promises). This way you don't have to block your main thread to execute javascript on other threads.

**Comment by liminzhu** [comment]
This is similar to node's event loop if that makes sense.

**Comment by frabert** [comment]
Thanks. I will try that way!

**Comment by frabert** [comment]
I am approaching this issue using jsrt-dotnet, see the issue here: https://github.com/robpaveza/jsrt-dotnet/issues/2

**Comment by EdMaurer** [comment]
Hi @frabert, is there more to add to this issue? If not, I'd like to close it.

**Comment by frabert** [comment]
Yes, I will continue the discussion on the linked issue. This can be closed.
