### ISSUE TITLE
JSRT: Improve JsGetValueType API

### ISSUE THREAD

**Issue by kunalspathak** [Microsoft/ChakraCore#135]
Current JsGetValueType only recognizes high level types. Improve it to recognize other types like RegExp, Date, Map, Set, etc.

**Comment by robpaveza** [comment]
I don't think this is a good idea.

When we were discussing the design of `JsGetValueType`, the real question was *what are the special kinds of values that the host needs to know about?*  The host needs to be able to do special things, for example, for ArrayBuffer (in order to access the underlying memory), the primitive types supported by JavaScript (for marshaling), Objects (because they can have properties), Functions (so that you know you can call them), Symbols (because they have special meaning for properties), Arrays (because indexed properties behave in a special way) and that is the most part of it.

If you want to know that an Object is a RegExp, you can look at its `constructor` property and compare it to the global object's `RegExp` property.

**Comment by liminzhu** [comment]
Agree with Rob. Another reason is that this would be a breaking change and unless there's a really compelling reason we shouldn't do it.

**Comment by kunalspathak** [comment]
Why would this be breaking change? We will be returning more JsValueTypes than today.

**Comment by ianwjhalliday** [comment]
I presume because today we return "object" for Map instances for example

**Comment by kunalspathak** [comment]
That way, sure.

**Comment by EdMaurer** [comment]
@kunalspathak are you in agreement that this suggestion is a no-go?

**Comment by kunalspathak** [comment]
I agree with @liminzhu that this is breaking change. However `constructor` check mentioned by @robpaveza doesn't guarantee that the underlying object is of that type. There are two scenarios in which it could fail. Correct me if I am wrong here.

**Scenario 1**

```js
// RegExp object having all internal slots
var x = /a/;
x.constructor == RegExp; // true
x.exec('string'); // returns array of matches or null.

// obj is an object whose prototype is RegExp object
var obj = Object.create(RegExp.prototype);
obj.constructor == RegExp; // true

// However something like this doesn't work with such objects.
// It would throws error: "RegExp.prototype.exec: 'this' is not a RegExp object"
obj.exec('a'); 

```

Right way to do this would be by using `Object.prototype.toString.call(o)` as explained in [this](http://web.mit.edu/jwalden/www/isArray.html) post.
```javascript
Object.prototype.toString.call(x); // [object RegExp]
Object.prototype.toString.call(obj); // [object Object]
```

We can compare the output of `Object.prototype.toString.call` instead to know the type of an object and this is precisely what I did in https://github.com/Microsoft/node/commit/6c70170eafd5dc9945cf5b553d3171fab7ff9a10 for fixing some unit test.

When an output is `[object RegExp]`, we know for sure that object has internal slots of RegExp intrinsic object. This works pretty well for object types like `Map`, `Set`, etc. (unless someone overriders `Symbol.toStringTag` of that object.)


**Scenario 2**

If an object `obj` is a RegExp created in different context, in order to compare `x.constructor` against `RegExp`, the `RegExp` has to be from the same context as `obj`. So in multiple context scenarios, if I want to know if `obj` is a `RegExp`, I will have to keep track of `global` objects from all contexts and extract the right `global` object (and hence `RegExp`) from the same context as of `obj` and then do the comparison.
I faced this situation too in node+chakracore unit test and addressed it by using `Object.prototype.toString.call` mechanism.

It would have been much easier to fix those unit test by simply calling `JsGetValueType`, had we returned more specific object types. I feel that JsValueType should be based on internal slots of objects rather than conveying host what it can do with it.
With new value types that I am proposing, host can still retain to generic types, the way we have today, by doing something like this :
```c++
JsValueType type = JsGetValueType(obj);
switch(type) {
  case JsRegExp:
  case JsDate:
  case JsMap:
  ...
      return JsObject;
}
```

**Comment by kunalspathak** [comment]
@Yongqu , thoughts?

**Comment by jianchun** [comment]
So far we don't have very compelling reasons to add this capability, other than that node uses v8 API and exposes the capability to scripts. We have very inefficient shim implementations for it. Assuming performance doesn't matter here, this is low priority. We can revisit if performance issue does show up.

If we really need to add this, we could consider a new API.

**Comment by kunalspathak** [comment]
The proposed JSRT APIs will not only benefit the performance, but will also avoid having workarounds (and possibly bugs) we currently have in shim to extract same information without APIs. 

E.g. Microsoft/node-uwp#13 is happening because shim tries to execute `isRegExp` by calling the `Object.prototype.toString` and fails. We could avoid this by having JSRT API.

**Comment by liminzhu** [comment]
Again as I mentioned before this would be a breaking change: wherever ```JsObject``` appears, there is a potential bug after this change. ```JsGetValueType``` was originally designed to mimic ```typeof```, but we added arrays and typedarrays because as Rob suggested they do special things: indexed properties behaved differently and you can access underlying memory of typearrays. You get perf gains from these added types. The downside is that the behavior of ```JsValueType``` is harder to reason about. If we add RegExp, Map, etc., it'll be even harder. What is ```JsValueType```? What about Promise/Proxy/Generator? One would have to browse through all enum values to reason about how the ```JsGetValueType``` can be used.  

On the other hand, it does seems there's well-established workaround for RegExp & etc. by running a small script...

**Comment by kunalspathak** [comment]
> by running a small script...

The small script doesn't work in all scenarios and breaks as pointed in node-uwp example. 

I am ok to not modify `JSGetValueType` , but we should consider adding new APIs that can tell us type of object based on [internal slots](http://tc39.github.io/ecma262/#sec-object-internal-methods-and-internal-slots) of objects.

**Comment by EdMaurer** [comment]
There does not appear to be strong demand for a change here. Closing
