### ISSUE TITLE
[OSX, Ubuntu] [master] {debug} array_slice.js test timeout caused build failure

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#1406]
Intermittent test timeout in `Array/array_slice.js`

# OS X

Multiple instances:

http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/master/job/osx_osx_debug_static/9/consoleText

http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/master/job/osx_osx_debug_static/11/consoleText

```
[904/1248 60.11] Failed -> Array/array_slice.js
ERROR: Test timed out!
/Users/dotnet-bot/j/workspace/Microsoft_ChakraCore/master/osx_osx_debug_static/BuildLinux/Debug/ch -WERExceptionSupport -ExtendedErrorStackForTestHost -BaselineMode -maxInterpretCount:1 -maxSimpleJitRunCount:1 -bgjit- /Users/dotnet-bot/j/workspace/Microsoft_ChakraCore/master/osx_osx_debug_static/test/Array/array_slice.js

Output:
----------------------------


1,2,3,4,5,6,7,8
4,5,6,7,8

1,2,3,4,5,6,7,8
2,3,4
3,4




----------------------------
exit code: -9
```

# Linux

http://dotnet-ci.cloudapp.net/job/Microsoft_ChakraCore/job/master/job/daily_ubuntu_linux_debug_static/31/console

```
[341/1249 60.03] Failed -> Array/array_slice.js             
15:55:34 ERROR: Test timed out!
15:55:34 /mnt/j/workspace/workspace/Microsoft_ChakraCore/master/daily_ubuntu_linux_debug_static/BuildLinux/Debug/ch -WERExceptionSupport -ExtendedErrorStackForTestHost -BaselineMode -maxInterpretCount:1 -maxSimpleJitRunCount:1 -bgjit- /mnt/j/workspace/workspace/Microsoft_ChakraCore/master/daily_ubuntu_linux_debug_static/test/Array/array_slice.js
15:55:34 
15:55:34 Output:
15:55:34 ----------------------------
15:55:34 
15:55:34 
15:55:34 1,2,3,4,5,6,7,8
15:55:34 4,5,6,7,8
15:55:34 
15:55:34 1,2,3,4,5,6,7,8
15:55:34 2,3,4
15:55:34 3,4
15:55:34 
15:55:34 
15:55:34 
15:55:34 
15:55:34 ----------------------------
15:55:34 exit code: -9
```

**Comment by digitalinfinity** [comment]
@obastemur can you take a look and see if there is flakiness with this test on OS X?

**Comment by obastemur** [comment]
That particular test takes 14 seconds on a 2.9Ghz Quad Core macBook pro. When the CI is busy (probably sharing the same physical machine for many others) this test takes much longer time to complete.

**Comment by dilijev** [comment]
@obastemur That sounds about right. My feeling is that 14 seconds on a reasonable non-busy machine is still too long. @ianwjhalliday do you concur?

**Comment by ianwjhalliday** [comment]
The test runs in about 12 seconds on my work desktop (Xeon E5-1620 3.6 GHz).

The reason it takes so long is that it has a loop from zero to one million setting an array's elements all to zero.  With JitLoopBody on, this happens much quicker, running around 1 second on my machine, but we run this test in the interpreted variant where `-nonative` is specified.

I tried removing the initializing loop and that brought the time down to a tenth of a second.  I don't think the loop is necessary since the array will be initialized to all undefined and the test is only verifying that the size of the slice is the correct, not its contents.
