### ISSUE TITLE
An idea for tail calls

### ISSUE THREAD

**Issue by DemiMarie** [Microsoft/ChakraCore#1410]
I think ChakraCore could implement tail calls without an undue performance penalty by using explicit frame pointers.  As I understand it, LLVM _does_ support proper tail calls on Windows x64 (and does so even with separate compilation – so LLVM cannot just preallocate space in the caller, since it doesn't know the amount of stack space the callee will need).  Therefore, LLVM must be able to emit proper unwind info, and I suspect they use a frame pointer for this case (the so-called `fastcall` LLVM calling convention).

**Comment by LouisLaf** [comment]
Chakra already does use an explicit frame pointer, but this is not really the issue.  The main issue is that all function in JavaScript have a variable argument list (arguments are optional and passing extra is ok).  LLVM does not do tail call if the caller has a variable argument list.

Without an variable argument list, a compiler can emit code to deal with the specific situation: same number of in/out args, less out args or more out args.  It can also decide to only handle some of these situations.  With variable argument list, the JIT needs to emit code to handle all of these decisions, and dynamically pick the right code path at runtime.

Compilers also use a "caller-cleanup" calling convention for variable argument list calls, since the caller statically knows the amount of stack space to cleanup after the call.  For tail call, you need to use a callee-cleanup convention since the original caller does not know the amount of stack to cleanup for the tail call callee.

On Windows x64, a fixed-stack calling convention is used makes it really hard to support these complex stack manipulation without requiring extra frames (which defeats the whole purpose) or some pretty severe performance penalty.

**Comment by DemiMarie** [comment]
As I understand it, one benefit of an explicit frame pointer is that it
allows SP to change in the middle of a function, since the frame can be
statically unwound using FP.  The callee already knows how many arguments
it has, otherwise arguments.length would not work.  So it can pop the
appropriate amount dynamically.

On Aug 22, 2016 5:46 PM, "Louis Lafreniere" <notifications@github.com>
wrote:
>
> Chakra already does use an explicit frame pointer, but this is not really
the issue. The main issue is that all function in JavaScript have a
variable argument list (arguments are optional and passing extra is ok).
LLVM does not do tail call if the caller has a variable argument list.
>
> Without an variable argument list, a compiler can emit code to deal with
the specific situation: same number of in/out args, less out args or more
out args. It can also decide to only handle some of these situations. With
variable argument list, the JIT needs to emit code to handle all of these
decisions, and dynamically pick the right code path at runtime.
>
> Compilers also use a "caller-cleanup" calling convention for variable
argument list calls, since the caller statically knows the amount of stack
space to cleanup after the call. For tail call, you need to use a
callee-cleanup convention since the original caller does not know the
amount of stack to cleanup for the tail call callee.
>
> On Windows x64, a fixed-stack calling convention is used makes it really
hard to support these complex stack manipulation without requiring extra
frames (which defeats the whole purpose) or some pretty severe performance
penalty.

**Comment by DemiMarie** [comment]
Am I correct that this idea would work for CoreCLR?

**Comment by LouisLaf** [comment]
The ability to allocate stack isn't sufficient however.  The return address also needs to be moved.  But the OS needs to find the original if an exception occurs.

**Comment by DemiMarie** [comment]
No, the return address does not need to be moved.

By definition, a tail call has the same return address as the caller.

**Comment by LouisLaf** [comment]
The return address does need to be moved if the tail call needs more argument space then the caller has available:

function foo(a, b) {
    bar(a, b, c, d);
}

Where do you put c and d?

**Comment by DemiMarie** [comment]
Ahh.. now I get it.

The obvious answer is "push the return address before a in both cases" but
the Windows ABI almost certainly forbids that.

Another option is to put the parameters that would go on the stack on a
"shadow stack" allocated on the C heap.

Yet another option is to not bother with OS unwinding across JS frames and
use RtlInstallFunctionTableCallback to register a handler that just jumps
across the JIT-compiled code.  Try/catch and try/finally can be lowered to
function calls taking callbacks, and all C++ exceptions can be caught, with
a longjmp across the JIT-compiled code in the catch block.

**Comment by DemiMarie** [comment]
Another thought would be to have JavaScript functions pass parameters in a runtime-global storage block instead of on the stack.  That way, each JS function has a bounded number of parameters (which can be fixed), but there would be a perf penalty.

**Comment by dilijev** [comment]
Doing some issue cleanup. Linking to related discussion #796 and closing this issue.
/cc @kfarnung @agarwal-sandeep
