### ISSUE TITLE
[Tests] Add test timeout *warning* at a lower threshold than *error* so we can detect test runtime regressions before they start causing errors.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#1425]
Converted from a Discussion issue. See discussion below for task proposal.

---

Our unit tests are intended to be functional tests, not performance tests, so to some extent we don't really care how long they take as long as we get a pass or fail result in a reasonable amount of time. For practical reasons, we added a timeout to catch tests if they start to take a long time or if a test is introduced which runs effectively forever so that we don't bog down our test VMs.

Setting the individual timeouts high enough that we only timeout on truly problematic tests is helpful, but doesn't really give us a sense of whether they are starting to take too long.

One proposal on the table is #1413 -- simply increase the default timeout so that we don't see as many timeouts when running on low-resource VMs. Since we've only seen a few problematic tests, we opted for #1421 for the time being, pending discussion.

If we see some value in tracking test runtime regressions, maybe we need to add something else to the runner.

Maybe we should add a warning threshold that will issue a warning when tests take a long time without breaking the build. Then we could set the warning threshold at 60s and timeout at 120s?

/cc @ianwjhalliday who implemented timeouts
FYI @obastemur 

See recent PRs related to test timeouts:
#1413
#1421

And recently opened issues:
#1406 [fixed]
#1417 [fixed]
#1407 [open]

**Comment by ianwjhalliday** [comment]
A very low threshold warning and a higher timeout would be reasonable.  We want to guard against adding slow tests, but can't control the resource performance of all machines and so should give some breathing room for the actual timeout.  A warning + timeout would give us that.  However, it would also add noise on low performance machines where tests consistently run longer than the warning threshold.  Notably CI runs.

I prefer we be vigilant that tests be very lean over introducing a more complex system personally.  However I think the warning + timeout approach would not be unreasonable if someone can design a good system that won't cause headache and has time to implement it.  If such a design I would recommend setting the warning threshold low (5 sec?) to keep the majority of tests tight and quick, because they very quickly add up in aggregate.

**Comment by dilijev** [comment]
@ianwjhalliday Cool. Sounds good. Although someone needs to actually implement the warning system. I imagine it would be the same as the timeout error except that it emits a warning instead of an error, and would use a different tag name like `<timeout-warning>` to override the default?

**Comment by dilijev** [comment]
A warning system would be more complex and would introduce noise. We haven't had as many issues with timeouts recently. Closing this issue for now.
