### ISSUE TITLE
JavaScript Performance issue

### ISSUE THREAD

**Issue by qina16** [Microsoft/ChakraCore#1432]
When parse large amount of data with JSON format (10MB) to Browser, IE11 takes more than 5 minutes to load the screen, but Chrome and FF on the same client can load it with 10-20 seconds.

**Comment by liminzhu** [comment]
Thanks for the input @qina16 . Unfortunately development for IE11 is pretty much limited to security updates, and the browser and JS team has been focusing on Microsoft Edge since it rolled out with Windows 10. As you can imagine, as a result IE11 performance now is not on the same level as the latest Edge/Chrome/FF, and I'd recommend you use and test against Edge which has the latest language support and performance updates, if it's possible.

**Comment by bterlson** [comment]
Closing this (JSON.parse is much faster in Edge, perf improvements wont-fix IE11).
