### ISSUE TITLE
Support for Visual Studio 2013

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#1484]
I am wondering how long do we plan to support VS 2013?
In PR https://github.com/Microsoft/ChakraCore/pull/1444 I started using `constexpr` on some functions to avoid using macros.

Before I reverted those change, I believe it would be worth checking if we planned to drop support soon.

**Comment by Cellule** [comment]
@curtisman @digitalinfinity @dilijev @LouisLaf @MikeHolman Any thoughts on the matter ?

**Comment by dilijev** [comment]
`constexpr` is a great feature we're missing out on. This isn't the first time it has come up. Since VS 2015 has a community edition that anyone can use for free, I'm seeing less of a compelling reason to keep supporting downlevel products because "people have already paid for those". Possibly you could argue "people are used to the workflow" but I don't think much of the community is depending on a VS 2013 workflow for our project.

**Comment by ianwjhalliday** [comment]
Agreed.

I may be mistaken, but I believe VS 2013 is the only non-fully compliant C++ 11 compiler we support.  It would be nice to have the full C++11 feature set available for us to use, by dropping VS 2013.

 - Use of constexpr came up once before in #309 
 - We thought about using C++11 `char16_t` and `u"..."` for xplat strings in #456 but couldn't because VS 2013 doesn't have it

I believe there were one or two other issues that came up where it would have been nice to have full C++11 support.

**Comment by tcare** [comment]
+1, though I seem to remember there being being issues about downlevel and ARM.

**Comment by curtisman** [comment]
Node still support building with VS2013.

**Comment by dilijev** [comment]
^ And that right there is the only reason we need to keep supporting VS 2013. :P

**Comment by ianwjhalliday** [comment]
That is too bad.  Doesn't mean node-chakracore needs to support VS2013, but reasonable to do so.
