### ISSUE TITLE
Getting JsErrorNoCurrentContext while trying to invoke a callback block

### ISSUE THREAD

**Issue by Kureev** [Microsoft/ChakraCore#1576]
Hi there,

I'm getting `JsErrorNoCurrentContext` error while error is definitely there (see screenshot below). The flow is following: in the main thread I spawn a ChakraCore thread. When JS invokes one of my custom functions, I use `dispatch_async` to call something in main thread. After work is done, I need to invoke a callback which I pass from the JS. Unfortunately, in 90% of my attempts I get random errors like no context or wrong arguments. Don't really get what happens under the hood. Seems that behavior is absolutely unpredictable.

What do I do wrong?

![image](https://cloud.githubusercontent.com/assets/2273613/18492655/b3d4ad38-7a0c-11e6-9016-605f7c3d8703.png)

P.S. I have a feeling that I hold a void * to the memory which has been rewritten (for some unknown reason). That may explain why it works in ~10% cases

**Comment by Kureev** [comment]
You can also find sources here: https://github.com/Kureev/GoldenGate

**Comment by liminzhu** [comment]
Can you check the error code from ```JsSetCurrentContext```? Have a hunch that your context might have been GC'ed. Try ```JsAddRef``` on the context when you left the context and ```JsRelease``` the context when it can be disposed.

**Comment by Kureev** [comment]
In one of my iterations I've used `JsErrorCode` to check if there is an error in this call, but everything is OK - `JsNoError`. I'll look into `JsAddRef`/`JsRelease` tomorrow in the morning and post you back the results. Thank you for your advices!

By the way, do you know if there are any examples of JsAddRef/JsRelease? Should I add a ref before the block definition and release it in the callback?

**Comment by liminzhu** [comment]
In general, add-ref before the var becomes invisible to GC (leaving the stack, etc) and release as soon as you no longer need it. I've done something similar in this [example](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/OpenGL%20Engine/OpenGLEngine/Task.cpp) where I [add-ref](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/OpenGL%20Engine/OpenGLEngine/Task.cpp#L16) to a var before the stack pops and release it in the [destructor](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/OpenGL%20Engine/OpenGLEngine/Task.cpp#L33). Pinning down context is necessary when the runtime switches to a different context since otherwise the runtime has no reference to the old context so it become garbage collectible.

I'm taking a closer look to your code. It seems the runtime is always on the same context since that context is first created, no? If so, then adding ref would be unnecessarily b/c ChakraCore obviously wouldn't just GC your current context. It might be some other problem.

**Comment by Kureev** [comment]
Ok, it's 100% about GC, but I have no idea when/where. If I remove UI code, it works better. Fails only in ~10%. So seems something is GCed when we switch to the main queue. I tried JsRefs etc - no luck so far.

**Comment by Kureev** [comment]
Small update:

I found out that my attempt to set an active context fails: `JsErrorWrongThread`. Could you be so kind to explain me what it means? I use dispatch_async to main_thread and then back again. Don't really get why it complains about the thread.

**Comment by liminzhu** [comment]
// FYI @Yongqu 

I see. The idea is that JSRT is rental-threaded. See [concepts](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview#concepts),
> Runtimes represent a single thread of execution. Only one runtime can be active on a particular thread at a time, and a runtime can only be active on one thread at a time. Runtimes are rental threaded, so a runtime that is not currently active on a thread (i.e. isn’t running any JavaScript code or responding to any calls from the host) can be used on any thread that doesn’t already have an active runtime on it.

`JsErrorWrongThread` happens when those rules are broken. Typically if you wish to move runtime from thread1 to thread2, you can to call `JsSetCurrentContext(nullptr)` on thread1 first to give up the runtime, then `JsSetCurrentContext(someContext)` on thread2. 

On which thread does the [callback](https://github.com/Kureev/GoldenGate/blob/master/GoldenGate/Source/ChakraProxy.mm#L63) get called? If it's a different thread than where the runtime is, it'd cause problems.

**Comment by Kureev** [comment]
Hi again,

I can't express how I appreciate your detailed and fast responses ❤️ It makes my experience with Chakra even more smooth 😉 I solved my problem. For those who's interested, I'll explain what happen and how I worked my issue around:

First of all, it was my bad. My lack of understanding the way how GCD works bite me in the ass: I expected that if I have a custom queue, it'll always dedicate one single thread and work inside it. But, as you could guess, I was wrong. GCD **always** use random threads. So, every time I tried to dispatch_async to my background chakra thread, I was spawning a new one and tried to invoke a js callback inside it. That's why I had `JsErrorWrongThread`. When I rewrote my implementation to use `NSThread`, the problem went away! Code became way more simpler.

Thanks a lot again!
