### ISSUE TITLE
s/BOOL/bool 

### ISSUE THREAD

**Issue by tfarina** [Microsoft/ChakraCore#160]
Is there a reason not to use bool type? Isn't ChakraCore implemented in C++?

**Comment by robpaveza** [comment]
Chakra, being based on Windows, has occasion to use the Windows [BOOL](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383751(v=vs.85).aspx) type over the ABI.  

One example reason is that various compilers can implement the `bool` C++ type differently at the ABI.  Windows' definition is consistent among compilers that want to target Windows.

It might conceptually be possible to s/BOOL/bool at least among the internal boundaries without breaking compatibility.  But I would venture that making the change would be nontrivial, and since Chakra started in the early 90's, that there's primarily a historical reason that it is the way it is.

**Comment by LouisLaf** [comment]
There are performance advantages to BOOL over bool.  The main situation is for return values, where bool values need to be coerced to 0 or 1, as BOOL can be 0 or not 0.  'bool' also only sets the low byte of RAX, so AL often needs to be zero-extended at the call-site.
Unfortunately however, BOOL is typedef'd to 'int' on Windows.  So 'bool' is more compact in data-structures than 'BOOL'...
So bool is better (size wise) in data-structures, BOOL is better (perf wise) for return values...  Yes, consistency would be nice.  A Bool typedef'd to uchar would solve these issue, but still wouldn't satisfy your desire to see the code more C++ like.

**Comment by tcare** [comment]
Also, changing this is quite a lot of effort. We've tried to do this in the parser multiple times as a drive-by cleanup, but it ends up spiraling out into having to fix compiler breaks everywhere. At least for parser/bytecodegen which I primarily work on, we tend to use bool in new code unless we have to interface with something that would require a conversion, or there is some other explicit reason for it such as the reasons Louis mentioned above.

**Comment by ianwjhalliday** [comment]
Yeah this is a topic that comes up whenever we get new eyes on the code base.  BOOL is so ugly imo.  Perhaps with the linux port happening now we can move to something a little less ugly for the return type usage of BOOL?  A typedef named something explicit like `boolret` perhaps?

I don't know if there is a conversion penalty to go from `bool` to an `int` type.

**Comment by phistuck** [comment]
@robpaveza -
> since Chakra started in the early 90's, that there's primarily a historical reason that it is the way it is.
Weird - I thought I read that Chakra was written from scratch (for Internet Explorer 9)?

**Comment by tcare** [comment]
Parts of Chakra were ported from the legacy JScript/VBScript engine, in particular some of the parser/scanner code. The difference is huge now, but you can still see some remnants of the old engine in files like lib\Parser\rterrors.h. We should probably clean that up at some point.

**Comment by dilijev** [comment]
Yeah, conceptually rewritten from the ground up. But, for the parts that worked and weren't tied to legacy support modes, we reused some code. The code style around code that interacted with that code and nearby code would have been written to match the style. Sometimes there may be good reasons for `BOOL` and in other places it might be "just because".

**Comment by dilijev** [comment]
As it happens, I was recently one of the "new eyes" @ianwjhalliday mentioned since I'm relatively new to the team. I found a couple of the "just because" cases and converted them.

**Comment by LouisLaf** [comment]
Also, early on in IE9, the register allocator didn't handle 8bit registers (like AL), so we couldn't generate the right code for a call to a helper returning bool.  All helpers called from the JIT used BOOL.

**Comment by ianwjhalliday** [comment]
@LouisLaf is that something we can support now then? Would it have a negative impact on performance?  I wouldn't entertain the idea of removing usage of BOOL if we weren't doing the linux port but it does sound like a nice ideal to strive for platform independent code base that does not use windows.h types.

I know we've got the PAL thing, so this is just a conversation about ideals at the moment.

**Comment by dilijev** [comment]
re @tcare's comment on cleanup in `lib\Parser\rterrors.h` see #214

**Comment by LouisLaf** [comment]
Well, the codegen would need to be changed to match the return type, but yes we do support it now.
As I said, bool is often slower because of the explicit coercion to 0 or 1.  On a lot of code paths it does not matter.

**Comment by EdMaurer** [comment]
@tfarina, if there's nothing more to add to this issue, then I'd like to close it.

Ed

**Comment by tfarina** [comment]
Do whatever you think it is best for the project. I don't anything to add here.

I will just look foward to see how this is going to work on Linux.
