### ISSUE TITLE
add c# class to context

### ISSUE THREAD

**Issue by oguzhankarsli** [Microsoft/ChakraCore#1609]
Hi, 
i try to add c# class to chakracore context. After i want to invoke from javascript. 
How can i do it?

**Comment by dilijev** [comment]
Have you tried following the documentation at https://github.com/Microsoft/ChakraCore/wiki/Embedding-ChakraCore and the example at https://github.com/Microsoft/Chakra-Samples/tree/master/ChakraCore%20Samples/Hello%20World/Windows/C%23/HelloWorld ?

Could you be more specific about what you have tried so far?

@liminzhu is there an example where we show how to expose a C# class as a JavaScript type and then call it from JavaScript?

**Comment by liminzhu** [comment]
[This](https://github.com/Microsoft/Chakra-Samples/tree/master/ChakraCore%20Samples/JSRT%20Hosting%20Samples/C%23) would be a better sample to look at. See how `Echo` gets projected into JavaScript in [ChakraCoreHost.cs](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/JSRT%20Hosting%20Samples/C%23/ChakraCoreHost/ChakraCoreHost.cs).

**Comment by oguzhankarsli** [comment]
Thank you. I examine sample project. I see Echo function.
But sample project doesn't include an example javascript. How to invoke function like Echo function in javascript. 
Can you give me an example please?

**Comment by dilijev** [comment]
You would simply call it as:

```js
Echo("string")
```

**Comment by liminzhu** [comment]
Minor nitpick - the `echo` function is a property of the `host` object, so `host.echo("string")`.

**Comment by dilijev** [comment]
@liminzhu - Thanks - I didn't realize that. Updated inline.

**Comment by oguzhankarsli** [comment]
i think that misunderstanding
i want to write code, for example,

`public int EchoFunctionCSharp(int a,int b){
     return a+b;
}

var javascript = @" var result = EchoFunctionCSharp(3,5);" +
                                        " return result;"


Native.JsRunScript(javascript, currentSourceContext++, "", out result);`

How can i write this example code to invoke csharp function?

**Comment by dilijev** [comment]
In the example I wrote inline above, the C# function called `EchoFunctionCSharp` is exposed to JavaScript as `host.echo`.

**Comment by oguzhankarsli** [comment]
Hi,

When i invoke c# function from javascript like **Echo()** function, **Echo()** function return **JavaScriptValue**. 
How i can get c# object to javascript from Echo function?

**Comment by liminzhu** [comment]
> How i can get c# object to javascript from Echo function?

Can you clarify on that part? Are you asking about the marshaling between C# objects and `JavaScriptValue`? For values that are not intrinsic to JavaScript, you can create JavaScript vars by [JsCreateExternalObject](https://github.com/Microsoft/ChakraCore/wiki/JsCreateExternalObject) and put whatever you want on the `data` param (e.g. the C# object itself), so that later on if another native function encounters such an external object (e.g. the external object is the callee or gets passed in as argument), the program can retrieve whatever was put in `data` through [JsGetExternalData](https://github.com/Microsoft/ChakraCore/wiki/JsGetExternalData), and do whatever C# things on `data`. 

Note that if you wish to invoke any C# methods on the external object, you still need to project the those methods into JavaScript (like what @dilijev showed you in the case of an `Echo` function), otherwise ChakraCore just sees your external object as a var and has no understanding of the C# methods.

**Comment by EdMaurer** [comment]
Looks like this thread has run its course.

**Comment by dilijev** [comment]
Renamed the title to make it easier for others to find the content of this discussion in the future.
