### ISSUE TITLE
Why there is a mix of filenames?

### ISSUE THREAD

**Issue by tfarina** [Microsoft/ChakraCore#161]
Some are named using CamelCase others are lower case. This is very annoying.

**Comment by dilijev** [comment]
We do most of our development on Windows, which uses NTFS, which is not a case-sensitive file system. Most of the files were created in an older source control system, and moving them between that system and Git probably could have been smoother than it was. Also renaming files to the same name with different casing is not a straightforward operation on Windows.

So when we migrated to the open repo, we did our best to let Git normalize line endings to Unix-style line endings except where it would break things (.js and .baselines, .cmd scripts, files processed by tools which require CRLF, etc.). We also trimmed trailing whitespace, converted tabs, and other little cleanup tasks of that kind, but the casing issue didn't come up in our discussions (because it's mostly invisible to us).

I'm not sure how disruptive changing the case of the all-lowercase files to CamelCase would be. Certainly it would be difficult to do all at once. I'll bring it up on the team and see if we can produce some kind of plan for that. Most likely, we will just convert them as we come to them.

Thanks for pointing out that this is annoying! :)

**Comment by dilijev** [comment]
Considering that casing is going to be more important in the cross-platform effort, this transformation might fall under that effort, but I think the best way to mitigate long-term impact, merge-conflicts, and so on would be to make those changes in `master` and merge them into the `linux` branch as needed. I believe Git is case-sensitive and so making this change would could as a file move, which would be very difficult to merge if the files were modified in multiple branches.

Perhaps @jianchun can advise?

**Comment by tcare** [comment]
@tfarina as Doug mentioned, it is a legacy thing that was just not a priority to fix. Off the top of my head I don't think we would have much break, but as we work more on Linux support this may be harder to integrate. If it's low impact @digitalinfinity and @jianchun may prefer to make this change now. However I suspect this will just be 'best effort' going forward and all new files will need to conform to the style rules (including camel case.)

Thanks for the input!

**Comment by dilijev** [comment]
@tcare as for impact I was thinking mainly about the general impact of moving a file. True the casing won't affect windows, but I believe the fact that git will register the change as a file move will cause issues in moving files. For files with relatively little activity, renaming them should have no impact except to the casing of header includes on the `linux` branch.

**Comment by nojvek** [comment]
>  but I believe the fact that git will register the change as a file move will cause issues in merging files. 

Does this mean the chakra teams works on their own repo and periodically syncs with the git repo?

**Comment by Cellule** [comment]
The main problem with casing when working on Windows is that it doesn't matter for the OS.
Therefor, git might have checked in a file `somefile.cpp` but in our explorer we see `SomeFile.cpp` and this works fine, until we go cross platform.
I have seen very problematic case where some file would have different casing for their folder. 
eg: `somepath\SomeFile.cpp` and `SomePath\otherfile.cpp` 
On Windows these 2 files would be in the same directory, but not on linux or mac for instance.

This is a particular painful thing to fix because git doesn't recognize a file to be renamed on Windows if we only change the casing.
My usual fix is to create 2 commits that renames the file
`somefile.cpp` => `_somefile.cpp` => `SomeFile.cpp`
I don't remember the fix for directory issues, but I think for now we are fine or we would have seen that error sooner in our cross-platform effort.

**Comment by nojvek** [comment]
Have you folks tried running git config core.ignorecase false

Is this something I can help with? If I change case, and all tests pass,
does that mean nothing else will break?

Thanks.

**Comment by dilijev** [comment]
@nojvek To your earlier question about our code flow from here to internal: we use ChakraCore as a git submodule of our internal Chakra repo which includes the internal components that connect with Edge etc, and we update the submodule hash continuously (every time there is a commit to master), so the version of ChakraCore we use internally is exactly the version that is worked on here.

I don't think we knew about core.ignorecase. Do you know what the implications of adding that now would be? You could try it and see what happens. We will do extra testing to make sure nothing broke. If it builds, there's a good chance we'll be fine.

Still I think a more conservative option is to take the best-effort rename-as-we-go approach.

@tcare @digitalinfinity thoughts?

**Comment by jianchun** [comment]
Yes, we've run into this problem on Linux. I talked to @digitalinfinity the other day and we thought we should fix this, probably standardizing (at least most) filenames to CamelCase. I'm trying it out.

**Comment by jianchun** [comment]
Sent #303

**Comment by jianchun** [comment]
This is mostly fixed now. There are some small number of files remaining lowercase as no ideal / strong preference for them.
