### ISSUE TITLE
`let undefined` in global scope should be an early Syntax error

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#165]
```js
print('not early');
let undefined;
```

* Expected: Syntax error with nothing printed.
* Actual: not early is printed, then Syntax error is thrown.

See [GDI step 5.c+d](http://tc39.github.io/ecma262/#sec-globaldeclarationinstantiation).

**Comment by ljharb** [comment]
presumably `const undefined = 3` in the global scope should do the same?

**Comment by ianwjhalliday** [comment]
I believe this is the let/const shadowing global non-configurable properties issue that we discussed months ago.  I have a fix for this if I'm not mistaken about its correctness, however right now it is throwing a ReferenceError rather than a SyntaxError.  I'll touch it up and send a PR.

**Comment by bterlson** [comment]
Just to confirm, yes const should behave same as let. `var undefined` should not throw an error and `var undefined = 1` should throw in strict mode (assignment to non-writable property).

**Comment by ianwjhalliday** [comment]
I also just noticed that the error is referring to line 1 column 1, which I presume is because the preamble bytecode that performs the check happens to be source mapped to the first line of source.  I can probably fix that up too.  I'll investigate.

**Comment by ianwjhalliday** [comment]
So I tried to do the line mapping but this screws with debugging, making the debugger think that those declarations should be stepped through before the first line of the script.  This is because debugger statement mapping and stack trace statement mapping are one and the same.

Splitting them is non-trivial so I opted to not fix this issue now.
