### ISSUE TITLE
Is there support for collecting JS Code Coverage numbers in ChakraCore?

### ISSUE THREAD

**Issue by still-dreaming-1** [Microsoft/ChakraCore#1794]
Is there anything built into Chakra to help with code coverage? Wouldn't it be more sensible for the runtime to know what ran and what did not than something else?

**Comment by EdMaurer** [comment]
Are you asking about whether ChakraCore can help determine the JS code that was executed in a given set of scripts?

**Comment by still-dreaming-1** [comment]
Yes. I'm wondering anything built in can help determine code coverage, either something that could be used directly or any features that would help someone build a code coverage tool.

**Comment by dilijev** [comment]
@still-dreaming-1 It sounds like you've already ruled this out, but to analyze code coverage in JS code, it would make the most sense to use an analysis library that does not depend on the Engine in which the code is running, for example, http://blanketjs.org/

Semantically, the engine implementations (Chakra, v8, etc.) should be more or less the same for the features they all implement, so knowing what parts of your code are covered semantically should be more than enough. In fact, it is even possible to do this for code which is written in a language which compiles to JS, like TypeScript. See [vscode's code coverage badge](https://github.com/Microsoft/vscode#visual-studio-code---open-source) which links to https://coveralls.io.

**Comment by dilijev** [comment]
Renamed the title to make this question easier to find in the future.

**Comment by still-dreaming-1** [comment]
Blanket.js is no longer maintained according to their github page.

**Comment by dilijev** [comment]
There are certainly other options. A quick search reveals several. A colleague says Istanbul (https://istanbul.js.org/) is the one most people use. Here's a Reddit thread where there's some discussion about testing code coverage for JS. https://www.reddit.com/r/node/comments/2muiay/code_coverage_tools_for_nodejs/

**Comment by still-dreaming-1** [comment]
I don't think Istanbul will work in a REPL and I'm not sure if I can access the code coverage information from the scripts being covered. Anyway, I tried looking into it's capabilities but they are unwilling to answer my questions and their documentation is very confusing.

**Comment by dilijev** [comment]
From our perspective, engine-agnostic tools are the better approach to getting JS code coverage numbers, and it's probably not worth the development effort to enable JS developers to collect engine-specific code coverage information (nor is it really clear to us what benefit that would buy for JS developers). There is probably a tool out there that can get you what you need, it will just take some time to find it and patience to get what you need from it.

So, I'm closing this question as Out of Scope for ChakraCore.

**Comment by still-dreaming-1** [comment]
Coverage provided by the engine would be great if it were part of the javascript spec and all engines started adding it. You guys could be a leader in that space which would encourage them to add it to ECMAScript. Having one engine support this is better than none as seeing the amount of coverage in one gives you a good idea of what it would be in others. So far I have only found that the dart VM can emit code coverage information. I know that is not javascript, but I think dart shows how something can be designed for developer tools.

**Comment by dilijev** [comment]
@bterlson can elaborate, but if we do want to make a trial implementation of such a feature that we plan on adding to the ECMAScript spec, we would go through the proposal and approval process with TC39, as we are members of TC39 and literally help write the standard. :)

**Comment by hashseed** [comment]
FWIW I don't think a debugging feature such as code coverage should be included in the language spec. If we do, it probably makes sense to start out with simple things such as Error.stack.

**Comment by dilijev** [comment]
@hashseed Agreed

**Comment by still-dreaming-1** [comment]
To put this into perspective you are saying an engine specific implementation would be a bad idea because it is engine specific, but your concerns actually run deeper than that. You actually think it would be a bad idea for this to be included in the language spec and therefore required of all engines. Why do you think that? So far the only clue I have been given is that it is considered a debugging feature, so the implication is that any and all debugging features should not be part of the language spec. Since this was not explained the implication goes even further to imply that the very notion of including debugging features into the language spec is so obviously a bad idea it does not need to be explained why. I think the ability to have powerful debugging tools work well should be a part of the language design because the most powerful ones will only be available if it is done that way.

In the case of code coverage, caring about and measuring it is so essential to the process of writing quality code it should be a first class citizen of the language. This could open up the way for people to explore specifying from tests which parts of the code should and should not be covered by a particular block of test code. This is different from what tools currently provide because they don't care which part of the tests caused to code to be covered. I think the most generally helpful use case would be that a single test file could be considered to fail overall if it does not achieve 100% coverage of a specific file. Basically this is measuring a more strict version of code coverage, intentional coverage only, excluding incidental coverage from tests whose purpose was primarily to test some other code.

**Comment by hashseed** [comment]
Setting break points is not part of the language either.

**Comment by still-dreaming-1** [comment]
@hashseed Ok Does different JavaScript engines provide their own debugging implementation or is the ability to set a break point coming from a separate tool that is not part of the language and independent of the particular engine being used?

**Comment by hashseed** [comment]
come again?

**Comment by dilijev** [comment]
I think a dead issue on ChakraCore is not the best place to discuss this. Maybe open an issue on https://github.com/tc39/ecma262 (the ECMAScript spec repo).

From our perspective, this comes down to a spec issue. In an effort to be standards-compliant, when it comes to the engines themselves (not the tooling built around them), language innovation happens in the spec first, then the engines implement the spec.

Since this is not part of the spec at this time, we will not implement it without a proposal and some form of agreement in the ECMAScript spec committee that it is mature enough to warrant trial implementations in the various engines (i.e. AFAIK, Stage 3 in the [Process](https://tc39.github.io/process-document/)). Again, @bterlson can provide more context on this.

If you feel this is definitely a point worth pursuing in the language spec, opening an issue at https://github.com/tc39/ecma262 to discuss it will get visibility from the right people, instead of the handful of people who happen to be watching this (closed) issue. (Note: I, for one, am not on the ECMAScript Committee.)

**Comment by dilijev** [comment]
@hashseed I think his question relates to the level at which breakpoints are supported in the engines. They are not a spec feature, but break points are implemented by tools which use the engines (like the browsers, VS Code, etc.). Is there any standard around how this should be done or is it a tooling issue which is supported by some other standard? (I believe it is the latter -- at least as far as debugging Node-ChakraCore from VS Code is supported by using the same debugging interface as Node-V8 uses.)

**Comment by bterlson** [comment]
If you want to propose a language feature for ECMAScript, the right approach is to follow ECMA262's [contributing.md](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md). Notably, to begin the process you should bring your ideas to es-discuss rather than simply opening an issue.

I'm not clear on what is being proposed here, though. The spec is not in the business of telling implementations what test tools and debugging capabilities it has. Such overreaches often do more harm than good. For example, if there had been a spec, it might have prevented us from doing work on a different debugging paradigm (time-travel debugging). It might also prevent memory-constrained ECMAScript implementations from existing at all. Debugging is an implementation concern that the spec allows for but does not specify in any detail. Enabling code coverage falls under a similar bucket afaict.

That said, I don't think it's unreasonable for engines to help collection of code coverage - js instrumentation techniques are kind of bad IMO (although they do work). If a couple engines start working on capabilities to enable this AND doing so requires something observable from JavaScript land (say, an API or something), then standardization at that point would be warranted.

**Comment by dilijev** [comment]
@still-dreaming-1, I apologize for misinterpreting your question at first as a language spec issue, and then getting muddled in the details of a language change. It's clear now from the discussion here that this doesn't necessarily fall in the realm of the ECMAScript spec and is a suggestion for a feature along the lines of other existing debugging features.

Since we didn't have any plans to support this yet, and we don't yet know what it would look like, I've reopened your issue as a Suggestion that Needs Proposal. When a Proposal is created, it can replace this issue.

Thanks for pursuing your suggestion even though we had closed the issue. Feel free to add any more details you might have to suggest for such a feature. Then maybe in the future we could create a proposal for the design and capabilities of this feature area.

**Comment by still-dreaming-1** [comment]
No problem, these things are complex things to reason about. I think it is more helpful to explain the end result I am hoping to have rather than the details of how I want an engine to expose these capabilities because that helps people to think in terms of the reason why it would be useful.

From JavaScript code, the same code that is my project, I would like to be able to create multiple, independent code coverage collection objects. Here is an example of code I would like to be able to write. As long as the engine provided what was needed to make it possible for someone to write this CodeCoverage class, I would be happy. I'm sure there are many things about this code / design that are ill-conceived, it is more intended to illustrate the capabilities and flexibility I am hoping for. I might have a Mocha test which is testing a CashRegister class / prototype (I will just say class going forward), and at the top of the test file I might create an object like this (sorry, I've mostly been writing PHP lately...):
```
let cashRegisterCodeCoverage = new CodeCoverage()
// allows collection of coverage for that file
cashRegisterCodeCoverage.include('path_to_CashRegister.js')
cashRegisterCodeCoverage.start()
```

Let's say the CashRegister has an addMoney() method. Inside that same test file, just before the code that tests the addMoney() method, I might create another coverage object like this:
```
let addMoneyCoverage = new CodeCoverage()
// allows collection of coverage for the addMoney() method
addMoneyCoverage.include('path_to_CashRegister.js', 'addMoney')
addMoneyCoverage.start()
```
After that there could be code testing the addMoney() method. Just after that code, I might stop collecting coverage for that method and require 100% coverage of the method:
```
addMoneyCoverage.stop()
assert.equals(addMoneyCoverage.coveragePercent, 100, addMoneyCoverage.getMissingLinesTerminalString())
```

At the end of the file I might place this code:
```
cashRegisterCoverage.stop()
assert.equals(cashRegisterCoverage.coveragePercent, 100, cashRegisterCoverage.getMissingLinesTerminalString())
```

Here are the main takeaways when working with such CodeCoverage objects. It should be easy to find out the percentage covered of whatever is being measured by that particular object, so that can be used to enforce a desired percentage of coverage, perhaps even making a unit test fail as a result of not enough coverage. Each object should work independently, potentially tracking the coverage of different things. You should be able to start and stop the collection of coverage for a single object at any place in the code, only coverage occurring after the starting point and before the ending point is tracked by that object. It would also be nice to be able to create JSON reports and HTML reports from / using those objects. It would be nice to be able to create one of those objects from a JSON report. I would want to be able to combine the coverage from multiple objects such that the end result is a new object, perhaps by using a `getCombined()` method.
