### ISSUE TITLE
dotnet-bot seems to test everything that has substring of your request

### ISSUE THREAD

**Issue by MikeHolman** [Microsoft/ChakraCore#1933]
I've found that when saying `test Ubuntu ubuntu_linux_release_static`, both `ubuntu_linux_release_static` and `Ubuntu ubuntu_linux_release` get rerun.

**Comment by dilijev** [comment]
Yes, that's because of the design of triggers which match an entire line of output. One of the triggers it creates is by filling in the regex `.*test.*JOBNAME.*` by replacing `JOBNAME` with the name of the job (in the example above, `ubuntu_linux_release_static`. Since `ubuntu_linux_release` and `ubuntu_linux_release_static` both match `test ubuntu_linux_release_release`, it triggers both of those builds.

This is an artifact of how the jobs are named, and the simplest solution is to change the names of the non-static jobs to include a suffix to disambiguate from static builds.

`ubuntu_linux_release` becomes `ubuntu_linux_release_nonstatic` (unless you can think of a better suffix).

The line to modify is this one:
https://github.com/Microsoft/ChakraCore/blob/master/netci.groovy#L124

/cc @mmitche @jianchun @obastemur @digitalinfinity

**Comment by dilijev** [comment]
Trivia: that's why I changes the trigger for all linux tests from `test linux` to `test linux tests` (despite the redundancy) -- initially any request for an individual linux test was setting off all of the linux tests.

**Comment by obastemur** [comment]
@dilijev Thanks for the useful information. Sent a PR with a potential fix to this; I was going to fix `no-jit` test names anyways. one stone two birds :)

We may discuss further here and finally update that PR to whatever the decision we reach.

my initial proposition follows;

`customTask(i.e no_jit)_shared/static_platform_buildType`

Since the final name comes with `platform` anyways, we may also remove `platform` from the config name too.

**Comment by dilijev** [comment]
Discussing here rather than in a PR comments is a good idea because we might accidentally set off a lot of triggers on the PR while we're discussing triggers.

Since individual test names are copy-paste for triggers in most cases I wasn't worried about being especially terse (more detailed even if redundant is more future proof in the sense that we have less to update).

Work item this will probably generate:

Changes to test names will likely result in us needing to update the links in the build status table in the README as well as in the Wiki (the URLs will change along with the names):

https://github.com/Microsoft/ChakraCore/blob/master/README.md#build-status
https://github.com/Microsoft/ChakraCore/wiki/Build-Status
https://github.com/Microsoft/ChakraCore/wiki/Build-Status-%28release-1.2%29
https://github.com/Microsoft/ChakraCore/wiki/Build-Status-%28release-1.3%29

**Comment by obastemur** [comment]
> Changes to test names will likely result in us needing to update the links in the build status table in the README as well as in the Wiki (the URLs will change along with the names):

@dilijev good point. Will update those on final PR.

This item has not much priority and I guess we would not prefer changing the test names very often.
I will give this discussion couple of days more to see if any other opinion will show up.

**Comment by dilijev** [comment]
Some more thoughts:

Remember to check in the change to the `netci.groovy` to any branch which is affected (if xplat test changes only, `release/1.3` is the branch; if it affects Windows, then target `release/1.2`).

My thoughts on changing things: only change things if there's a benefit (this issue brought up a good one), and leave along anything you can. That said, as long as we're making the update which affects those our CI and those wiki entries, it's best to make all the changes you're planning all at once (to minimize the disruption).

Also just remembered, we'd need to update the test names in this Wiki page as well:
https://github.com/Microsoft/ChakraCore/wiki/Jenkins-Build-Triggers

**Comment by mmitche** [comment]
It might be worth changing the regex to have a word boundary at the end of the string.  That can be changed at the utility level.

FYI, I think your triggers are available by commenting @dotnet-bot help

**Comment by dilijev** [comment]
@mmitche That's a good idea about adding the word boundary (`\b`). That would block matching beyond the end of a particular trigger name.

**Comment by dilijev** [comment]
@mmitche to clarify, are you saying you are going to add that to the Utilities script, or should we add it to our regexes?

**Comment by mmitche** [comment]
I can add it to the overall regexes.

**Comment by dilijev** [comment]
Since this will be updated on the utility side by @mmitche, I think there's no more action to take here. Closing this issue.

**Comment by dilijev** [comment]
Oh this issue will be closed automatically when #1962 is merged.
