### ISSUE TITLE
WASM - int32 trunc bug

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#1957]
Wrong behavior in jitted code for i32.trunc_u/f32 and i32.trunc_u/f64
See test/WasmSpec/conversions.wast lines 78-84 and 117-122
test/WasmSpec/float_exprs.wast lines 695-696
test/WasmSpec/float_exprs.wast lines 704-709

**Comment by Krovatkin** [comment]
@MikeHolman 

Identified 3 separate issues in those tests so far. Two of which we are working on fixing. 

* (NEW) for unsigned truncations, we need to convert to double first before doing subtraction, since 23 bits of precision is not enough to convert relatively small numbers. For example, `1 - MIN_INT` after conversion gives us `MIN_INT`, we add `0x80000000` and get `0` instead of `1`
* If we try to convert 0.7 using our sequence after subtracting 2147483648 we end up with -2147483647.3, -2147483647.3 is truncated to -2147483647. We add 2147483648 back and we got 1 
* if we feed it values like -0.4 (unsigned) or -2147483648.8 (signed). This equality comparison we are using, (double) MIN_VALUE == initialValue, isn't strong enough to capture MIN_VALUE.xxx (xxx is a fractional part) cases.

FYI: @Cellule

**Comment by MikeHolman** [comment]
From all this it sounds like the sequence I initially suggested was ill advised. Maybe we need to do the range check?

**Comment by Krovatkin** [comment]
@MikeHolman yes working on reinstating the older version of truncation sequence and enabling failing tests

**Comment by maksqwe** [comment]
@Krovatkin 
By the way, can be that this typo is affected to truncation bug?

\lib\backend\linearscan.cpp 3400
```C++
StackSym * oldSym = sym;
sym = StackSym::New(TyVar, this->func);
sym->m_isConst = true;
sym->m_isIntConst = oldSym->m_isIntConst;
sym->m_isTaggableIntConst = sym->m_isTaggableIntConst; // <<<<< oldSym->isTaggableIntConst ?
```

**Comment by Krovatkin** [comment]
Hi Maks!
Thanks for reporting this! AFAIK, we seem to have fixed all the bugs in our 32-bit truncation logic and those issues fortunately had nothing to do with a register allocator 🎱 . 

`sym->m_isTaggableIntConst = sym->m_isTaggableIntConst;` does look like a typo to me. Did you come across any more typos like this one? Also, how did you hit this one; did you run a lint on ChakraCore codebase? 

I think that you should open a PR and submit a fix for this one. Additionally, if you got a few of these, we might want to consider opening an issue to provide some more info for the PR. Let's double check with Chakra core team ( @MikeHolman  @Cellule ) to make sure that this course of action is indeed the right one to take.

FYI: @obastemur Running a lint could be another cool idea for a side project, what do you think? 😃

**Comment by Krovatkin** [comment]
@Cellule Do you think we can close this one? Or are there any more spec tests I haven't enabled?
