### ISSUE TITLE
JsRunScriptUtf8 missing

### ISSUE THREAD

**Issue by d4nnyk** [Microsoft/ChakraCore#2006]
JsRunScriptUtf8 is missing from the Master branch, which is used in all of the samples for Linux. I guess previously there was a Linux branch and currently it's not there.

Could you please add this? or change the example program to use current exposed API?

**Comment by liminzhu** [comment]
// fyi @obastemur 

Hi @d4nnyk. The utf8 APIs were experimental, and we've replaced them with something we believe is better for cross-platform apps https://github.com/Microsoft/ChakraCore/pull/1830. Do you have a dependency on the old APIs? In a nutshell, the way to use new string APIs is 1) converting native strings (`const char`/`uint8_t`/`uint16_t`) to `JsValueRef` (a JavaScript var in JSRT), 2) then call new APIs that consumes JsValueRef instead of native string. For example, `JsRun` (corresponding to windows-only `JsRunScript` and obsolete `JsRunScriptUtf8`).

I'll update the docs/samples shortly.

**Comment by d4nnyk** [comment]
Thanks! I had to go through some of the "test" code to find "JsRun" and I have ported the old code.
It will be great if you can change the sample code :)

**Comment by obastemur** [comment]
We track this issue at https://github.com/Microsoft/Chakra-Samples/issues/47 and the PR for new samples https://github.com/Microsoft/Chakra-Samples/pull/48

**Comment by obastemur** [comment]
@d4nnyk Thanks for reporting anyways 👍
