### ISSUE TITLE
history.pushState updates page path to /undefined when optional URL is undefined

### ISSUE THREAD

**Issue by mkhatib** [Microsoft/ChakraCore#2479]
[Reproduce here](https://output.jsbin.com/fuqukov/quiet).

Steps to reproduce:
* Call `history.pushState(anything, anything, undefined)`
* Notice the page path changes to `/undefined`

### Expected Behavior
The third URL parameter is optional and the current path should be used when URL is not passed. 

### Versions
Edge 25.10586.672.0
EdgeHTML 13.10586

**Comment by liminzhu** [comment]
Hi @mkhatib , thanks for reporting the issue! I believe this is a browser API issue rather than a JavaScript issue so filing the bug on Edge issue tracker through [these steps](https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues) would be the better action. Feel free to re-open the issue if it's determined as a Chakra issue. Thanks!

**Comment by mkhatib** [comment]
Thanks @liminzhu - filed: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10825440/
