### ISSUE TITLE
Unicode character breaks ES6 class toString() output

### ISSUE THREAD

**Issue by dballesteros7** [Microsoft/ChakraCore#2656]
When analyzing a script, the toString output of a class declaration is wrong if preceded by a unicode character (even in a comment).

Example:
```js
// Evil ndash
// –
console.log(class {});
```

Expected output: `class {}`
Actual output: `g(class`

Browser version: 38.14393.0.0

**Comment by dilijev** [comment]
Props for using one of my favorite typographical characters in your repro. :)

**Comment by dilijev** [comment]
My theory: byte counts for index into the source got screwed up here. The file is encoded in UTF-8 and en-dash is encoded as three bytes instead of one. The output is displaying the source starting two characters before the actual beginning of the source, with the correct length (missing only the `{}` -- there's a trailing space (`\x20`) in the output).

**Comment by dilijev** [comment]
An extra test case to confirm that behavior:

```js
// Evil ndash
// –– (two en-dashes)
console.log(class {});
```

Output: `log(clas`

**Comment by dilijev** [comment]
@pleath as this might be related to the parser.

**Comment by pleath** [comment]
@boingoing

**Comment by boingoing** [comment]
Looks like the parse node for the class constructor function is setting the byte offsets into the source to values calculated for the character count of the class. This could be our bug in ParseClassDecl:

```c++
    if (buildAST)
    {
        pnodeConstructor->sxFnc.cbMin = pnodeClass->ichMin;
        pnodeConstructor->sxFnc.cbLim = pnodeClass->ichLim;
        pnodeConstructor->ichMin = pnodeClass->ichMin;
        pnodeConstructor->ichLim = pnodeClass->ichLim;
```

I'll test it out.

**Comment by dilijev** [comment]
Would be good to make sure the length is also based on bytes and not character count.

I wrote a quick test and the results were not quite what I expected:

```
console.log(class { /* – */ }); // using en dash U+2013 inside a comment inside the class
```

Output: 
```
class { /* ? */??
```

Those are actual question marks (i.e. `0x3F`) but I think that's because we convert anything that is considered "garbage" to ? before printing.

**Comment by dilijev** [comment]
Interestingly, using a 4-byte encoded CJK character (I tried 𢭃 U+22b43), still only exhibits a 2-byte difference in expected versus actual behavior (the same as the effect of the en-dash 3-byte encoded character).

I think this is because it's a surrogate pair in UTF-16 which has 2 code units (whereas the en-dash only had 1 code unit), and I think code unit counts rather than character (codepoint) counts are probably what are considered in our source since we decode sources to char16 strings. The difference in code units versus bytes is still 2 in this case.

Also reinforced by the encoding in a similar test where we put that character into the class itself in the same position as before:

```js
console.log(class { /* 𢭃 */ }); // 4 byte Chinese character U+22b43
```

Output:

```
class { /* ?? */??
```

The other case to check is a 2-byte UTF-8 code point.

```js
console.log(class { /* ā */ }); // LATIN SMALL LETTER A WITH MACRON U+0100 (UTF-8 bytes: c4 81)
```

```
class { /* ? */ ?
```

Side note: By definition it is not possible to have a case of UTF-16 (2 code units) with UTF-8 encoding of 3 bytes. See [U+FFFF](http://www.fileformat.info/info/unicode/char/ffff/index.htm) which is a single code unit in UTF-16 and 3 bytes in UTF-8.

Furthermore it is not legal in the current definitions of these encodings to have a character which is larger than 2 code units in UTF-16 nor one which is larger than 4 bytes in UTF-8. Largest code point supported by both encodings is U+10FFFF which is a surrogate pair and 4 bytes respectively. Theoretical max encoding by the UTF-8 scheme is higher (36 bit codepoints) so it would be worth testing what happens with that type of input, as a separate exercise from this issue.

**Comment by dilijev** [comment]
This is now fixed. /cc @LouisLaf
