### ISSUE TITLE
IE11 broken when using class properties only with the latest/default document mode "Edge" (as named in WinBlue)

### ISSUE THREAD

**Issue by jayson30100** [Microsoft/ChakraCore#2706]
This issue is broken only with IE11 EDGE document mode, whereas rest of the documents mode <= 10 works exactly fine.

It’s disturbing as say the web page should be in the latest standards document mode like EDGE and its breaking in that document mode itself. Down-level doc modes were its not recommended works exactly fine, seems to be a regression with IE11.

Calling Function.name on Classes fails if it is called in the order of base class->child. If called in the child->base class order, it succeeds.

Simplified Repro, launch below URL and open F12 console section to observe the output.
https://jsfiddle.net/2so35uf3/1/ 

Actual:
console.log(Animal.name); // returns Animal in IE11 with EDGE doc mode
console.log(Snake.name); // returns Animal in IE11 with EDGE doc mode
console.log(Horse.name); // returns Animal in IE11 with EDGE doc mode
Actual Output:
Animal 
Animal 
Animal 

Expected Output:
Animal
Snake
Horse

Based on walking the code I don't think that is the problem. This appears to be a flaw in the IE11 JIT.

I'm looking for any advice on how to handle this besides (1) don't use IE11 or (2) don't use Function.name.

Sample:

// Typescript
class Animal {    
    hello(person: string) {
        console.log(`Hello ${person}`);
    }
}

class Snake extends Animal {    
    hello(person: string) {
        console.log("I'm a snake");
        super.hello(person);
    }
}

class Horse extends Animal {
    get wow(): string {
        return "wow";
    }
}

console.log(Animal.name);
console.log(Snake.name);
console.log(Horse.name);

tsc -t ES2015 with produces this JavaScript:

class Animal {
    hello(person) {
        console.log(`Hello ${person}`);
    }
}
class Snake extends Animal {
    hello(person) {
        console.log("I'm a snake");
        super.hello(person);
    }
}
class Horse extends Animal {
    get wow() {
        return "wow";
    }
}
console.log(Animal.name);
console.log(Snake.name);
console.log(Horse.name);

This issue is also reported in:
http://stackoverflow.com/questions/42470179/ie11-javascript-behavior-with-polyfilled-function-name
https://social.technet.microsoft.com/Forums/en-US/761d1195-bb1d-4129-a39d-420c304e5b15/ie11-jit-broken-when-using-class-properties?forum=ieitprocurrentver

We know that MS is not working on IE11 fixes considering EDGE, but this is breaking the latest EDGE doc mode itself not the older doc modes in IE11 and we can't live with it like that forever. It would have been okay to not fix if the issue was with the older doc modes like IE10/9, but here the issue is with the latest IE11 EDGE doc mode itself.

Hope this is fixed sooner. Thanks.

**Comment by dilijev** [comment]
Presumably you're depending on Edge doc mode in IE11 because you're not running Windows 10?

I'm not very familiar with IE doc modes; however, I believe the Edge doc mode is considered a compatibility mode of IE11 and is not the same code as runs in Edge for document parsing and rendering (i.e. EdgeHtml). AFAIK, the Javascript engine used in that mode is still the legacy JScript engine used in all the rest of the document modes in IE11, and not Chakra (which doesn't ship to previous versions of Windows and is not used by IE11). We don't support changes to the legacy JScript engine except security fixes.

However, this appears to be a purely JS problem (not related to the rendering engine), and the regression from an older to a newer mode is concerning.

Marking as External since this affects a non-ChakraCore product.

**Comment by dilijev** [comment]
Tagging as Won't Fix because it probably won't be fixed, unfortunately. Will leave this issue open for a little bit in case there are more comments.

**Comment by dilijev** [comment]
Updated title to clarify.

**Comment by MikeHolman** [comment]
I think in ie11 our support for classes wasn't great. Honestly, I'm surprised it's there at all.

If this is impacting a lot of people it might be worth looking into fixing for next version of Windows (even if we don't service the fix).

But it will likely be that we can only workaround this, which in your case may mean to transpile to older version

**Comment by jayson30100** [comment]
So, Microsoft asking us to move back to the old IE10 doc mode? Not fair :( It's Microsoft who first recommended developers to go with the latest default IE11 doc mode so we invested a lot and revamped our exiting web applications, now should we again move back to older IE10 doc mode?

I can't agree more with your comment for "Won't Fix". This is really letting us down and feel sorry for creating this request.

Is there a way can you consider in fixing this latest IE11 doc mode?

**Comment by MikeHolman** [comment]
I was a bit confused when you said it was a bug in the JIT (which to me has a different meaning). But now I think I understand your problem.

The spec for classes changed since IE11 shipped, so this would require implementing the new spec for classes into IE. This would not be a bug fix, but would be a feature implementation. We are not currently implementing new JS language features in IE, so this is beyond the scope of what we can do.

All of our implementation effort is going towards the Edge browser, so is there something that is blocking you from using Edge?

**Comment by dilijev** [comment]
@jayson30100 even with @MikeHolman's comment in mind, I think we can do even better for you at this time -- and you won’t even need to wait for us to fix anything (since no fix is required for this to work for you):
 
It looks like you’re using TypeScript to develop your app, and you’re targeting ES 2015. Since IE11 was released in 2013, it didn’t fully support ES 2015. However, without even changing your TypeScript sources you can get a version of your app working in IE11 by compiling your TypeScript to target ES5 (which was published in 2009) instead.

**Comment by cinPlicity** [comment]
Its not fixed because main branch cant access the required tools or access to download any supporting links. Hello Main branch here, I been running int this error for the past 2yrs trying to gain access to main console (my buisness device samsung edge note4) Im new at learning how all this"codebuilding" works. Majority of the time I end up pushing random buttons and in doing this I managed to gain a glimps following my own bread crumbs, it brought me here to Git hub. Apperently this development on my device started here last year when my device was compramised. 

Main Thread

**Comment by dilijev** [comment]
@cinPlicity we removed your comment because it appeared to be gibberish and we've seen other strange posts in your account history. We believe your account may have been compromised and a bot is using it to post nonsense around GitHub. Please contact us if you believe this action was not correct.

**Comment by dilijev** [comment]
Closing. This issue is External to ChakraCore. Additionally, a suitable workaround has been presented for affected products.
