### ISSUE TITLE
[Question] Can JsContextRefs and JsPropertyIdRefs be safely stored in an JsArray??

### ISSUE THREAD

**Issue by markt-** [Microsoft/ChakraCore#2900]
What I am hoping to do is add assorted JsRefs that I want to be keep around for a while into an array that I have done a JsAddRef on, with the theory that since the array will not be garbage collected, none of the JsRef's stored in it will get garbage collected, but then when I want to release them all, I just need to do a JsRelease on the array, and I don't have to set up a separate tracking system for those things. and do a JsAddRef/JsRelaseon on each of them individually. Since ContextRefs and JsPropertyIdRefs are not JsValueRefs however (although they typedef to the same type),  I am not sure if it is possible to safely store them in an array.

**Comment by jianchun** [comment]
You are correct except that you can't do that with `JsContextRef/JsPropertyIdRef` because you can't store them in a JavaScript Array since they are not JavaScript Vars. The same approach is used in node-ChakraCore, e.g. [HandleScope::AddLocal](https://github.com/nodejs/node-chakracore/blob/xplat/deps/chakrashim/src/v8handlescope.cc#L57).

**Comment by liminzhu** [comment]
Close as this question seems to be answered already. Feel free to re-open otherwise.
