### ISSUE TITLE
Assertion fails when dump constant table.

### ISSUE THREAD

**Issue by penhoi** [Microsoft/ChakraCore#3069]
I used the following code to dump a constant table just right after a Func instance is created, but got an assertion failure `Assert(varConst != nullptr);` when feeding CH with bigfib.cpp.js. 

```
 --- a/lib/Backend/Func.cpp
+++ b/lib/Backend/Func.cpp

@@ -295,6 +295,7 @@ Func::Codegen(JitArenaAllocator *alloc, JITTimeWorkItem * workItem,
         {
             func.TryCodegen();
             rejit = false;
+            Js::FunctionBody *fbody = (Js::FunctionBody*)(func.GetJITFunctionBody()->GetAddr());
+            Js::ByteCodeDumper::DumpConstantTable(fbody);
         }
```

How can i fix this problem? Thanks!

**Comment by dilijev** [comment]
Clarifying: it looks like you modified ChakraCore source code (diff above), built `ch`, and ran `ch bigfib.cpp.js`, and then encountered this assertion failure.

Which commit did you base your change on?

**Comment by MikeHolman** [comment]
I'm assuming that is asm.js function? In that case, the issue is that DumpConstantTable only supports dumping normal js functions, and doesn't support dumping constant table for asm.js.

Unfortunately it doesn't look like there is any API right now that will dump asm.js constant tables at JIT time `AsmJsByteCodeDumper::DumpConstants` would work only during bytecode gen. If you don't care about asm.js functions, you can wrap that call in an `if(!fbody->GetIsAsmjsMode())` and it will work for everything else.

**Comment by penhoi** [comment]
@dilijev 
My modification is based on branch "release/2.0", and the latest commit is as following:

commit 039006b8f4b62eb9d4812241377cf6a38e3c073e
Merge: 34c3ab1 9f7430d
Author: Oguz Bastemur <ogbastem@microsoft.com>
Date:   Sun May 21 04:30:40 2017 -0700

@MikeHolman 
Yes, it is asm.js function because both fields "m_isAsmjsMode" and "m_isAsmJsFunction" are true.
It works when I use the statement "if(!fbody->GetIsAsmjsMode())" before dumping constants.

Thanks all :)
