### ISSUE TITLE
Unresolved P/Invoke method 'JsCreateExternalArrayBuffer!Chakra.dll'

### ISSUE THREAD

**Issue by irbull** [Microsoft/ChakraCore#3216]
We have been successfully using Chakra in our application for over 2 years (before it was even open sourced). It is a great JS engine. Today we released some work via the Windows store, and apps that work fine on our workstations, fail at runtime with the following error:

```
System.TypeLoadException: Unresolved P/Invoke method 'JsCreateExternalArrayBuffer!Chakra.dll' in assembly 'EclipseSource.Tabris.JavaScript, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
```

It appears this particular API is not available. Is that expected? Is `JsCreateExternalArrayBuffer` considered *public*, and do you know what version of Chakra core this API was introduced in?

This might not be the best forum for asking this question, but I can't seem to find another suitable place. Also, this may also raise a _meta issue_, how do developers know what version of Chakra ships with Windows UWP.

**Comment by liminzhu** [comment]
Hey @irbull . I'm assuming you're using Chakra since ChakraCore won't pass the //WACK tool for store apps. I think `JsCreateExternalArrayBuffer` is added to the store white-list since Anniversary update last August-ish. What version of Windows are you using?

> how do developers know what version of Chakra ships with Windows UWP.

Chakra as well as Windows 10 are evergreen. As Chakra comes with Window, you can think of the Windows update version as Chakra version.
