### ISSUE TITLE
releationship between chakracore and chakra.dll?

### ISSUE THREAD

**Issue by zenhumany** [Microsoft/ChakraCore#3260]
what's the relationship between chakracore and edge js engine chakra?Can I guess which version of chakracore is used by chakra engine based on the version of chakra.dll?

**Comment by bterlson** [comment]
The wiki has a pretty good answer about the relationship: https://github.com/Microsoft/ChakraCore/wiki/Architecture-Overview. Version numbers I'm not sure about, perhaps someone else can comment.

**Comment by liminzhu** [comment]
> Can I guess which version of chakracore is used by chakra engine based on the version of chakra.dll?

Hey @zenhumany ! There is no separate versioning for Chakra.dll besides Windows version since it's a system component. There's also no definitive 1-1 mapping between a major Windows update and a ChakraCore release, though so far we usually make a ChakraCore release that is pretty close to what we ship in Chakra in a Windows update.

**Comment by zenhumany** [comment]
@liminzhu ,i got it,thanks very much for your answer!
