### ISSUE TITLE
Remove Simd.js code from ChakraCore - Part 1 (ifdef out)

### ISSUE THREAD

**Issue by agarwal-sandeep** [Microsoft/ChakraCore#3273]
simd.js is no longer planned for in its current form. V8 has already removed it and ChakraCore should also remove it.

Since some code of simd.js can be reused for WASM simd. In first part of change try to ifdef out simd.js specific code to not build and then in second part remove code which is not needed for WASM simd.

**Comment by agarwal-sandeep** [comment]
@Krovatkin I have ifdef'd out most of library and runtime code abd32f52.

Are the following used in WASM simd?

[liveSimd128*Syms](https://github.com/Microsoft/ChakraCore/blob/master/lib/Backend/GlobOptBlockData.h#L161])
[simd128*SymsOnEntry](https://github.com/Microsoft/ChakraCore/blob/master/lib/Backend/FlowGraph.h#L572)
[likelySimd128*SymsUsedBeforeDefined](https://github.com/Microsoft/ChakraCore/blob/master/lib/Backend/FlowGraph.h#L579)
[forceSimd*F4SymsOnEntry](https://github.com/Microsoft/ChakraCore/blob/master/lib/Backend/FlowGraph.h#L585)
[argOutSimd*Syms](https://github.com/Microsoft/ChakraCore/blob/master/lib/Backend/BailOut.h#L287)
[liveSimd128*Syms](https://github.com/Microsoft/ChakraCore/blob/master/lib/Backend/BailOut.h#L105)
[Simd*](https://github.com/Microsoft/ChakraCore/blob/master/lib/Backend/IRTypeList.h#L25)
[Simd*](https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/ByteCode/OpCodesSimd.h#L63)
[Simd*](https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Language/AsmJsBuiltInNames.h#L93)

**Comment by Krovatkin** [comment]
@agarwal-sandeep The last 3 are **definitely** used. 
It is a little bit less clear-cut w/ the remaining ones. While there's no type specialization in asm.js/wasm, CSE seems to rely on liveXXXSyms bit vectors (see `GlobOpt::NewIntConstantValue`) and if we are planning on enabling CSE & const folding for SIMD types, we *might* need these vectors. Also, the bailout infrastructure uses liveSimd128XXX vectors, so if we enable bailouts for asm.js/wasm, again, we *might* need these vectors.

I was wondering if it makes sense to hold off for a little bit on ripping out/if 0 simd.js code until the spec stabilizes and Chakra team decides on which optimizations it would like to enable for WASM? Otherwise, there's a chance we might need to put this code back in later on :-) 

Can we get @LouisLaf 's opinion on the matter?

**Comment by agarwal-sandeep** [comment]
Thanks @Krovatkin. In this part of the change I am not removing any code just putting everything under #ifdef ENABLE_SIMDJS which by default is not defined. We have another issue #3274 opened to remove all simdjs related code which is not used for WASM simd after we have it ready. For now I will go ahead and ifdef out except the last 3.

**Comment by agarwal-sandeep** [comment]
#3296 got merged
