### ISSUE TITLE
[Question] JsConstructObject, examples of use?

### ISSUE THREAD

**Issue by marktjsonar** [Microsoft/ChakraCore#3293]
I can't find any examples of how to use JsConstructObject in the ChakraSamples repo.  In particular, I'm curious what the arguments array needs to look like.... can I pass any object as the first argument, or does it need to be a newly created one that the constructor can fill by referring to 'this'?

**Comment by liminzhu** [comment]
Hey @markt- , Yes arguments[0] needs to be thisArg and I updated the API [reference](https://github.com/Microsoft/ChakraCore/wiki/JsConstructObject). Obviously not the best example, but here's how we call it in our [unittest](https://github.com/Microsoft/ChakraCore/blob/1db78494a58073be848ab91de6eb073cbff055c3/bin/NativeTests/JsRTApiTest.cpp#L673).

**Comment by markt-** [comment]
I'm sorry, but I am finding your answer to be just a bit ambiguous.   Do you mean that it should be 'this' as it would be within the scope of the constructor (that is, a newly created object with JsCreateObject or JsCreateObjectExternal), or should it refer to 'this' in the scope of the calling function (that is, a reference to whatever object instance contained the constructor function being called, which could easily be the global object in the case of callling a globally visible constructor)

**Comment by liminzhu** [comment]
Sorry for not being clear. It would be `this` for the scope where the constructor is called.

**Comment by markt-** [comment]
Okay, thanks.  That makes sense, but I wasn't entirely sure, and I didn't want to be passing my current 'this' in if the construct method was going to modify it by putting content into its own 'this'.

**Comment by gh-andre** [comment]
I don't think first argument works as described above (or at all). No matter what I pass as the first argument into `JsConstructObject`, in the constructor function the first argument is always a different object. Looking at the code, I don't see how it can possibly work as described. 

1. `JsConstructObject` makes this call, hardcoding `overridingNewTarget` to `nullptr`:
```
Js::JavascriptFunction::CallAsConstructor(jsFunction, /* overridingNewTarget = */nullptr, 
    jsArgs, scriptContext);
```

2. In `CallAsConstructor` this code always allocates a new `resultObject` because `overridingNewTarget` is `nullptr`:
```
        if (overridingNewTarget != nullptr && args.Info.Count > 0)
        {
            resultObject = args.Values[0];
        }
        else
        {
            resultObject = JavascriptOperators::NewScObjectNoCtor(v, scriptContext);
        }
```

3. `newArgs` is populated from `newValues`, which is set like this:
```
        if (!thisAlreadySpecified)
        {
            newValues[0] = resultObject;
        }
```

So, no matter what I do, I always get a new object in my constructor. Is this a new direction or just a bug in the current code (looking at the code that is about two weeks old from the date of this comment)?

As a side note, I wish Chakra would be documented even 1/10th as good as v8 in-code comments. Current Chakra documentation is just stating what the function name says it does anyway, like `JsConstructObject` says "Invokes a function as a constructor." Not very helpful.

**Comment by liminzhu** [comment]
It seems like you're right. @akroshg do you know who was the original author of `JsConstructObject`? We might want to look into the current behavior.

> As a side note, I wish Chakra would be documented even 1/10th as good as v8 in-code comments. Current Chakra documentation is just stating what the function name says it does anyway, like JsConstructObject says "Invokes a function as a constructor." Not very helpful.

Is there anything that you think would be helpful for us to add in the documentation? Many of those APIs are somewhat self-explanatory so if there's anything that may confuse you (like this API), I'd love to fix it.

**Comment by akroshg** [comment]
@liminzhu  I am not aware of who is author. Perhaps you can look at the usage at https://github.com/Microsoft/ChakraCore/blob/master/bin/NativeTests/JsRTApiTest.cpp#L748

**Comment by gh-andre** [comment]
@liminzhu Thank you for confirming. Much appreciated. Took me a bit to figure out why I wasn't getting my object in the constructor function - I thought at first I was calling something incorrectly.

> Is there anything that you think would be helpful for us to add in the documentation?

Here's a couple of points off the top of my head:

Anyone who worked with the v8 will struggle to implement properties in C++. It took some digging to find some discussion where you advise to use the `Proxy` object. That bit would be useful in the main API page because most JavaScript bindings I saw in my experience use properties. That would save people time because it is not an obvious approach that one would have to use a JavaScript object for this to work. 

Some additional narrative would also be useful, such as if one makes use of the `Proxy` object, then they cannot implement functions by creating a function object, but rather would have to call `bind` and return the resulting function with the target object, which is also not something obvious.

I struggled to figure out how to report errors. The v8 docs spell out exactly how to use script origins and error objects, so it's easy to report the error with a line and character precision. Chakra seems to rely on the built in error object and many of its properties, other than error message, are non standard. I had to dig through the code to figure out that there's a call stack property and I didn't find a way to report line number and associate it with the script origin. 

Speaking of the script origin, I still haven't figured out how the source context integer can be used in error reporting. That would be a nice addition to the docs. 

The v8 has special syntax (escape handles) to allow local handles carried out of a local scope of a function. Chakra doesn't describe anything along these lines and doesn't describe how `JsValueRef` are cleared out and how one preserves those that are in return values.

**Comment by liminzhu** [comment]
Really appreciate the feedback!

> Anyone who worked with the v8 will struggle to implement properties in C++. It took some digging to find some discussion where you advise to use the Proxy object. That bit would be useful in the main API page because most JavaScript bindings I saw in my experience use properties. That would save people time because it is not an obvious approach that one would have to use a JavaScript object for this to work. Some additional narrative would also be useful, such as if one makes use of the Proxy object, then they cannot implement functions by creating a function object, but rather would have to call bind and return the resulting function with the target object, which is also not something obvious.

Not sure what you mean by implement `properties in C++`. If you mean attach properties to objects natively, [this doc] shows a short sample of how to attach the `log` function on `console` object.

> I struggled to figure out how to report errors. The v8 docs spell out exactly how to use script origins and error objects, so it's easy to report the error with a line and character precision. Chakra seems to rely on the built in error object and many of its properties, other than error message, are non standard. I had to dig through the code to figure out that there's a call stack property and I didn't find a way to report line number and associate it with the script origin.

[This](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview#exception-handling) is perhaps what you look for. This is also some code in the [sample](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/JSRT%20Hosting%20Samples/C%2B%2B/ChakraCoreHost/ChakraCoreHost.cpp#L300), which we could probably include in the doc itself.

> Speaking of the script origin, I still haven't figured out how the source context integer can be used in error reporting. That would be a nice addition to the docs.

It's basically an id for your script. You can put whatever you think makes sense there. It is used in case such as [JsSerializedScriptUnloadCallback](https://github.com/Microsoft/ChakraCore/blob/master/lib/Jsrt/ChakraCommon.h#L688) as the engine gives you the id back to tell you which script you can safely free now. We should document this better as I can understand how this is confusing.

> The v8 has special syntax (escape handles) to allow local handles carried out of a local scope of a function. Chakra doesn't describe anything along these lines and doesn't describe how JsValueRef are cleared out and how one preserves those that are in return values.

[This](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-%28JSRT%29-Overview#memory-management) is perhaps what you look for.

**Comment by gh-andre** [comment]
> Not sure what you mean by implement properties in C++

I mean a concept similar to v8 accessors - you can just bind a callback to a JS property in C++ without using `Proxy` objects. From the object setup perspective it is more straightforward. The `Proxy` object makes it similar to v8 interceptors, except that you would use the latter only if you create flexible bindings where you don't know property names beforehand, like an object representing an arbitrary database table with properties for names. 

> This is perhaps what you look for. (error reporting)

I did read all these docs and a lot of Chakra functionality relies on JavaScript objects, like the `Proxy` object and additional undocumented JS properties, like the `stack` property of the exception object. Message alone is not enough for troubleshooting. I'm sure there are some undocumented properties that allow you to use debuggers and identify the exact line in the script and may be even the column. Knowing this would be useful. 

> It's basically an id for your script

I see. That's useful. Thanks for pointing it out. 

> This is perhaps what you look for. (returned handles)

I didn't describe it well. May be this concept doesn't exist in ChakraCore. The v8 has a concept of a handle scope (`v8::HandleScope`), which destroys local handles when it is destroyed, so if one wants to return a local handle from a function, they would have to identify it in a special way. I suppose in ChakraCore there is no concept of a handle scope, so it just keeps track of all handles without explicit references in C++ callbacks.

**Comment by gh-andre** [comment]
@rhuanjl 

> The CC function JsDefineProperty basically behaves like the JS function 

Good to know. Thank you for mentioning. I managed to implement all properties via the `get` and `set` methods of a `Proxy`, but this did require extra work around member function calls because the target object and its member functions had to be wrapped in a `bind` call. Using `defineProperty` would be more straightforward indeed. I wish it was mentioned in the docs. I picked up the `Proxy` idea from one of the issue in this project, as it didn't even occur to me to look for some functionality in the JavaScript itself (i.e. as opposed to using just the C interface to bind things).

> On error reporting have you looked at the method JsGetAndCLearExceptionWithMetadata? 

I was using `JsGetAndClearException`, which doesn't mention that. Missed that function. Thanks for pointing out.

**Comment by liminzhu** [comment]
@gh-andre I think I misunderstood your initial point. Indeed we don't have a interceptor API to bind callbacks on properties natively, but as you already know you can achieve this in JS by using Proxy or getters/setters, which in turn can be added through JsDefineProperty natively as pointed out by @rhuanjl . I think this is an interesting enough scenario to be covered by docs so I added a note [here](https://github.com/Microsoft/ChakraCore-wiki/issues/5#issue-170031584) and will try to find some time to cover that. Ofc we'll take PR if someone wants to do that as well 😄.  

Thanks for pointing out JsGetAndClearExceptionWithMetadata @rhuanjl. I just added a short [note](https://github.com/Microsoft/ChakraCore/wiki/JavaScript-Runtime-(JSRT)-Overview/_compare/ae83f37b33e8cbf5f00c04e8562bad9048d7e5ef) in the docs as well.
