### ISSUE TITLE
Module syntax errors not showing properly

### ISSUE THREAD

**Issue by suwc** [microsoft/ChakraCore#3357]
```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <script type="module">
    import; // expected: syntax error, actual: Exception thrown and not caught
    console.log(test);
    </script>
</body>
</html>
```

```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <script type="module">
    import test from "./test.js"; // expected: syntax error, actual: silent failure
    console.log(test);
    </script>
</body>
</html>
```
```javascript
// test.js
var a = 0;
export { a as default };
import; // line with syntax error
```

**Comment by vinay72** [comment]
I would like to contribute by sending a Pull Request.

**Comment by fatcerberus** [comment]
At a glance this seems like an Edge bug - that is to say ChakraCore *does* produce a syntax error for this case but the module loader swallows it.  I know I ran into similar issues with miniSphere when I was first integrating CC and it turned out I had just wired up the ES module machinery improperly.  There could be a similar bug in Edge's module loader.

**Comment by dilijev** [comment]
As @vinay72 indicated in #5713, this repro case might be improved by changing `import test from "./test.js";` to `import test from "./test";`

**Comment by rhuanjl** [comment]
Module errors for this kind of case work correctly in master (and 1.11) hence closing.
