### ISSUE TITLE
Intl.js: when the outer function of Intl.js is called (Intl lazy-init), it appears in the debugger dump

### ISSUE THREAD

**Issue by atulkatti** [Microsoft/ChakraCore#3438]
It seems an internal anonymous function call during the constructor's execution is being shown in the debugger output.

Run the following with "ch -Intl -debugLaunch"
```js
var options = { ca: "gregory", hour12: true, timeZone:"UTC" }; 
var dateFormat1 = new Intl.DateTimeFormat("en-US", options);    /**bp:resume('step_over');locals();**/
WScript.Echo("");
```
**Actual output:** 
    "functionCallsReturn": {
          "[Anonymous function returned]": "undefined undefined",
          "[Intl.DateTimeFormat returned]": "Object {...}"
**Expected output:**
    "functionCallsReturn": {
          "[Intl.DateTimeFormat returned]": "Object {...}"

**Comment by dilijev** [comment]
The problem here is that we are leaking implementation details of Intl via the debugger logging. In general, functions called from Intl are called with Intl's special implementation of the function call operation, `IntlEngineInterfaceExtensionObject::EntryIntl_BuiltIn_CallInstanceFunction` called from Intl.js as `callInstanceFunc`, exposed to Intl.js as `platform.builtInCallInstanceFunction` (see [line 24](https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Library/InJavascript/Intl.js#L24) `var callInstanceFunc = platform.builtInCallInstanceFunction;`)

Looks like that didn't happen here.

**Comment by dilijev** [comment]
Looks like this isn't a problem with the JS code in Intl.js but rather how the C++ code calls the outer function of Intl.js. Changing [line 8](https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Library/InJavascript/Intl.js#L8) to

```js
(function IntlInit(EngineInterface, InitType) {
```

The debugger dump now shows:

```
"[IntlInit returned]": "undefined undefined",
```

**Comment by dilijev** [comment]
See: `IntlEngineInterfaceExtensionObject::InjectIntlLibraryCode`

[This line](
https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp#L478) calls the outer function in Intl.js:
`JavascriptFunction::CallRootFunctionInScript(function, Js::Arguments(callInfo, args));`
