### ISSUE TITLE
clang: error: unable to execute command: Killed

### ISSUE THREAD

**Issue by bpavesi** [Microsoft/ChakraCore#3567]
Hi all, i'm unable to build ChakraCore on Ubuntu 16.04.3 64bit due to this error. Any solution?

[100%] Linking CXX shared library libChakraCore.so
clang: error: unable to execute command: Killed
clang: error: linker command failed due to signal (use -v to see invocation)
bin/ChakraCore/CMakeFiles/ChakraCore.dir/build.make:147: recipe for target 'bin/ChakraCore/libChakraCore.so' failed
make[2]: *** [bin/ChakraCore/libChakraCore.so] Error 254
CMakeFiles/Makefile2:1790: recipe for target 'bin/ChakraCore/CMakeFiles/ChakraCore.dir/all' failed
make[1]: *** [bin/ChakraCore/CMakeFiles/ChakraCore.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
See error details above. Exit code was 2

**Comment by obastemur** [comment]
You need ~2.5Gb system memory to compile ChakraCore in Debug mode. Otherwise LD fails with out of memory. If you can't increase the system memory, you may use swap files too. I use the second option for raspberry Pi.

You may compile ChakraCore in Release / Test mode with lower amount of system memory.

Closing for now. If you can't fix the problem by increasing the memory. Feel free to open it back.

**Comment by bpavesi** [comment]
I increased the momory and now it works!
Tnx
