### ISSUE TITLE
Intl: Date.toLocaleString on date/year with >10000 returns an error "Invalid procedure call or argument"

### ISSUE THREAD

**Issue by sanyamc** [Microsoft/ChakraCore#3579]
Repro:
var a = new Date(10000,5,1)
a.toLocaleString()

Observed:
Invalid procedure call or argument
Works in chrome; errors out in Edge/IE11.

**Comment by obastemur** [comment]
@sanyamc Thanks for reporting.

This affects Windows only.

**Comment by dilijev** [comment]
Definitely related to Intl (WinGlob). On Windows (with WinGlob implementation of Intl and with Intl enabled), we see the `TypeError`, with Intl disabled we fall back on the non-Intl implementation of toLocaleString (see Intl spec https://tc39.github.io/ecma402/#sup-date.prototype.tolocalestring and Ecma-262 spec https://tc39.github.io/ecma262/#sec-date.prototype.tolocalestring)

```
>es --tags council -h ch-dev-che3-no-intl -its -e "new Date(10000,5,1).toLocaleString('en-us') + ''"
## Source
print(new Date(10000,5,1).toLocaleString('en-us') + '')

┌─────────────────────┬────────────────────────────────────────────────────────────┐
│ ch-1.7.1            │                                                            │
│ node-ch             │ TypeError: Invalid procedure call or argument              │
├─────────────────────┼────────────────────────────────────────────────────────────┤
│ d8                  │ 6/1/10000, 12:00:00 AM                                     │
│ node                │                                                            │
│ sm                  │                                                            │
├─────────────────────┼────────────────────────────────────────────────────────────┤
│ ch-dev-che3-no-intl │ Thu Jun 01 10000 00:00:00 GMT-0700 (Pacific Daylight Time) │
└─────────────────────┴────────────────────────────────────────────────────────────┘

>es --tags council -h ch-dev-che3-no-intl -its -e "new Date(10000,5,1) + ''"
## Source
print(new Date(10000,5,1) + '')

┌─────────────────────┬────────────────────────────────────────────────────────────┐
│ ch-1.7.1            │ Thu Jun 01 10000 00:00:00 GMT-0700 (Pacific Daylight Time) │
│ ch-dev-che3-no-intl │                                                            │
│ d8                  │                                                            │
│ node                │                                                            │
│ node-ch             │                                                            │
├─────────────────────┼────────────────────────────────────────────────────────────┤
│ sm                  │ Thu Jun 01 10000 00:00:00 GMT-0700 (Pacific Standard Time) │
└─────────────────────┴────────────────────────────────────────────────────────────┘
```

**Comment by dilijev** [comment]
Confirmed this error is due to a failure within WinGlob. Closing as External.

**Comment by dilijev** [comment]
As part of #3644, see whether there's anything we can do to recover from this error instead of just showing an error (perhaps fall-back on non-Intl definition of toLocaleString).

**Comment by dilijev** [comment]
I think your claim that it doesn't work for values <= 1000 is a bit extreme. This seems to be a very specific failure related to year 0 (first day of year 1 timezone-adjusted to year 0).

Your test case:

```
## Source
print((new Date('0001-01-01T00:00:00+00:00')).toLocaleString())

┌──────────────────┬───────────────────────────────────────────────┐
│ d8               │ 12/31/1, 4:07:02 PM                           │
├──────────────────┼───────────────────────────────────────────────┤
│ ch-1.7.1         │                                               │
│ ch-master-latest │ TypeError: Invalid procedure call or argument │
│ node-ch          │                                               │
├──────────────────┼───────────────────────────────────────────────┤
│ jsc              │ 1/2/1, 4:07:02 PM                             │
├──────────────────┼───────────────────────────────────────────────┤
│ sm               │ 31/12/1, 16:07:02                             │
├──────────────────┼───────────────────────────────────────────────┤
│ node             │ 1-12-31 16:07:02                              │
└──────────────────┴───────────────────────────────────────────────┘
```

With an explicit locale to make more of the outputs agree and I believe the old version of `jsc` does date/timezone conversions incorrectly but it has been fixed in later versions:

```
## Source
print((new Date('0001-01-01T00:00:00+00:00')).toLocaleString('en-us'))

┌──────────────────┬───────────────────────────────────────────────┐
│ d8               │ 12/31/1, 4:07:02 PM                           │
│ node             │                                               │
│ sm               │                                               │
├──────────────────┼───────────────────────────────────────────────┤
│ ch-master-latest │                                               │
│ node-ch          │ TypeError: Invalid procedure call or argument │
└──────────────────┴───────────────────────────────────────────────┘
```

Looks like WinGlob doesn't support the year 0 and timezone conversions set the date back to year 0. It looks like ICU saturates it down to year 1 even though it is incorrect to do so.

See this modification for year 3 (sanitized out bidi markers from WinGlob output as well):

```
## Source
print((new Date('0003-01-01T00:00:00+00:00')).toLocaleString('en-us').replace(/[^\w\d/: ]/ig,''))

┌──────────────────┬────────────────────┐
│ d8               │ 12/31/2 4:07:02 PM │
│ node             │                    │
│ sm               │                    │
├──────────────────┼────────────────────┤
│ ch-master-latest │ 12/31/2 4:00:00 PM │
│ node-ch          │                    │
└──────────────────┴────────────────────┘
```

At this point aside from the difference in whether to display minutes/seconds, the outputs agree.

Even simply moving to the next day fixes the error and the engines agree on the date and hour:

```
## Source
print((new Date('0001-01-02T00:00:00+00:00')).toLocaleString('en-us').replace(/[^\w\d/: ]/ig,''))

┌──────────────────┬──────────────────┐
│ d8               │ 1/1/1 4:07:02 PM │
│ node             │                  │
│ sm               │                  │
├──────────────────┼──────────────────┤
│ ch-master-latest │ 1/1/1 4:00:00 PM │
│ node-ch          │                  │
└──────────────────┴──────────────────┘
```

**Comment by dilijev** [comment]
In our opinion, since WinGlob does not support values outside of [1,9999] for the year, throwing is better than clamping the year to [1,9999] and rendering something completely inaccurate. At least this way you can catch an exception and see that we've done something wrong.

It might be possible for us to implement the workaround of printing using the non-Intl method (i.e. `Date.prototype.toString()`) to display something with correct information even if it's not the expected Intl/WinGlob output.

Will update as more details become available.

/cc @bterlson

**Comment by dilijev** [comment]
Looks like the engines disagree about how to toString non-4-digit positive number years...

```
## Source
print(new Date('0000-01-01T00:00:00+00:00').toString())

┌──────────────────┬────────────────────────────────────────────────────────────┐
│ d8               │ Fri Dec 31 -001 16:00:00 GMT-0800 (Pacific Standard Time)  │
│ jsc              │                                                            │
├──────────────────┼────────────────────────────────────────────────────────────┤
│ ch-1.7.1         │ Fri Dec 31 -1 16:00:00 GMT-0800 (Pacific Standard Time)    │
│ ch-master-latest │                                                            │
│ node-ch          │                                                            │
├──────────────────┼────────────────────────────────────────────────────────────┤
│ sm               │ Fri Dec 31 -0001 16:00:00 GMT-0800 (Pacific Daylight Time) │
├──────────────────┼────────────────────────────────────────────────────────────┤
│ node             │ Fri Dec 31   -1 16:00:00 GMT-0800 (Pacific Standard Time)  │
└──────────────────┴────────────────────────────────────────────────────────────┘
```

```
## Source
print(new Date('0001-01-01T00:00:00+00:00').toString())

┌──────────────────┬───────────────────────────────────────────────────────────┐
│ ch-1.7.1         │ Sun Dec 31 0 16:00:00 GMT-0800 (Pacific Standard Time)    │
│ ch-master-latest │                                                           │
│ node-ch          │                                                           │
├──────────────────┼───────────────────────────────────────────────────────────┤
│ d8               │ Sun Dec 31 0000 16:00:00 GMT-0800 (Pacific Standard Time) │
│ jsc              │                                                           │
├──────────────────┼───────────────────────────────────────────────────────────┤
│ sm               │ Sun Dec 31 0000 16:00:00 GMT-0800 (Pacific Daylight Time) │
├──────────────────┼───────────────────────────────────────────────────────────┤
│ node             │ Sun Dec 31    0 16:00:00 GMT-0800 (Pacific Standard Time) │
└──────────────────┴───────────────────────────────────────────────────────────┘
```

**Comment by mohamedmansour** [comment]
I hope the fix or improvement would match other vendors and not throw an exception. But honestly this should be taken up at the next Ecmascript committee to have a standard of invalid dates. Cause all vendors do it their own way :(

**Comment by bterlson** [comment]
@mohamedmansour I represent Chakra on in the ECMAScript committee, and am very much having discussions about exactly these problems. A little but of context: the specification leaves much up to implementers by design. This is to allow for implementing Intl APIs using a variety of techniques and libraries including both WinGlob and ICU. Even simple things like "what's an invalid date" can vary across platforms and locales.

Up for debate is how valuable this specification is as-written. We're presently in a place where 3 engines use the same back-end library (ICU) and thus agree on pretty much everything. Then, there's us, conforming to the specification but in a different way, and it's not good for interoperability as most developers feel like if 3 browsers agree on a thing, that thing is at the very least a defacto standard.

My personal belief is that we're already at the point of ICU being a defacto standard on the web and thus ChakraCore will want to use it on all platforms eventually. It will take some time to figure this out (on both our end and on the standards side) so be patient! In the meantime, if anyone is interested in this space, I recommend following the standards work happening here: https://github.com/tc39/ecma402.
