### ISSUE TITLE
Reveal Windows Insider and ChakraCore (base) revision mapping

### ISSUE THREAD

**Issue by phistuck** [Microsoft/ChakraCore#359]
I am not sure where is the best place to surface this. Perhaps multiple places -
1. Here in the wiki.
2. In the Edge change log.
3. In the Windows Insider announcement blog (https://blogs.windows.com/windowsexperience/2016/02/19/announcing-windows-10-mobile-insider-preview-build-14267/ for example).

Basically a table of

```
Windows Insider Build Number | Platform | ChakaraCore Base Revision
14267                        | Desktop  | https://github.com/Microsoft/ChakraCore/commit/c70cd6cf9daf609ca4139ef148cd1743081d22ea
14267                        | Mobile   | https://github.com/Microsoft/ChakraCore/commit/6e90b4adb9bbc042289b4e45d8dd7145aebcbb0e
```

**Comment by tcare** [comment]
This is hard to do, because ChakraCore.dll does not ship with Windows. There is an approximate correlation for what we build Chakra.dll from, but it is not exact.

**Comment by bterlson** [comment]
:+1:, I would also find this very handy :-P An approximation is fine.

**Comment by tcare** [comment]
After discussing this a bit today, a hash is till quite hard for us to do since there's no direct correlation. However, a changelog or list of features going out might be doable. It's still quite hard for us to do this at a per-change level internally though. If there's demand we'll certainly look into it.

**Comment by phistuck** [comment]
Just to be clearer, can you clarify how is it that there is no direct correlation?

**Comment by tcare** [comment]
First some good news, after chatting with @EdMaurer it looks like we can work with some people internally to make this a bit easier for us to do. We'll give things a go next time we flight some major changes.

To elaborate on why this is currently difficult for us, I need to give a bit of background about how ChakraCore relates to Windows. Chakra.dll, which ships with Windows, is a superset of ChakraCore and contains ChakraCore as a submodule. Chakra.dll cannot build independently. As such, it requires ChakraCore to be in a state where internal changes related to Chakra.dll are not broken by ChakraCore.

We do our best to keep GitHub in sync with what is used by Chakra.dll, but due to internal code and the time delay between GitHub and flighting we often have to do some branch management with ChakraCore internally. This means that the hash we see internally may not be meaningful on GitHub, or have extra commits to get things ready for flighting, merge commits, some fixes disabled, etc.

What I spoke to Ed about was making it faster for us to backtrack from the flighting version of Chakra.dll to a hash range that we could use to figure out the changes from ChakraCore. Once we have that, we could figure out which commits in that range came from GitHub itself. It's definitely an approximation, and not a guarantee that everything in there is enabled, but it should give us some idea of the range of commits that came in.

We're certainly interested in what you would find helpful about the hashes. Would you like what went in on a commit level? Feature level? Or would you just like to browse the code around that particular flight?

**Comment by phistuck** [comment]
Feature level should already be exposed by the Edge changelog, right? So this is unnecessary, I think (and it takes more manual work, I believe).

One of the purposes of this is to know whether a contribution made into the flight so contributors could test (or brag about ;)) their contribution using a Windows Insider build or RemoteIE.
The other is to have a finely grained change log for a released build, just like you can get from other open source engines.

Ideally, I think the last option is the best. It will ideally either be a branch or a tag or something and it would include all of the commits that are actually in the released (preview or not) build (and exclude excluded commits).

**Comment by phistuck** [comment]
It is great to read that it is closer to being possible!

Feature level should already be exposed by the Edge changelog, right? So this is unnecessary, I think (and it takes more manual work, I believe).

One of the purposes of this is to know whether a contribution made it into a released (preview or not) build so contributors could test (or brag about ;)) their contribution using a Windows Insider build or RemoteIE.
Another purpose is to have a finely grained change log for a released build, just like you can get from other open source engines.

Ideally, I think the last option is the best. It will ideally either be a branch or a tag or something and it would include all of the open source commits that are actually in the released (preview or not) build (and exclude excluded open source commits).

**Comment by yuhong** [comment]
What about things like security updates?

**Comment by EdMaurer** [comment]
We're moving towards a plan in which we provide the last ChakraCore commit hash that flowed into Chakra.dll as a string in the file's resources. In Windows Explorer, one could right click the binary, select "Properties," go to the "Details" tab and see the commit hash in the "Product version" string. All of the earlier ChakraCore commits could be assumed to be included. We would not update this as the binary was serviced, only on a new OS flight or release.

**Comment by dilijev** [comment]
Doing some issue tracker cleanup. This discussion has stalled so I'm closing this issue. Please feel free to comment if you have a need for this.
/cc @kfarnung @agarwal-sandeep
