### ISSUE TITLE
Object keys should not reorder if they are numerical. 

### ISSUE THREAD

**Issue by restarian** [Microsoft/ChakraCore#3614]
Object qualifiers are linked, and iterated upon in ECMA. Object key order should never change even when key iterating code is idempotent sense the most efficient code design can only be written knowing the iteration ahead of time. 
Currently, in other ecma implementations, Object keys are/can be reordered dependent on if it is numerical. Index value re-ordering is one of those annoying functionalities in C/C++ that javascript should be blanketing. The ecma specification needs to change as well. I would be thrilled to see this happen with chakra. 

Sharpen your swords here -->
[The debate](https://stackoverflow.com/questions/3186770/chrome-re-ordering-object-keys-if-numerics-is-that-normal-expected)

**Comment by dilijev** [comment]
There are implementation reasons (major runtime efficiency impact) for not requiring an iteration order, especially because objects with many properties can be implemented as hash maps (which don't have a consistent ordering as they grow).

(For the spec change request, you might want to start a discussion on https://esdiscuss.org or #tc39 on freenode, but I imagine TC39, which includes implementers, will defend this point.)

/cc @bterlson

**Comment by fatcerberus** [comment]
I got the impression the argument *wasn't* about requiring an iteration order, but rather arguing *against* JS sorting integer keys in ascending order (which is indeed the case, per spec).  I think he wants them treated the same as other properties?

**Comment by dilijev** [comment]
It's possible we don't understand the requested change here, but if the spec needs to change, please discuss with TC39 to get the spec to change. Otherwise, if we diverge from the spec, please provide a link to the relevant section of the spec and a test case which demonstrates the incorrect behavior.

**Comment by restarian** [comment]
Another reason for Object keys to not re-order is that the most useful/relevant properties of an Object are the ones which are added last.  E.g. if a logging tool is printing the first 100 characters of Objects to the screen, it is best to print the properties which are added last sense printing the first 100 characters of known Objects would not be as useful (like jquery or dom Objects which have been altered).
