### ISSUE TITLE
API to trigger immediate breakpoint?

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#3628]
I was looking through the debugging API and couldn't find a function to trigger an immediate break.  My next thought was to use `JsDiagEvaluate()` to inject a `debugger` statement, but it can only be used while already at a breakpoint.

**Comment by digitalinfinity** [comment]
Does `JsDiagRequestAsyncBreak` do what you want? It should ask the VM to break when the next JS statement gets executed which sounds close to what you want?

cc @agarwal-sandeep @kfarnung

**Comment by digitalinfinity** [comment]
Although I believe that you would have to call `JsDiagStartDebugging` first

**Comment by fatcerberus** [comment]
Interesting, somehow I missed that one.  Is that thread-safe, i.e. can I call it on a different thread than the one the runtime is on?  I would like to implement a setup where if the user presses F12 at any time it immediately breaks into the debugger, but for that to work reliably I would have to check for the keypress off-thread.

**Comment by agarwal-sandeep** [comment]
@fatcerberus JsDiagRequestAsyncBreak can be called from another thread. Node-chakracore calls it from inspector [thread](https://github.com/nodejs/node-chakracore/blob/f839c0b54642cd8698ac7da1c8d961cb6f5d34c8/deps/chakrashim/src/jsrtinspector.cc#L184) to process messages from debugger frontend but the runtime on which JsDiagRequestAsyncBreak is called should already be in debug mode otherwise it will return JsErrorDiagNotInDebugMode error.

For your scenario you have to handle this in host layer. On recieving the F12 keypress signal script thread and call JsDiagStartDebugging or have the runtime in debug mode from beginning by calling JsDiagStartDebugging after creating the runtime.

**Comment by fatcerberus** [comment]
Will putting the runtime in debugging mode from the start slow down execution?

**Comment by agarwal-sandeep** [comment]
It will have some performance impact as few optimizations will be turned off when running in debug mode and will vary based on how much time is spend in script and host calls.

**Comment by fatcerberus** [comment]
Thank you, this will come in handy. :)

Closing as question is answered.
