### ISSUE TITLE
Intl-ICU: platform.resolveLocaleBestFit

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#3674]
* [x] Fallback logic (#3654)
* [ ] Implement with ICU

**Comment by jackhorton** [comment]
Is the path forward here to pass the user-provided locale directly to the backing ICU constructor and let it figure out what it wants to do? I am not sure that that's any better than the Intl algorithm and it would be somewhat wasteful to implement, since we likely wouldn't be able to easily cache the ICU object that gets created... I think I vote to close this for now, lookup is as good as we will do for the time being.

**Comment by dilijev** [comment]
Best Fit is implementation-defined. This can, indefinitely, fall back on resolveLocaleLookup logic. Feel free to close this issue if there is no plan to implement it and this is just clutter. However, before we close this issue, I think we should research whether ICU exposes something to us we can use to get better BestFit logic in a relatively straightforward way.

**Comment by jackhorton** [comment]
I am going to call this wontfix until we get a particularly compelling reason or way to do so.

**Comment by dilijev** [comment]
Yeah I'm pretty sure other engines just punt on this point as well.
