### ISSUE TITLE
Intl-ICU: On Windows, use ICU from Windows Kit (compile option overrides).

### ISSUE THREAD

**Issue by dilijev** [Microsoft/ChakraCore#3675]

**Comment by jackhorton** [comment]
Do we think this is still important? This will only work on RS2+, so it would severely limit the benefit of ChakraCore running downlevel.

**Comment by dilijev** [comment]
This is probably out of date given the more recent design discussions anyway. Windows Kit is a dev dependency to be installed, includes dev headers not just data for the runtime -- and might work downlevel as well, so it's a potential place we could try to grab ICU data from, but probably not worth it -- and ICU data already exists on the system in RS2+ regardless of whether the Windows Kit is installed.

**Comment by jackhorton** [comment]
So by Windows Kit ICU, I meant the icuuc.dll, icuin.dll, and icudt.dat that are included in every box, which is vaguely related to the headers that you get when you install an RS2+ Windows SDK. By depending on any of that at any time, it limits ChakraCore to running by default only on RS2+. The ICU team did some investigation on how far downlevel those DLLs can go and the ones that are in-box can only be copied onto TH1+ machines, since they depend on apiset shenaniganry when built within Razzle. The UWP projects included by default in the ICU source code do work downlevel to windows 8ish, but then theyre technically incompatible with whats on RS2 because they just link to kernel32.lib.... the entire situation is fuzzy and I don't think its a good idea to expose this until we get a specific use case for it.

**Comment by dilijev** [comment]
I'm not sure we should refer to those in-box binaries (the ones you mentioned which live under `C:\Windows\…`) as Windows Kit because the Windows Kit version is installed as an SDK with VS (I think) at `C:\Program Files (x86)\Windows Kits\10\…`. Mixing up this terminology could prove to be confusing.

**Comment by jackhorton** [comment]
What is installed with the Windows Kit is just the headers and link libs. The DLLs and data file are in every RS2+ box (similar to the distinction between kernel32.dll and kernel32.lib + windows.h)

**Comment by dilijev** [comment]
Ah yeah, dev dependencies for the in-box thing. Does the ICU stuff installed in Windows 10 Kit not work downlevel? I guess it's the same as what you were saying, due to implementation, it only works down to TH1+ but not Win8/Blue.

**Comment by jackhorton** [comment]
The headers aren't relevant since they aren't present at runtime, and Curtis thinks that the link libs should be compatible since they point to names in the DLLs rather than any sort of offset, which is the old-style DLL Hell problem (apparently, I am not particularly familiar with any of these things).
