### ISSUE TITLE
Unable to attach debugger during execution

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#3697]
I would like to allow my debugger to attach to a running instance of miniSphere, as can be done with a native code debugger.  However, if I call `JsDiagStartDebugging()` during active JS execution (i.e. any time the JS call stack is not empty), I get `JsErrorRuntimeInUse` and debugging is not enabled.

Is this by design?  The comment here https://github.com/Microsoft/ChakraCore/issues/3628#issuecomment-326651449 implied it was allowed to start debugging in the middle of execution.

**Comment by agarwal-sandeep** [comment]
@fatcerberus Yes that's by design. [JsDiagStartDebugging](https://github.com/Microsoft/ChakraCore/blob/36bd20a7863c3dcd08fd9cb663bdc86ff68e3beb/lib/Jsrt/JsrtDiag.cpp#L35) is not allowed when [script](https://github.com/Microsoft/ChakraCore/blob/36bd20a7863c3dcd08fd9cb663bdc86ff68e3beb/lib/Runtime/Base/ThreadContext.h#L852) is on call stack.

**Comment by fatcerberus** [comment]
Hm, so for my scenario I would have to call JsDiagStartDebugging() before running the main script and take a performance hit.  I guess that makes sense, the engine may do optimizations that would be invalidated if the debugger is attached midstream.

The performance hit is unfortunate, but shouldn't be a big problem since I can just disable debugging in my redistributable.  Thanks!
