### ISSUE TITLE
TODO: Platform agnostic virtual memory management

### ISSUE THREAD

**Issue by obastemur** [Microsoft/ChakraCore#3726]
1 - Virtual memory backend we use on xplat is pretty expensive.

 - memory region is stored on a linked list
 - Each VirtualProtect / Commit etc. requests end-up searching through the linked list.
 - we acquire a lock each time since this linked list is process wide.

#3725 reduces the number of times we loop the whole list.

2 - Backend is unaware the intentions. 

Consumer (CC) already has start boundary information (and others) on many places. However, current common interface we use for both Windows and xplat doesn't allow us to use the data without looking up for memory region store.

3 - Complicated mprotect usage.

mprotect is not that cheap to call on small parts of the mapped area.

**Comment by digitalinfinity** [comment]
@obastemur I think there are two choices here- one is improving the implementation of the VM subsystem in the PAL, and the second is introducing a platform agnostic layer for VMM and changing Chakra's PageAllocators/other MM classes to use it. The second is definitely more expensive to implement than the first.

In terms of node benchmarks like AcmeAir, do you have a sense of how much the cost is today as a percentage of main thread CPU time for 1, and how much we could gain if we went with the first choice instead of the second.

**Comment by obastemur** [comment]
@digitalinfinity I agree with the number of possible approaches you did mention. 

Performance-wise, not sure if we can reduce mprotect+mmap double calls. Besides, because of common memory region linked list, we hold a lock on each and every VM call. I did open this issue to at some point check if threads are waiting each other because of that lock.

#3725 patches the looping problem reasonably.

I came to this issue while tracking the #3650 . lots of kernel breaks on the main thread.

**Comment by obastemur** [comment]
considered as a part of #4093
