### ISSUE TITLE
Edge javascript slowdown

### ISSUE THREAD

**Issue by chris70c** [microsoft/ChakraCore#3828]
This test program takes about 300ms in both Chrome (canary 63) and Firefox (Nightly 58.0a1) and slightly less using a worker.
In Edge (EdgeHTML 15.15063) it takes about 13 seconds and the worker version never prints anything at all.

You can find the test program here:
http://www.neoartcr.com/edge_test/index_worker.htm
http://www.neoartcr.com/edge_test/index_noworker.htm

Keep the console open to see the time it takes to run the test.

Thanks
Christian

**Comment by obastemur** [comment]
I saw the worker.js but honestly I didn't try on console. Is it fair to ask you for a reduced version of this issue (into a single JS file)? That could help me (potentially others) to inspect this problem sooner!

@chris70c Thanks for sharing this issue with us anyways 👍

**Comment by akroshg** [comment]
@chris70c I ran this scenario (http://www.neoartcr.com/edge_test/index_noworker.htm) and I get around ~800ms.
When you open F12 the Edge goes to debug mode which slows things down a bit. 
In **F12** 
go to **Debugger** tab and click on the **unplug** icon (The tool tip says, **debugger connected click to disconnect**). Can you run the scenario after that?

**Comment by chris70c** [comment]
obastemur: it is already a single js file the main.js is to launch the worker, nothing else; unfortunately I can't make the code any simpler 'cause is part of a C=64 sid emulator that I'm writing and that is the filter tables creation.

akroshg: even with the debugger unplugged I still get ~920ms seconds, still 3 times slower than Chrome/Firefox and the worker version still doesn't print anything at all (can't see why unless console.time is not available in workers but it is in Chrome/Firefox)

**Comment by chris70c** [comment]
btw, is the SharedArrayBuffer available in Edge 15.15063 with the experimental flag enabled?

**Comment by MikeHolman** [comment]
Yeah, pretty sure SAB is under experimental flag in Edge 15.

Regarding webworker case never printing, I vaguely remember reading something about console.log not working inside webworkers in Edge. I think that may be an Edge bug though rather than Chakra bug.

I took a quick look at the JS file, and it looks like the big bottleneck is creating `new Point()` inside of `evaluate`. 

Replacing `const out = new Point()` with  `const out = {x:0, y:0}` improved perf by 50%. (I got similar results by transpiling the file with typescript.)

Improving perf for new language features is on our radar, and clearly we have some work to do for class constructors.

**Comment by chris70c** [comment]
MikeHolman: not sure that's the only bottleneck here's a breakdown of the timing for Edge followed by Chrome.

Edge:
scaled: 0,1ms
spline: 0,21ms
opamprev: 6,29ms
opampmodel: 0,185ms
summer: 264,065ms
mixer: 414,11ms
gain: 205,045ms
vcr: 6,54ms
total: 898,085ms

Chrome:
scaled: 0.030029296875ms
spline: 0.666015625ms
opamprev: 14.281005859375ms
opampmodel: 0.146728515625ms
summer: 98.550048828125ms
mixer: 114.326171875ms
gain: 85.817138671875ms
vcr: 17.288818359375ms
total: 334.651123046875ms

**Comment by chris70c** [comment]
Edge timing replace new Point() with {x:0, y:0}.

scaled: 0,085ms
spline: 0,185ms
opamprev: 4,36ms
opampmodel: 0,195ms
summer: 133,81ms
mixer: 283,815ms
gain: 132,29ms
vcr: 6,48ms
total: 562,1ms

**Comment by chris70c** [comment]
Also you can see from here that the SharedArrayBuffer is not working (at least not as expected).

http://www.neoartcr.com/edge_test2/

in Chrome you can see that the values of the shared buffer are being changed while in Edge they're still all zeros.

**Comment by chris70c** [comment]
Here's a much simpler test, Edge (debugger disconnected) takes between 28 and 32ms against Chrome 14-18ms; for such a simple loop twice as much time seems a bit excessive.

http://www.neoartcr.com/edge_test3/

**Comment by MikeHolman** [comment]
I don't repro the SAB bug on my machine (which has prerelease build of Edge 16), so I'm thinking that was fixed.

For the original issue, other than the time in constructor time is all in JIT code. The JIT code looks fine at first glance, but clearly we are missing some significant optimization opportunity.

For the new issue, the problem is that the div is using floating point math. We need the result as a uint16, so we should be able to do it as integer divide.

**Comment by MikeHolman** [comment]
Actually, I doubt chrome int divide there either. A 20ms test is too small to really get good numbers (you are testing our interpreter vs. their baseline JIT for much of that time). I made the test loop and I'm seeing the same score on Chrome and Edge now.

````html
<script>
const buffer = new Uint16Array(5000000);

start = new Date();

function bar() {
    for (let i = 0, len = buffer.length; i < len; i++) {
        let idiv = 1;
        let size = 1;

        if (i) {
            idiv = i;
            size = i << 16;
        }

        const n = i * 8 / 6;

        buffer[i] = n;
    }
}
for (var i = 0; i < 100; ++i)
    bar()

console.log(new Date() - start)
</script>
````

**Comment by chris70c** [comment]
not sure which Edge version are you using because on Edge 15 your test takes 2577ms against 806ms in Chrome here.

**Comment by obastemur** [comment]
@MikeHolman The issue there is `n` is being a floating number.

Try replacing `8/6` to `8/4` It will run 3 times faster.

**Comment by akroshg** [comment]
@leirocks can you confirm from what Edge version SAB is enabled?

**Comment by chris70c** [comment]
even if I replace 8 / 6 with 1.333333 doesn't change anything so the div is only part of the problem

**Comment by MikeHolman** [comment]
Interesting, what version of Chrome are you using? For me both Chrome 61 (x64) and Edge 16 (x64) take ~2 seconds. Possibly Chrome recently optimized this.

**Comment by chris70c** [comment]
Canary 63

**Comment by MikeHolman** [comment]
I installed Canary and am able to repro the perf improvement compared to Edge/Chrome stable, so it seems like this is a recent improvement. I suspect that they are now doing what I suggested and avoiding the floating point math.

**Comment by chris70c** [comment]
http://www.neoartcr.com/edge_test4/

this is another one, takes about 1850ms in Chrome, ~1200ms in FF, just crashes in Edge...

**Comment by MikeHolman** [comment]
I don't see a crash, but I do see Edge is something like 35x slower on this one. I don't have time to look at codegen right now, but part of this is that inlining in JIT loop bodies (as opposed to our full function JIT) is not very aggressive. In this case it is causing a 10x perf loss. Even still we're ~3x slower, so that needs to be looked at separately.

We aren't aggressive because we want loops to compile quickly and then the full function once it is called will get the more optimized code. In this case, that heuristic doesn't work out since there is no full function that ever gets called.

@rajatd I wonder if we should be more aggressive about inlining in global JIT loop bodies?

**Comment by chris70c** [comment]
It doesn't actually crash, it just sits there until the message to recover the webpage comes out but I never get the console output (debugger is disconnected).

**Comment by rajatd** [comment]
I tried the test on console and wrapping the hot loops in a function I definitely see ~10x improvement. However, inlining may not be the only thing missing because running the test with `-InlineInLoopBodyScaleDownFactor:1` (default is 4, it essentially brings down the inline threshold for loop bodies by the specified value), I see different degrees of improvement for the two loops - 

stock test:
1178.6666666666667
1210.2

with hot inner loops pulled into a function
174.46666666666667
133.43333333333334

loops left where they are, and run with `-InlineInLoopBodyScaleDownFactor:1`
107.3
321.53333333333336

Inlining more aggressively in global jitted loop bodies seems to make sense. There will be a trade off involved for sure, but definitely worth a try.

**Comment by rhuanjl** [comment]
No specific work to do on this - separate issues exist for the identifiable points.
