### ISSUE TITLE
utf8::NarrowToWide fails to return correct length

### ISSUE THREAD

**Issue by obastemur** [Microsoft/ChakraCore#3852]
Not sure what's going on here but we need to take a deeper look.

Repro:

```
utf8::NarrowToWide wname("Length", 7);
fprintf(stdout, "%d \n", wname.Length() == 6); // --> prints false!!
```

**Comment by jianchun** [comment]
> utf8::NarrowToWide wname("Length", 7);

Isn't it supposed to be `utf8::NarrowToWide wname("Length", 6);`?

**Comment by obastemur** [comment]
It is... but, what if it's 7? `node-chakracore` NAPI was setting 7... Why we keep the length 7?

**Comment by obastemur** [comment]
In other words, when I call `wname.Length()` I do expect a correct wide string length. Which is not `7`

**Comment by jianchun** [comment]
If you pass 7, the converter would try to convert the last 0. Need to examine what the code does. Won't be surprised if it outputs a mark to indicate invalid input.

**Comment by MSLaguana** [comment]
My understanding of the `NarrowToWide` converter is that the length parameter says how far it is permitted to read in the buffer; since we are using a literal it is null-terminated and thus there are 7 valid bytes to read, so it should still correctly convert things. What I'm not sure about is what the resulting `wname.Length()` is supposed to represent.

If we pass in a "buffer + length" representation, the length is the number of characters excluding a null terminator (but the string is null terminated). If we pass in a null terminated string and specify a length that passes the null, the `wname` string has the correct encoding, but now the length seems to include the null terminator. Which should it be? And does this also suggest that if we used non-ascii strings (which would trigger some of the same codepaths as finding a null) the length will behave differently?

**Comment by obastemur** [comment]
A reminder from a prev. experience: `"null characters don't mean anything in JS."` 

https://github.com/Microsoft/ChakraCore/issues/2397

So, we better keep things as is and continue taking `length` argument into consideration and don't care null ending?

**Comment by obastemur** [comment]
I would like to add a conclusion and close this issue. If anyone stumbles into this problem, I hope the discussion and notes here will help.

The behavior of `utf8::NarrowToWide::Length` is not quite expected from C,C++ experience point of view. However, this interface serves to a JS frontend and the behavior matches to specs.

Consumer is expected to be careful with setting the `length` argument value.

In case this conclusion + explanation feels wrong or not complete, feel free to open it back.
