### ISSUE TITLE
localeCompare doesn't take into account minus signs

### ISSUE THREAD

**Issue by SjoerdL** [Microsoft/ChakraCore#4060]
The compareLocale method seems to ignore minus signs, even when the numeric option is set:
````javascript
'-2'.localeCompare('1', undefined, {numeric: true});
````
results in 
````javascript
1
````
on Edge. This seems incorrect to me; other browsers also seem to handle this differently. The behavior is especially frustrating when trying to give a natural sorting to numbers. Example: 
```javascript
var strings = ['3', '1', '-2'];
var ascCompare = function(elem1, elem2) {
  return elem1.localeCompare(elem2, undefined, {numeric: true, sensitivity: 'variant'});
};
strings.sort(ascCompare);
```
results in 
````javascript
[1, -2, 3]
````
For a working example, see: https://jsfiddle.net/9rff9xLt/3/

**Comment by jackhorton** [comment]
I am not sure that other browsers handle this correctly either:

```js
"-2".localeCompare("-3", undefined, { numeric: true }) // -1
"-2".localeCompare("3", undefined, { numeric: true }) // -1
"-2".localeCompare("-1", undefined, { numeric: true }) // 1
"-2".localeCompare("1", undefined, { numeric: true }) // -1
```

I get the above commented results in both Firefox and Chrome. I know that the numeric option for ICU, which we are actively adding support for to enable the Intl object on Linux and macOS, explicitly states that it does not take minus signs into account (see UCOL_NUMERIC_COLLATION [here](http://icu-project.org/apiref/icu4c/ucol_8h.html)). I think there is some trickiness going on with the precedence of the negative sign. Change your fiddle JS to the following:

```js
var strings = ['3', '1', '-2', '-12', '12', '14', '-14'];
var ascCompare = function(elem1, elem2) {
  return elem1.localeCompare(elem2, undefined, {numeric: true});
};
```

Firefox/Chrome returns `[-2,-12,-14,1,3,12,14]` while Edge returns `[1,-2,3,12,-12,14,-14]` -- that is, Firefox/Chrome considers all negative numbers to be less than all positive numbers, but otherwise sorts negative numbers in increasing magnitude, while Edge seems to simply ignore the negative sign. I would suggest that neither are what you want, and the difference is probably directly related to the fact that both Firefox and Chrome use ICU for their Intl implementations while Edge uses Windows Globalization.

Unless I am misunderstanding your question/concern here, if you want to sort a list of numbers as strings and get back a list of numbers as strings, I would recommend something along the lines of the following (ugly) one-liner:

```js
const sorted = numbersAsStrings.map((el) => parseInt(el, 10))
    .filter((el) => !isNaN(el))
    .sort()
    .map((el) => el.toString())
```

**Comment by jackhorton** [comment]
Also, on an unrelated note, if you want to use an Intl-specified function as the compare function for a sort, look into creating a new Intl.Collator object and passing collator.compare as the sort function -- parsing the options to localeCompare is relatively expensive and may start to show up if you're sorting large arrays. #4007 tracks our work to cache option computation, but that is not going to be in RS3 edge or earlier.

**Comment by dilijev** [comment]
jsc doesn't seem to expose an Intl object in the console host so I'm leaving that out.

d8/sm/ICU default collation for `en-us` seems to be lexicographic, and numeric sorts negatives first in increasing magnitude, then positive numbers in increasing magnitude. Which might also just mean that numeric collation doesn't support negative signs as part of numbers and simply that `-` sorts before numbers, and then numeric collation is applied to the token of the string which was parsed as a number.

ch/WinGlob default collation seems (?) to be lexicographic (ignoring -) and then considers `-` to be negative and sorts them after positive numbers (??). Numeric collation is in increasing order of magnitude with positives before negatives.

Um... I don't know how to rationalize that behavior.

Test output below. Also demonstrates using Intl.Collator.prototype.compare instead of calling localeCompare every time.

```
## Source
let strings = ['3', '1', '-2', '-12', '12', '14', '-14', '2'];

let collBase = new Intl.Collator("en-us");
let collNumer = new Intl.Collator("en-us", {numeric: true});

function render(comparer)
{
    let sorted = strings.sort(comparer);
    let out = "";
    strings.forEach((x) => out += x + ",");
    print(out);
}

render(collBase.compare);
render(collNumer.compare);


┌──────────────────┬─────────────────────────┐
│ d8               │ -12,-14,-2,1,12,14,2,3, │
│ sm               │ -2,-12,-14,1,2,3,12,14, │
├──────────────────┼─────────────────────────┤
│ ch-master-latest │ 1,12,-12,14,-14,2,-2,3, │
│                  │ 1,2,-2,3,12,-12,14,-14, │
└──────────────────┴─────────────────────────┘
```

**Comment by dilijev** [comment]
Probably want to track this issue as part of #3644

**Comment by dilijev** [comment]
It doesn't seem that minus signs are considered as part of numeric collation even under ICU. For the rest of the differences (winglob vs ICU), tracking with #3644
