### ISSUE TITLE
Where is the module support in JSRT?

### ISSUE THREAD

**Issue by JohnMasen** [Microsoft/ChakraCore#4269]
hi,
as chakracore supports ES6, I suppose there's a "LoadMoudleScript" callback in JSRT. however I can't find it in the online document.
Can you guys please help me find out where's the module API?

Thanks

**Comment by liminzhu** [comment]
There’s a [PR](https://github.com/Microsoft/ChakraCore/commit/50767f9f33812b4a036794a6a98404145563409f) that gives you an overview of the related APIs and an example implementation (see WScriptJsrt.cpp in the same PR) in our own ch test host. It is not super well documented atm since it is experimental.

**Comment by JohnMasen** [comment]
Thanks liminzhu, any chance you can wrap it to the C# wrapper in the examples? Very appeared if you could do this, I'm not that good at wrapping native calls.

**Comment by liminzhu** [comment]
@JohnMasen you can just dllimport each API like what we did in the [samples](https://github.com/Microsoft/Chakra-Samples/blob/master/ChakraCore%20Samples/Hello%20World/Windows/C%23/HelloWorld/Hosting/Native.cs#L122) and build from there.
