### ISSUE TITLE
Exception seen in Xbox app: stowed_exception_delegate_800a138f_chakra.dll!__cunknownimpl_method0

### ISSUE THREAD

**Issue by marcpems** [Microsoft/ChakraCore#4344]
this crash is seen around 1k times in 72hrs for a public Xbox app. 
Exception occurs on Xbox RS3 images, seen on Xbox one, one S and one X.

**Exception:** 
stowed_exception_delegate_800a138f_chakra.dll!__cunknownimpl_method0

**Stack:**
Frame     Image                  Function                               Offset
0             Chakra.dll         
[5e99c4be-334b-4a3b-b713-aac84d0dd1df.ext.zip](https://github.com/Microsoft/ChakraCore/files/1514246/5e99c4be-334b-4a3b-b713-aac84d0dd1df.ext.zip)
   __CUnknownImpl_Method0 0x0000000000000000

**Comment by curtisman** [comment]
This usually mean a script error that wasn't handle by the app, not a crash by Chakra itself.
You will need to debug the scripts in the application to see what the script error is. 
Unfortunately, I am unable to provide more information just looking at the mini-dump without heap info.

**Comment by stratosnn** [comment]
@curtisman Hey, we have exactly the same issue. I wonder would it be possible to debug the exception further if we provide heapdump?
Also I wonder if this crash happens only if exception is thrown within "native" callback (i.e. "suspending" lifecycle event handler). I guess for normal errors thrown in JS browser shall not crash. Right?

**Comment by curtisman** [comment]
@stratosnn Unhandled exception in the Edge browser will not crash.
However for WWAs apps, the rules are different, where unhandled script error is fail fast (WWA will terminate the app after the script engine reported the error to the WWA host).

Since the fail fast is on the WWA side, I am not sure the exception is saved or not, or if there is a way to find out what the error is.  From my experience, heap dump at the point of fail fast is too late, or at least I haven't find a way.

A **very** hacky way if you have symbols is to scan the Chakra GC heap, in case the thrown error object is not collected and guess which in the heap is the one that caused the problem.
