### ISSUE TITLE
Incorrect Webassembly Behaviour

### ISSUE THREAD

**Issue by dtippett** [Microsoft/ChakraCore#4562]
The JavaScript and WebAssembly based sample at http://pdftron.s3.amazonaws.com/custom/ID-zJWLuhTffd3c/microsoft/EdgeWASMBug/WithWasm.html downloads a simple PDF file. In Chrome, Firefox this sample works fine, but in Edge it produces a corrupt PDF. 

In addition the asm.js only version at 
http://pdftron.s3.amazonaws.com/custom/ID-zJWLuhTffd3c/microsoft/EdgeWASMBug/WasmDisabled.html works everywhere, which suggests that there is a bug with the WebAssembly handling in Edge.

At the moment I have no choice but to disable WebAssembly for Edge in the viewer which is far from ideal. 

Thanks in advance for any fix or workaround you can provide,

David

**Comment by dtippett** [comment]
For reference I am currently running Edge 41.16299.15.0,

**Comment by MikeHolman** [comment]
This was fixed by #4256, which will ship in RS4.

Until then a workaround would be to change the code around where we are doing the bad divide.

I was able to find the function where the bad divide is happening, but I don't have names for the wasm functions, so I can't say exactly what the source function is (in the wasm module, it's func $720), i.e. this function:
[720.txt](https://github.com/Microsoft/ChakraCore/files/1709673/720.txt)

Probably hard to tell what function it is from that, so you might try searching for a couple constant values used early in the function:
````
      (f64.const -2.25179981369e+15)
      (f64.lt)
      (get_local 0)
      (f64.const 2.25179981369e+15)
````

The problematic divide is one of the 2 places where you do this:
````
                    (i32.const 100)
                    (i32.rem_u)
                    (set_local 4)
                    (get_local 3)
                    (i32.const 100)
                    (i32.div_u)
````
In source maybe it looks something like this? The generated code is a bit funky, so it's hard to tell.
````
uint a = b % 100;
c = doubleArray[(b / 100)]
````

Anyway, if you can find this, I think reordering the divide and the remainder operations should make your code work in Edge even without my fix.

**Comment by dtippett** [comment]
Thanks, Michael! It's great to know this will be fixed in the next version. I wasn't able to get it working even with the divide and mod operations reordered, (which incidentally was due to a compiler optimization, they were written in the other order) so I suppose I will just have to keep WebAssembly disabled for the current version of Edge.

Is there a reasonable way to feature detect this bug or is my best bet to simply check the version number?

Thanks again,

David

**Comment by MikeHolman** [comment]
I think your best bet is looking at version number -- the bug requires specific register allocation, so it's hard to come up with a small test.

I'm a bit surprised the reordering didn't work, but I guess that could have changed the register allocation. The other workaround I can think of would be to manually apply strength reduction on the divide (something we were only doing for powers of 2 until recently).
So you could change this:
````
(get_local 3)
(i32.const 100)
(i32.div_u)
````
Into:
````
get_local 3
i64.extend_u/i32
i64.const 1374389535
i64.mul
i64.const 37
i64.shr_u
i32.wrap/i64
````

**Comment by kfarnung** [comment]
@MikeHolman If this is fixed can we close the issue?
