### ISSUE TITLE
how to access Object or Array (JS's ChakraCore side) from native code

### ISSUE THREAD

**Issue by lemmel** [Microsoft/ChakraCore#4678]
Hi.

For my project I'm in the need of an access to the data from the JS world side.

As of today, I think I know how to access to a "basic type" (such string, number or boolean; for example to read a value: a call to [JsCreatePropertyId](https://github.com/Microsoft/ChakraCore/wiki/JsCreatePropertyId), a call to [JsGetProperty](https://github.com/Microsoft/ChakraCore/wiki/JsGetProperty), then a call to either [JsNumberToDouble](https://github.com/Microsoft/ChakraCore/wiki/JsNumberToDouble), [JsCopyString](https://github.com/Microsoft/ChakraCore/wiki/JsCopyString), [JsBooleanToBool](https://github.com/Microsoft/ChakraCore/wiki/JsBooleanToBool)).

### the problem
But I want to access object and array, and I didn't found how to do it.
I saw in your [data for test](https://github.com/Microsoft/ChakraCore/tree/master/test) there is an object, called WScript, that could help me to understand, but I didn't find its definition 

Have you any example to how to read/write such complex type ? Do I need to consider object and array as local context and do in the same way that the global object ?

**Comment by MSLaguana** [comment]
The `WScript` object is something provided by our test host `ch`; you can see how we set everything up at https://github.com/Microsoft/ChakraCore/tree/master/bin/ch

Regarding your problem, what do you mean by "read/write" the type? If you want to find all the properties that an object has, you can use `JsGetOwnPropertyNames` and `JsGetOwnPropertySymbols` to get the different properties that an object has (and you can `JsGetPrototype` and walk the prototype chain, although some care is needed due to proxies)

If instead you mean that you want to to do the equivalent of `arr[2] = foo` or `o.x = foo`, then you can use `Js(Get/Set)IndexedProperty` or `Js(Get/Set)Property`.

Does that answer your question?

**Comment by lemmel** [comment]
There is still some "dark place" :
- to use [JsGetProperty](https://github.com/Microsoft/ChakraCore/wiki/JsGetProperty), one must provide a JsPropertyIdRef, do I get it through a call to [JsGetPropertyIdFromSymbol](https://github.com/Microsoft/ChakraCore/wiki/JsGetPropertyIdFromSymbol) ? And so a propertyId may be considered as a symbol ?
- the same with array, to use [JsGetIndexedProperty](https://github.com/Microsoft/ChakraCore/wiki/JsGetIndexedProperty), one must provide a JsValueRef (the index), how can I get it ? Is that obtained through a simple creation of an integer index (through a call to [JsIntToNumber](https://github.com/Microsoft/ChakraCore/wiki/JsIntToNumber)) ?

**Comment by MSLaguana** [comment]
To use `JsGetProperty` you do need a `JsPropertyIdRef`, which you can get from `JsGetPropertyIdFromName` if you have a string (a char16 string) of the property, or from `JsGetPropertyIdFromSymbol` if you have a reference to a javascript symbol.

For `JsGetIndexedProperty(obj, idx, &result)`, it is the equivalent of `result = obj[idx]` in javascript, so you need to have a `JsValueRef` for the index. If you have a native value that you want to index the object with, you must create it via `JsIntToNumber` or `JsCreateString` or similar.

**Comment by lemmel** [comment]
It seems clear. I will work on it later.

Last but not least, I will soon have a code that allow to wrap QObject's into ChakraCore. How can I propose the code as an example for the project ?
