### ISSUE TITLE
Question about reducing private memory size

### ISSUE THREAD

**Issue by crdumoul** [Microsoft/ChakraCore#4772]
I'm investigating a multi-tenant use of ChakraCore where there would be many instances of the same process running, and the incremental memory usage of each additional process is important.

In doing some memory profiling of a simple hello-world-type program embedding ChakraCore, I'm seeing a private memory size (as reported by the Activity Monitor on OS X and /proc/pid/smaps on Linux) of around 10MB. I expect this private memory size to be the incremental memory cost of multiple processes.

Doing some heap profiling with Valgrind's Massif tool, it looks like most of the memory is being allocated in the RecyclerWriteBarrierManager code, and specifically in X64WriteBarrierCardTableManager::Initialize() where it allocates memory for a card table.

I'm interested in learning about what the CardTable and WriteBarrierCardTableManager are used for, and if there is a way to tune down or disable this large memory allocation.

Any help would be appreciated.
Thanks,
Chris

**Comment by MSLaguana** [comment]
These are used for our software write barrier on non-windows platforms.

Because we have a concurrent garbage collector, we need to know when memory is written to and needs to be re-scanned. On non-windows platforms, we implement this in what we call "software write barrier". If you look at our code, you see many instances of a `Field` macro annotating properties. This maro means that whenever such a property is written to, we also set a bit in the card table so that the concurrent GC can find that the memory was touched and get up-to-date information on reachability.

If you look at the virtual memory allocated for this, I believe you'll see ~32GB allocated for the card table (to represent all addressable memory)  and then the amount actually used depends on how much memory is actually touched.

**Comment by crdumoul** [comment]
Thanks for the information.
Can you clarify the difference between memory "allocated" and "used"?

In my particular example, I'm seeing a little over 8MB being allocated on the heap via a call to VirtualAlloc from X64WriteBarrierCardTableManager::Initialize().
The call stack looks like:
Memory::X64WriteBarrierCardTableManager::Initialize() --> VirtualAlloc --> VirtualAlloc_ --> VIRTUALReserveMemory

Would this be the amount allocated, or the amount that was used as a result of memory being touched?

I'm currently running this on OS X.

**Comment by MSLaguana** [comment]
To be more specific, I should say that we reserve 32GB of contiguous virtual address space for the card table, which is what the allocation you refer to is doing. However this reserves the memory without committing it, meaning it isn't backed by any physical memory at this point. Later on, accesses to `Field` properties will write into this address space, which will cause the memory to get committed and start using resources.

The 8MB that you see there most likely corresponds to pages that were committed because the memory was touched.

**Comment by digitalinfinity** [comment]
A couple of clarifying points:
1. Software write barrier is actually used on all platforms, not just non-Windows. It's just used much more broadly on non-Windows platforms than on Windows (or put another way, non-Windows platforms don't rely on any hardware-supported write-watch pages)
2. What @MSLaguana

**Comment by digitalinfinity** [comment]
Some more details in case it's helpful. The card table represents 1 byte for 4KB of address space usage. The maximum supported process address space for Chakra is 128 TB, so this gives us a card table reservation of 32 GB. Additionally, this is per-process- multiple script runtimes running within a single process share a single card table.

**Comment by crdumoul** [comment]
Thanks. I think that answers my question.
