### ISSUE TITLE
Question about Linux support

### ISSUE THREAD

**Issue by crdumoul** [Microsoft/ChakraCore#4784]
I know that ChakraCore can be built for Linux, but I wondering what the experience running on Linux will be like.
Are there known limitations with running on Linux, compared to Windows?
Does the Linux build undergo the same testing as Windows?
Are there known projects out there running ChakraCore on Linux?

**Comment by MSLaguana** [comment]
There are occasional bugs that only affect non-windows scenarios (and there are bugs that affect only-windows scenarios) and we only support building for x64 on Linux, but apart from that the functionality should be the same regardless of OS now I believe. Until a few months back the non-windows scenarios did not support internationalization and there were calling convention issues for wasm, but they have both been addressed now. There are some implementation details which differ between the two, so perf behavior may differ.

Our windows builds undergo more extensive testing, but the majority of our codebase is shared code so that testing would also catch many errors that could affect non-windows builds. We do have CI that runs on linux for every PR, so we expect the quality to be similar.

There is at least one project which supports running ChakraCore on Linux: node-chakracore builds for windows, OSX and Linux.

**Comment by obastemur** [comment]
> There is at least one project which supports running ChakraCore on Linux: node-chakracore builds for windows, OSX and Linux.

and that's the only option to run node on iOS. See https://github.com/janeasystems/nodejs-mobile
