### ISSUE TITLE
console.log passed as function value fails

### ISSUE THREAD

**Issue by alfonsogarciacaro** [Microsoft/ChakraCore#4787]
This code fails with the error `Invalid calling object`:

```js
[1,2].forEach(console.log);
```

This fixes the issue:

```js
[1,2].forEach((x) => console.log(x));
```

Please note this only happens **if the devtools are closed**.

Related: https://github.com/fable-compiler/Fable/issues/1357#issuecomment-371275788

**Comment by jackhorton** [comment]
This looks like it might be an issue with Edge, rather than with Chakra, since Edge provides the console.log API. See https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues for more there.

With that being said, this doesn't repro for me in Edge 42/EdgeHTML 17. There _is_ different behavior between when F12 is open and when it isnt, but both work (when dev tools are open, the output gets parsed as an array). In the interim, does `console.log.bind(console)` work? Their implementation of the log function on `console` might rely on internal state that requires it to be called with `console` as `this`

**Comment by alfonsogarciacaro** [comment]
I tried to report it for Edge, but when selecting Javascript Category the tracker redirects me here. 

Using `console.log.bind(console)` removes the error, though the way to print the results is a bit different when the devtools are open or closed.

I use Edge 41/EdgeHTML 16, happy to know the issue is fixed in the next version :)
