### ISSUE TITLE
Function reference to console functions make Edge to rendering the page at all

### ISSUE THREAD

**Issue by maoueh** [Microsoft/ChakraCore#4795]
First of all, if I'm reporting this issue at the wrong location, feel free to tell me where I should do it instead, I'll be happy to move it there and close this one.

Versions:

```
Microsoft Edge 38.14393.2068.0
Microsoft EdgeHTML 14.14393
```

**Note** At home I have `EdgeHTML 15.xxx` and it was not working either, going to update with latest info when I get home.

So, with this piece of code below, Edge does not display `Works` as expected. Instead, the rendering and execution of JavaScript simply stop completely and the page remain empty. No issue is written to console and no way to further know the problem is available.

```
<html>
<body>
  <script>
    const func = console.log;
    func('Test');

    document.write('Works');
  </script>
</body>
</html>
```

If the `Developer Tools` is opened however, the page loads correctly without issue. 

The problem seems to be the reference to the `console.log` function which is probably a native reference. By doing directly a `console.log(...)` or a function reference to pure JavaScript function instead, the problem is not exhibited (of course and hopefully :)).

**Comment by jackhorton** [comment]
This looks like a dupe of https://github.com/Microsoft/ChakraCore/issues/4787 -- though the issue with developer tools not showing anything useful here is probably separate and should be reported to Edge [here](https://github.com/Microsoft/ChakraCore/wiki/External-Issues#edge-issues).

The fix is `const func = console.log.bind(console)`. console.log was only recently changed in the WebIDL spec to not require `this` to be `console`, but Edge only adds support for this in Edge 17.

**Comment by maoueh** [comment]
Seems exactly the same, I should have searched better!

Thanks.
