### ISSUE TITLE
exception when attempting to construct bound proxy

### ISSUE THREAD

**Issue by sethbrenith** [Microsoft/ChakraCore#4918]
The following test case throws `TypeError: 'newTarget' is not a constructor`.

```javascript
        body() {
            let constructionCount = 0;
            function a(arg1, arg2) {
                this[arg1] = arg2;
            }
            const b = new Proxy(a, {
                construct: function (x, y, z) {
                    ++constructionCount;
                    return Reflect.construct(x, y, z);
                }
            });
            const boundObject = {};
            const c = b.bind(boundObject, "prop-name");

            {
                const obj = new c("prop-value");
                assert.areNotEqual(boundObject, obj, "bound function should ignore bound this when constructing");
                assert.areEqual("prop-value", obj["prop-name"], "bound function should keep bound arguments when constructing");
                assert.areEqual(1, constructionCount, "bound proxy should be constructed once");
                assert.areEqual(a.prototype, obj.__proto__, "constructed object should be instance of original function");
            }

            {
                constructionCount = 0;
                class newTarget {}
                const obj = Reflect.construct(c, ["prop-value-2"], newTarget);
                assert.areEqual(newTarget.prototype, obj.__proto__, "bound function should use explicit newTarget if provided");
                assert.areEqual("prop-value-2", obj["prop-name"], "bound function should keep bound arguments when constructing");
                assert.areEqual(1, constructionCount, "bound proxy should be constructed once");
                assert.areEqual(newTarget.prototype, obj.__proto__, "constructed object should be instance of original function");
            }
        }
```

**Comment by rhuanjl** [comment]
I'll take a look at this, may be related to or even caused by one of the Proxy fixes I've done recently.

Trying with eshost JSC also errors on this but v8 and SM don't.

**Comment by rhuanjl** [comment]
Ok no the error is not related to the pieces I've done on Proxies issue appears to relate to the way Reflect.construct interacts with proxy construct traps. Putting in a print() call shows that the ```new c``` call results in the trap being triggered twice instead of once - the error is on the second trigger of the trap which should never occur.

I'll see if I can work it out what's going wrong to make the trap fire twice - I think it may be an error in the implementation of Reflect.construct.

**Comment by rhuanjl** [comment]
OK so there are there three problems in BoundFunction.cpp related to constructing var a proxy trap:

1. The construct trap of the proxy is called here WITHOUT the bound arguments:
https://github.com/Microsoft/ChakraCore/blob/1189fe888e6a7aa8d4727cddf3af446da9252f20/lib/Runtime/Library/BoundFunction.cpp#L143

2. The construct trap of the proxy is called AGAIN here this time with the bound arguments BUT not with (target, argumentsList, newTarget), instead it's called with (...boundargs, target, argumentList, newTarget) 
https://github.com/Microsoft/ChakraCore/blob/1189fe888e6a7aa8d4727cddf3af446da9252f20/lib/Runtime/Library/BoundFunction.cpp#L204

The error is thrown on the second call as the newTarget parameter is instead one of the boundArgs or the target or the argumentList.

Note currently in the edge cases where this (i.e. instantiating a bound proxy with a construct trap) doesn't throw an error (there are a few) the constructor is still being called twice.

**To fix this...**
Need to know how to insert the boundargs onto the start of the argumentList parameter for the trap rather than on to the start of all arguments.

Then need to fix it to do that and then call the trap and return if it's a Proxy.

**Comment by rhuanjl** [comment]
So I've had a look at this, I do not have a working fix but as I've taken a bit of time working through what the issues are posting them in case useful to anyone else looking at this.

**There are two different errors to look at in order to fix the above test:**
**Firstly - new boundProxy -> Reflect.construct -> throws**
1. Calling new on a boundFunction leads to:
BoundFunction::NewInstance creating a this value:
https://github.com/Microsoft/ChakraCore/blob/5fb9787b67476fe51cde96f994d1b0771d2d2844/lib/Runtime/Library/BoundFunction.cpp#L168-L178
It then calls the constructor which hits JavascriptProxy::FunctionCallTrap
2. JavaScriptProxy::FunctionCallTrap concludes that this is a ConstructorSuperCall
https://github.com/Microsoft/ChakraCore/blob/5fb9787b67476fe51cde96f994d1b0771d2d2844/lib/Runtime/Library/JavascriptProxy.cpp#L2075
This is because it a) is a new call AND b) has a non-null this value or new target, see:
https://github.com/Microsoft/ChakraCore/blob/5fb9787b67476fe51cde96f994d1b0771d2d2844/lib/Runtime/Language/JavascriptOperators.cpp#L1324-L1329

3. JavaScriptProxy::FunctionCallTrap on encountering a ConstructorSuperCall sets the 3rd argument (newTarget) of the construct trap call to the "this" value for the call - so when the construct trap is called newTarget is the "this" value created by BoundFunction::NewInstance.

4. Reflect.Construct cannot use a "this" value as its newTarget.

**Secondly - new boundProxy results in constructor being called twice**
This issue whilst not directly related to the first error message must also be fixed for the above case to pass in full.

1. BoundFunction::NewInstance when called with a Proxy invokes the Proxy's construct trap to create the "this" value it's going to provide (see above)
https://github.com/Microsoft/ChakraCore/blob/5fb9787b67476fe51cde96f994d1b0771d2d2844/lib/Runtime/Library/BoundFunction.cpp#L137-L144
2. BoundFunction::NewInstance ends by calling the relevant constructor:
https://github.com/Microsoft/ChakraCore/blob/5fb9787b67476fe51cde96f994d1b0771d2d2844/lib/Runtime/Library/BoundFunction.cpp#L211
This involves the construct trap again.
