### ISSUE TITLE
core dumps on String.repeat function

### ISSUE THREAD

**Issue by igor-simoes** [Microsoft/ChakraCore#4979]
Hello everyone,
this is a case of "inconsistent treatment/check of pre-conditions" with long numbers on String.repeat function.

Chakra version: 1.9.0.0
OS: Ubuntu 16.04 x64

Steps to reproduce:
1. Run this code
`print( "foo".repeat(657604378) === "foofoofoo" );`

Expected output:
An exception with an invalid string length (RangeError)

Actual results:
core dumps

V8 and SpiderMonkey raises a `RangeError` and JavascriptCore returns `false`.

**Comment by jackhorton** [comment]
I believe this is intentional behavior, where we crash the process when we run out of memory. Not doing so would put the engine in an inconsistent state and could lead to security issues. I believe there is a flag like "-FailFastOnOOM-" that you can pass, where the trailing "-" turns the feature off.

**Comment by MSLaguana** [comment]
For what it's worth, in v8 (using node9.5.0 as the host) if I try to `"foo".repeat(1<<26)` I get a crash due to out of memory (when trying to display the string), but `"foo".repeat(1<<27)` I get an exception. Using node-chakracore, I can successfully compute `"foo".repeat(1<<26)`, and even `"foo".repeat(1<<28)`, but `"foo".repeat(1<<29)` gives me a crash due to out of memory.

**Comment by damorim** [comment]
If I understood correctly a core dump is not considered to be worse than an exception raised (in effect of defensive programming) to check input length.

**Comment by MSLaguana** [comment]
That's right; if we encounter a situation where we are unable to guarantee the state of the system (out of memory being a common case) then we choose to crash (core dump optional) on our terms rather than attempting to roll-back to a maybe-good state and continue on with an exception, which might leave some state in an intermediate / exploitable state.

**Comment by dilijev** [comment]
From the discussion, it looks like because this is by design, there is no action to take.
