### ISSUE TITLE
uint16_t undefined with 1.8.3

### ISSUE THREAD

**Issue by billti** [Microsoft/ChakraCore#5059]
I'm seeing the same issue as #4320 again. Using the latest VS 15.7 preview, and referencing via the ChakraCore NuGet package in a C++ Console app, I get the below error (on the parameter `_In_ const uint16_t *content` in the declaration for `JsCreateStringUtf16`). 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	ChakraConsole	c:\temp\chakraconsole\packages\microsoft.chakracore.vc140.1.8.3\build\native\include\chakracore.h	285	
```

The fix at #4322 seems to have been changed, and now the inclusion of `stdint.h` (which defines the type) is only present in the non-Windows section of ChakraCommon.h (i.e. its in the `else` block of the condition at https://github.com/Microsoft/ChakraCore/blob/707ae66637018f7983bc0ee5a6811c6e1789aa75/lib/Jsrt/ChakraCommon.h#L27 ).

**Comment by MSLaguana** [comment]
Actually the issue is that #4322 put the fix into master at the time, which became part of release/1.9, while the nuget package is coming from release/1.8 still which doesn't have the fix. For now you can add the `#include <stdint.h>` to your project, but we should probably backport the fix to 1.8 so our next release doesn't have the same issue.
