### ISSUE TITLE
Raising an exception when promise rejection is unhandled

### ISSUE THREAD

**Issue by vikrem** [Microsoft/ChakraCore#5079]
I'm trying to replicate implementation-specific behaviour in ChakraCore to mirror behaviour found in v8.

In v8, a Promise that `.reject()`s, wherein the rejection lacks a handler, will cause an exception.
ChakraCore has a `JsHostPromiseRejectionTrackerCallback` hook to define host behaviour in this situation.

The ChakraCore docs (https://github.com/Microsoft/ChakraCore/wiki/JsHostPromiseRejectionTrackerCallback) claim:
> Note - per ECMASpec #sec-host-promise-rejection-tracker this function should not set or return an exception.

The ECMAScript spec (https://www.ecma-international.org/ecma-262/7.0/#sec-host-promise-rejection-tracker) claims:
> An implementation of HostPromiseRejectionTracker must complete normally in all cases.

Given this constraint, I do not understand how I can throw an exception to the offending javascript code. V8 does it, so surely there must exist a reasonable method?

**Comment by dilijev** [comment]
As a simplification, let's take as an assumption that a spec-compliant host will not throw from that callback.

My understanding is that what should actually happen is that the callback is merely a means for the engine to **notify** the host that a promise rejection occurred (and whether the operation was 'reject' or 'handle'). The actual action the callback may take, then, is to schedule an event in the host's event queue corresponding to the promise rejection. If the promise rejection was unhandled, for example, the host might fire an `unhandledrejection` event. If this event has no explicit handler, it's default handler will run, and this might throw an exception.

With no handlers in place it may appear that a rejection directly causes an exception to occur, but that is not actually the case.

(Someone more knowledgeable about the specs in this area, please correct me if I'm wrong.)

/cc @liminzhu @bterlson

**Comment by rhuanjl** [comment]
**Firstly a little background on why HostPromiseRejectionTracker should not create an exception:**
```js
const foo = Promise.reject("anything"); //HostPromiseRejectionTracker will trigger here with handled as false

foo.catch((reason)=>{/*handle somehow*/}); //HostPromiseRejectionTracker will trigger here with the same promise but now with handled as true
```
If your HostPromiseRejectionTracker implementation throws an exception the above code would error out which you probably wouldn't want as there is a handler in the code it's just later on.

**Note on the v8 Comparisons**
v8 on it's own shouldn't throw an exception here it should depend on the host note that they provide an equivalent api:
```SetPromiseRejectCallback``` perhaps they have an implementation using this in their d8 shell?

**How to achieve what you want**
If you really want every unhandled promise rejection to throw an exception you could use JsSetException within your JsHostPromiseRejectionTracker callback - BUT your host would then throw an exception for the code example above - which would not be spec compliant, and may be problematic.

The "proper" way of doing it is to:
1. create a native array/list/queue of some kind in which to store rejected promises and rejection reasons
2. Whenever HostPromiseRejectionTracker is called with handled = false add the promise to the array along with the rejection reason
3. Whenever HostPromiseRejectionTracker is called with handled = true look through the array and remove the promise+reason
4. At some regular interval in your host check if the array has anything in it, if yes throw an exception or print a warning (node currently does this and prints a warning rather than throwing)

There is a question of when that regular interval should be - once per event loop cycle is the obvious answer.

See also https://html.spec.whatwg.org/multipage/webappapis.html#unhandled-promise-rejections for the standard web browsers are meant to follow in implementing this.

**Comment by fatcerberus** [comment]
The callback is not allowed to throw.  In practice you wouldn't want to anyway: You may get an unhandled rejection for a promise which has its handler attached later in the same tick it gets rejected.  For example you wouldn't expect this to crash your process:
```js
Promise.reject().catch(() => {});
```

For the above you get two calls to HostPromiseRejectionTracker:
1. "reject" for `Promise.reject()` (as it's indeed unhandled at the time of rejection).
2. "handle" upon calling `.catch()`

If you do the above in Node, you don't crash.  This is because Node checks at the end of the event loop whether there are any `reject` notifications without a matching `handle`.  If it were legal to throw from inside the callback and you did so, the above code would crash your process.
