### ISSUE TITLE
Imported function is undefined

### ISSUE THREAD

**Issue by ragzovskii** [Microsoft/ChakraCore#5171]
Hello.
I have recently updated from Edge 16 to Edge 17 and now I began to experience issue with imports from momentjs. You can reproduce this issue easily. Assuming you have installed momentjs from npm, create two files:
**index.html**
```
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    <script src="test.js" type="module"></script>
</body>
</html>

```

**test.js**
```
import { getSetHour } from '../node_modules/moment/src/lib/units/hour.js'

console.log(getSetHour);
```

This snippet works fine in chrome and edge 16, but fails in edge 17.

**Comment by kfarnung** [comment]
@boingoing Do you have any idea what changed here?

**Comment by ragzovskii** [comment]
While looking up solution for this strange bug, I learned, that issue may be caused by exception in imports. E.g. if imported js has exception in it, it may fail silently and result in undefined export. I have no idea why exception is swallowed in this case.

**Comment by fatcerberus** [comment]
I'm not able to reproduce in miniSphere (throwing in any module causes the engine to crash with an uncaught exception), so this sounds like an Edge bug.

**Comment by ragzovskii** [comment]
Are you suggesting me to report this to the Edge issue tracker?

**Comment by fatcerberus** [comment]
Yes, this doesn't seem to be a bug in ChakraCore per se.

**Comment by ragzovskii** [comment]
5 days without any reaction on edge issue tracker. Do you have influence on issue tracker team? I would appreciate if someone would take a look, pretty serious issue.

**Comment by rhuanjl** [comment]
I'm not a member of the team but I've had a quick look at this - I think the change in behaviour between Edge 16 and Edge 17 does relate to a CC change.

Specifically this change: https://github.com/Microsoft/ChakraCore/pull/4574
This change among other things reversed the load order for ESModule dependency trees.

I actually think this is an error in the ESM version of the moment library which was exposed by that correction in CC.

Looking at:
https://github.com/moment/moment/blob/3062ca13cd1cfbcef1c4a0cd5543f5fcd329c1d9/src/lib/units/hour.js#L144

getSetHour is defined as the return value of makeGetSet('Hours', true); however makeGetSet is also imported so there's a question on what order the imports and exports happen in order to determine whether you get the result you need.

Reversing the load order will have changed that order and hence caused a problem here. I note that node doesn't yet support ESModules except with an experimental flag so I assume that the moment.js ESmodule code is intended for use with a transpiler - when transpiled and packed into a single file module load order becomes irrelevant.

**Comment by ragzovskii** [comment]
I re-tested that code in latest firefox 60.0.1, it works (logs function to console):
![image](https://user-images.githubusercontent.com/1575279/40469416-23b69f40-5f39-11e8-8bb6-2f10ed29f3f0.png)
I checked this in safari, on virtual machine in saucelabs, it works. My colleague also tested this piece on macbook, he says console displays this method. He didn't see it first, because filter was enabled. Could that maybe have happened to you too?
Also, to finalize my point, we have an app, which eventually imports this method, that works in every major browser, that supports ES modules. **Only Edge**, starting from version 17, stopped working.

I recall claim, that Edge appends 'chrome' into userAgent, because it has to behave just like chrome, and then we have this issue. I think it was said in this blogpost: https://blogs.windows.com/msedgedev/2015/06/17/building-a-more-interoperable-web-with-microsoft-edge/

We had to modify plenty of apps to detect Edge and redirect user to webpack-ed version of the app. Which is pretty sad, given that edge 16 worked just fine with modules.

**Comment by rhuanjl** [comment]
Hmm my tests were in latest Firefox and latest Safari on macOS, curious that it wouldn’t work for me but does for you)

That aside using node as a comparator i’ll see if I can discover why the execution order is different in current CC and if/how it can be changed to work in this case.

(Note i said above i’m not a member of the team , to clarify further i’m not from Microsoft, I’m just an external contributor trying to be helpful)

**Comment by rhuanjl** [comment]
OK dug a little and got a simple proof of concept for the incompatibility - note the error being encountered above is due to modules being executed in the wrong order.

```js
//a.js
console.log("a");

//b.js
console.log("b");

//c.js
console.log("c");

//mod.js
import "./c.js";
import "./a.js";
import "./b.js";
```

When ChakraCore runs mod.js as a module it will print:
```
b
a
c
```
Conversely when v8 runs it it will print:
```
c
a
b
```

CC reverses the order but I can't at the moment see how exactly the code causes the reversal. (Note it is nothing to do with this: https://github.com/Microsoft/ChakraCore/blob/master/lib/Runtime/Language/SourceTextModuleRecord.cpp#L757-L761)

**Comment by rhuanjl** [comment]
@kfarnung if I can fix this would it be possible to get a bug fix into edge 17 at this stage?

**Comment by kfarnung** [comment]
Ping @digitalinfinity for that question.  I think at this point a fix like that would be targeting the next release of Edge.

**Comment by rhuanjl** [comment]
@ragzovskii I've looked at this more and have a few things for you:
**1. A possible workaround in your example above try adding**
```js
import "../node_modules/moment/src/lib/moment/prototype";
```
Before importing getSetHour. This extra import changes the import order and should cause it to resolve - bit awkward but seems to work.

**2. Follow up question - where you actually doing**
```js
import { getSetHour } from '../node_modules/moment/src/lib/units/hour.js'
```
Without a different import first successfully in edge 16? - I've tested this with versions of CC going back a year and it didn't work. (Note this issue is all to do with the order of imports resolving so an extra import first can change the result)

**3. If you were doing:**
```js
import Moment from '../node_modules/moment/src/moment'
```
I can confirm that this worked with Chakracore 1.7 but broke in Chakracore 1.8 - this was broken by commit 2dc946cbecfc22f849b3b953844924a6f7d1ff5d which reversed the importing order for child modules - looking at related Pull Requsts I think this was a mistake that could be undone for future versions.

4. I note that 
```js
import { getSetHour } from '../node_modules/moment/src/lib/units/hour.js'
```
Does work with v8 but I can't understand why - there may be a subtlety I'm missing here - as noted above the fix from point 3 doesn't fix this in CC - importing hour as your first import results in year being imported before get-set which results in a crash in CC and this seems to be the same with or without the fix I mentioned. However if you import prototype first it works in either case.

**Comment by ragzovskii** [comment]
I was importing moment (option 3), yes. Then I was able to narrow down the test case to importing single method which I reported here.

As a workaround we are using bundles now, but hoping modules will work soon.

**Comment by rhuanjl** [comment]
@ragzovskii This issue has now been closed as my fix for the regression is in Chakracore master but I don't know when that will flow through to a released version of Edge.

**Comment by ragzovskii** [comment]
Awesome! Thank you
