### ISSUE TITLE
Chakra throws SyntaxError if RegExp pattern has a quantifier prefix with a long number 

### ISSUE THREAD

**Issue by igor-simoes** [Microsoft/ChakraCore#5182]
Hi everyone,
Chakra throws a SyntaxError when I instantiate a RegExp class with a pattern that have a long number quantifier prefix, the same occurs with the regular expression literal.

OS: Ubuntu 16.04 x86
Chakra: 1.10.0.0-beta

Step to reproduce:
```
let p1 = new RegExp('^[a-z]{2,2147483648}$');
print(p1.test('a'));

let p2 = /^[a-z]{2,2147483648}$/;
print(p2.test('aaaaa'));
```
Actual results:
```
SyntaxError: Syntax error in regular expression
```
Expected results:
```
false
true
```

V8, SpiderMonkey and JavascriptCore works as expect. 

Maybe this stderr output can help to debug:
`ChakraCore/pal/src/cruntime/printfcpp.cpp:70WideCharToMultiByte failed.  Error is 487`

**Comment by dilijev** [comment]
RegexParser.cpp

```cpp
CharCount Parser<P, IsLiteral>::RepeatCount()
//...
            if (n > MaxCharCount - standardEncodedChars->DigitValue(ec))
                Fail(JSERR_RegExpSyntax);
```

CommonTypedefs.h

```cpp
const CharCount MaxCharCount = INT_MAX-1;
```

We don't support strings longer than `MaxCharCount`, so coding a range check into a regex for some specific repeat count which would require a string longer than `MaxCharCount` to satisfy is not going to be helpful for your program.

Perhaps this error could be more helpful (it's really more of a RangeError than a SyntaxError).

IMO an error here makes sense, but an alternative, in order to maintain compat without breaking semantics within supported scenarios (i.e. wouldn't have already failed for another reason, be it string length or OOM), would be to clamp such regex range check numbers to the largest acceptable count instead of throwing an error. FWIW I don't see a particularly compelling reason to do this, though, unless this is causing a compat/interop issue in a real scenario.

**Comment by fatcerberus** [comment]
The other engines don’t throw in this case (it’s a legal regex even if it can’t be satisfied due to technical limitations on string length) so that seems like a compatibility issue by definition.

**Comment by dilijev** [comment]
True, and as a second pass, it therefore seems fine to do

> in order to maintain compat without breaking semantics within supported scenarios (i.e. wouldn't have already failed for another reason, be it string length or OOM), would be to clamp such regex range check numbers to the largest acceptable count instead of throwing an error.
