### ISSUE TITLE
JsCollectGarbage doesn't do a garbage

### ISSUE THREAD

**Issue by dimitrovp** [Microsoft/ChakraCore#5190]
Hi, all again :)

I have a problem with the garbage collection.

I need to create and destroy a lot of contexts which use one runtime and after that,
I want to uninitialize my system where I am trying to invoke  JsDisposeRuntime,
but it seems that on "ClearObjectBeforeCollectCallbacks" there are still data, but all my resources and data is released. 

When I destroy a context I just release it and invoke "JsCollectGarbage(rt)" but the data is still there, why?

Why when I call "JsCollectGarbage(rt)" it doesn't collect everything?

I've written a sample where I've attached a callback which I expect to be invoked on "JsCollectGarbage" but it is invoked on "JsDisposeRuntime".

What can I do to force garbage collection for every unused context?

Foo()
{
	JsRuntimeHandle rt = JS_INVALID_REFERENCE;
	CHECK_CCRT(JsCreateRuntime(JsRuntimeAttributeNone, nullptr, &rt));

	void* data = nullptr;
	JsFinalizeCallback finalizeCallback = [](void* call) {
	};

	{
		unsigned cnt = 0;

		JsContextRef m_Context = JS_INVALID_REFERENCE;
		CHECK_CCRT(JsCreateContext(rt, &m_Context));
		CHECK_CCRT(JsSetCurrentContext(m_Context));
		CHECK_CCRT(JsAddRef(m_Context, &cnt));

        JsValueRef object = JS_INVALID_REFERENCE;
        CHECK_CCRT(JsCreateExternalObject(data, finalizeCallback, &object));

		CHECK_CCRT(JsSetCurrentContext(nullptr));
		CHECK_CCRT(JsRelease(m_Context, &cnt));
	}
	// Expect to call finalize here
	CHECK_CCRT(JsCollectGarbage(rt));
	// But it is called here
	CHECK_CCRT(JsDisposeRuntime(rt));
}

**Comment by MSLaguana** [comment]
Because we have a concurrent GC, it is possible that a GC was triggered in the background earlier on, and then the `JsCollectGarbage` call may just wait until that collection has finished. In that case, when the collection started the object was still reachable, so it was marked and not collected.

I suspect that if you add a second call to JsCollectGarbage that it might end up calling your finalizer there, since by the time that collection starts there should be no lingering references to your object. That said, because we have a conservative GC I don't think we make many guarantees about when finalizers will be called, so be cautious about making assumptions there.

**Comment by dimitrovp** [comment]
I've tried to call JsCollectGarbage twice but the result is the same.

Is it possible to force garbage collection for a certain context or how can I force all finalizers for a certain context?

**Comment by MSLaguana** [comment]
GC isn't managed per-context, it is per-runtime. The Recycler doesn't really care what context something comes from, the only way that the context plays into things is that the current context is considered to be reachable, while others won't be unless you `JsAddRef` them or similar. Are you sure that there are definitely no references to the context sticking around, perhaps on the stack? I know of cases when there is no need for a value to still be referenced, but it just happens to still exist on the stack and thus the GC considers it to be live.

**Comment by dimitrovp** [comment]
No, there are no references to the context. OK thank you. It seems that I can't trust on JsCollectGarbage and I will try to figure out how to deal with it
