### ISSUE TITLE
Global object has no toStringTag unlike other engines

### ISSUE THREAD

**Issue by sunlili** [Microsoft/ChakraCore#5513]
Hello,
The following code behaves strangely (inconsistent with other engines).
```
var test = 1; 
function fail(n, expected, result) { print("test " + test + "; expected " + expected + ", got " + result); }
function test0() {
    var result;
    var check;

    result = (~ 2147483647);
    check = this;
    if(result != check) {{ fail(test, check, result); }} ++test; 
}
test0();
print("BT_FLAG");
```
In ChakraCore, the output is
```
test 1; expected [object Object], got -2147483648
BT_FLAG
```
However, in V8 and SpiderMonkey, output is
```
test 1; expected [object global], got -2147483648
BT_FLAG
```
BT group
2018.7.24

**Comment by fatcerberus** [comment]
I’m rather confused by the test - it can’t possibly ever succeed because `result` is a number and `check` is set to`this`, i.e. either the global object (sloppy mode) or `undefined` (strict mode).

That said, to clarify for everyone else, the actual inconsistency here is that ChakraCore stringifies the global object as `[object Object]` whereas the other engines stringify it as `[object global]`.  I’m not sure if there’s a spec point about this, I’ll have to check.

**Comment by fatcerberus** [comment]
By the way, could you be more specific in your issue titles?  They’re all just “inconsistent output with other engines” so if you look at the issue page it just seems like you’re spamming.

**Comment by fatcerberus** [comment]
Specification for `Object.prototype.toString`:
https://tc39.github.io/ecma262/#sec-object.prototype.tostring

There is no special case here for the global object; what seems to be happening is that V8 and SpiderMonkey have a `@@toStringTag` on the global object while CC does not.

Test code:
```js
let global = new Function('return this;')();
print(global.toString());
print(global[Symbol.toStringTag]);
```

Node (V8):
```
C:\temp>node global.js
[object global]
global
```

ChakraCore:
```
C:\temp>ch global.js
[object Object]
undefined
```

There is no specification requirement for the global object to have a `@@toStringTag`; but, nor is this forbidden.  In the absence of an outright prohibition, I think we should be consistent with the other engines.
