### ISSUE TITLE
WebAssembly cleanup

### ISSUE THREAD

**Issue by Cellule** [Microsoft/ChakraCore#568]
Now that pre-v1.0 is completed (#440)
There are some items that needs to be fixed before we move on.
The purpose of this issue is to keep track of things we know about and intend to change.

- [x] : Break `ScripContext::LoadWasmScript()` into smaller functions
- [x] : Check if default export should be supported by spec
- [ ] : Allow `-off:jitloopbody` for wasm functions (currently causes crash in the interpreter if the flag is set to false (check BytecodeWriter::begin)
- [x] : Check if trying to export a function as `memory` (verify what should be the behavior in this case)
- [x] : Are empty blocks valid by spec?
- [x] : Should empty data segment throw compilation error ?
- [x] : Wasm Signature initialize with fixed size from param count

I will update this list as we find other things we want to do before we move on.
@MikeHolman @commonlisp Can you guys reply here if there are other things you remember we should look into

**Comment by MikeHolman** [comment]
if we're talking about refactoring, I'd like to refactor GenerateFunction and maybe EmitCall into smaller functions as well. And we can remove code around the now defunct constant table.

Default export is not supported by spec. Empty blocks are valid by spec. But we may want to bring these up as questions on design repo, because they haven't really been discussed.

Wasm.instantiateModule is a nonstandard ad-hoc API and we will hopefully be moving to a standard API fairly soon, where this name conflict will not be an issue. Though if you try to export anything with duplicate names we should throw, and this rule extends over the special "memory" export as well.
