### ISSUE TITLE
Support TextEncoder&TextDecoder

### ISSUE THREAD

**Issue by d3x0r** [Microsoft/ChakraCore#5726]
TextEncoder and TextDecoder have been missing from IE/Edge forever.

This is a document of the api...
https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder

Here is your status compared to other's status.
https://caniuse.com/#search=uint8array

I did just notice that there's a 'in development' note on 'can i use' 
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/encodingstandard

But actually going there and searching for 'TextEncoder' yields no results.

**Comment by chicoxyzzy** [comment]
This API is significant when one use WebAssembly<->JS boundary

**Comment by fatcerberus** [comment]
I've implemented TextEncoder/Decoder myself in miniSphere, albeit for UTF-8 only; it'd be great to have fully-featured versions available natively.

That said, these aren't part of ECMAScript so it might not make sense to have them in core.

**Comment by jackhorton** [comment]
cc @liminzhu 

This is unfortunately a browser API rather than an ECMAScript API, and as Bruce said, is out of scope for ChakraCore. From https://developer.microsoft.com/en-us/microsoft-edge/platform/status/encodingstandard, you can see that the Edge team is aware of the issue, and that link will be the place to check for any status updates on it.

**Comment by fatcerberus** [comment]
That being said, I do very much wish there was some kind of text encoding facility in the specification; it feels like a major shortcoming that we have DataView providing a standardized way to poke arbitrary integer and float values into an arraybuffer, but no standard way to do the same with strings.  As it stands the Encoding API is a near-necessity if you want to process any kind of structured binary data in JS (which is why I implement it in miniSphere).

**Comment by EdMaurer** [comment]
Thread has run its course.
