### ISSUE TITLE
GC concurrent collection performance

### ISSUE THREAD

**Issue by NDobrev** [Microsoft/ChakraCore#5774]
Hi , 

I've made some performance measurements, because we have very big spikes sometimes when GC kick in and I found something weird. When DoCollect is called with CollectOverride_ForceInThread reflect in some very long waits. I am wondering, if this is expected or I do something wrong. Also is there any way to reduce GC spikes. I try to poke some of heuristics in recycler.cpp, but i didn't find any noticeable difference. My trace looks like this (we have 1 main and 2 background worker threads) : 

![image](https://user-images.githubusercontent.com/6154617/46801902-93821680-cd64-11e8-8611-c024c5ce01ef.png)

**Comment by digitalinfinity** [comment]
CollectOverride_ForceInThread is the GC's sad case- either it's asked to do that by someone manually (if you're doing that, consider using other flags), or it's in a state where it can't allocate memory and it really needs to stop the world. In general, Chakra's GC is a mostly concurrent GC- we'll do most of the work on the background thread so that by the time we need to stop the world for correctness, the pause time is really small because the mark state that we have is almost complete. If there is a long GC time that wasn't manually triggered, it means that there is a ton of object allocations and mutations happening in the main thread that's defeating the GC's background thread work. If this is your scenario, the best advice I can give is to profile the allocations happening while we're background marking and send us a sample, and we can see if there are ways we can optimize the allocations.

@VSadov any other thoughts?

**Comment by EdMaurer** [comment]
Thread appears to have run its course.
