### ISSUE TITLE
BUG: dumps of multiple functions are mixed in --asmDumpMode or --dump:assembly

### ISSUE THREAD

**Issue by utshina** [Microsoft/ChakraCore#5863]
When we use --asmDumpMode or --dump:assembly, dumps of multiple functions are mixed (only tested in Linux), making it hard to read.

**Comment by MSLaguana** [comment]
I believe that this is because there are multiple threads. If you specify the particular function that you want to dump (I believe something like `--dump:assembly:1.23` will work to dump function 1.23) then it won't interleave with other functions, or alternatively I think there's a way to reduce parallelism, but I forget the flag off the top of my head...

**Comment by utshina** [comment]
Yes, this is a multi-thread (and multi-process) problem. It seems that Func::Dump() in Func.cpp is called from multiple thread in parallel and their dumps are mixed. In addition, if we use --dump:assembly, dumps from Encoder::Encode() in Encoder.cpp are also mixed. By taking locks with CriticalSection in the first part of these functions, the dumps are not mixed.

**Comment by Penguinwizzard** [comment]
Dump phases are handled differently for different phases, so taking locks for all of them could get pretty involved (and there'd have to be work to avoid deadlocks). Instead, what we normally do in this situation is use `-bgjjit-`, which disables background jitting; in these scenarios, writing to the console is going to tank your jit performance regardless, so disabling parallel jitting isn't a big issue, and it avoids all of the interleaving.
