### ISSUE TITLE
ChakraCore 1.11.7 download broken on jsvu due to mac file link

### ISSUE THREAD

**Issue by kjpou1** [Microsoft/ChakraCore#6034]
[jsvu](https://github.com/GoogleChromeLabs/jsvu) downloads ChakraCore from GitHub releases and has used the link `osx_x64` as the operating system link 1.11.6 and previous.

Example: `https://aka.ms/chakracore/cc_osx_x64_1_11_6` 

The new link for the mac os version is now: `https://aka.ms/chakracore/cc_osx_64_1_11_7`

Is there anyway we can keep these links consistent?

jsvu issue: https://github.com/GoogleChromeLabs/jsvu/issues/63

**Comment by mathiasbynens** [comment]
Note that for other operating systems, the `x` is still there in the URL. So for consistency it would be best to just... stick to the pre-existing URL format.

> Is there anyway we can keep these links consistent?

+9001

ChakraCore has broken jsvu several times already due to unexpected changes to the URL format, incorrect checksums, missing release information, and the like:

- https://github.com/GoogleChromeLabs/jsvu/issues/21
- https://github.com/GoogleChromeLabs/jsvu/issues/54
- https://github.com/GoogleChromeLabs/jsvu/issues/55
- https://github.com/Microsoft/ChakraCore/issues/5945
- https://github.com/mono/mono/issues/12331
- https://github.com/Microsoft/ChakraCore/issues/6034

No other JavaScript engine has required this many hotfixes on the jsvu side.

It would be great if ChakraCore could stick to a unified way of releasing new versions. Isn't this all automated anyway?

**Comment by zenparsing** [comment]
Thanks for the report - will follow up!

**Comment by zenparsing** [comment]
@mathiasbynens The link should be fixed; let me know if there are still any issues.

**Comment by kjpou1** [comment]
Yes, this is now fixed.  Thanks
