### ISSUE TITLE
Return Promise from JavaScript

### ISSUE THREAD

**Issue by TemporalAgent7** [microsoft/ChakraCore#6048]
I couldn't find any examples of calling JavaScript functions that return promises. I'm particularly interested in how to register callbacks for resolve / reject.

We can check the state of a promise with `JsGetPromiseState` and get its result with `JsGetPromiseResult`, but I can't see how to get notified when a promise's state changes. What is the intended design, and how are others handling this scenario?

I presume we could keep a global vector on the C++ side of all unresolved promises then manually iterate over all of them on each `PromiseContinuationCallback` call, but that feels wrong (and a potential perf issue). Are there alternatives I'm missing?

Thank you!

**Comment by MSLaguana** [comment]
What end-result do you want to achieve? Do you want to run some code once the promise is either resolved or rejected? If that is the case, then it sounds like you essentially want to do `myPromise.then(onResolved, onReject)` in your native code, and you can do that by mimicing the javascript: get the `then` property of `myPromise`, construct your resolve/reject callback functions (as native functions or otherwise) and then call `then` with the appropriate arguments.

**Comment by fatcerberus** [comment]
If you only care about rejections, you can use `JsSetHostPromiseRejectionTracker`:
https://github.com/fatcerberus/minisphere/blob/master/src/shared/jsal.c#L205

I don’t think there’s a general way to track promise *fulfillments*, though, unless you created the promise yourself.
