### ISSUE TITLE
Is there an option that can turn on all the checks in jit?

### ISSUE THREAD

**Issue by ZackJohn** [microsoft/ChakraCore#6152]
I am learning about the bailout mechanism. I find that if the object, like JavaScriptNativeIntArray, is accessed twice in JITted code, and there is no operation that can change the type of object between these two accesses, then for the optimization purpose, the BailOnNotNativeIntArray code will only execute once.
Is there an option that can turn on all the checks in JITted code?

**Comment by MikeHolman** [comment]
I'm not 100% sure I understand the question. You mean that you want a flag that will make you have two BailOnNotNativeIntArray checks instead of the one?

There isn't really one flag that will separate all of the bailout checks, because they are often added as part of optimizations, and the combined checks might be different than the individual checks. Or they might impact further optimization.

For example, you might have a loop like
````
for (let i=0; i<10; i+=2) {
 a[i] = 1;
 a[i+1] = 2;
}
````
We could eliminate bound checks and then have bailouts:
````
for (let i=0; i<10; i+=2) {
 BailOn a.length <= i
 a[i] = 1;
 BailOn a.length <= I+1
 a[i+1] = 2;
}
````
We might combine them like this:
````
for (let i=0; i<10; i+=2) {
 BailOn a.length <= i +1
 a[i] = 1;
 a[i+1] = 2;
}
````
Or hoist like this:
````
BailOn a.length <= 10
for (let i=0; i<10; i+=2) {
 a[i] = 1;
 a[i+1] = 2;
}
````

Depending on what else is happening in the loop, we might combine them or hoist them or not, but eliminating redundant bailouts can change the conditions that we bail out on.

**Comment by ZackJohn** [comment]
Excellent, thanks for your reply.
First, “You mean that you want a flag that will make you have two BailOnNotNativeIntArray checks instead of the one?”
"Yes!"
Now I understand I can't separate all of the bailout checks by an option.
Second, according to your example, is there a time window that two BailOn checks exist in the "IR chain"?
"IR chain" means the Instrs generated after IRBuilder phase.

**Comment by fatcerberus** [comment]
I would think there's no specific rules like that; it would just be "if this condition we've assumed is true for optimization purposes turns out to actually be false at runtime, bail out."  Like an `assert()` that instead of crashing the program on failure, bails out back to the interpreter.  So they'd just be inserted according to what's needed at that point to keep the code safe - it wouldn't really be deterministic in the way you're assuming.

**Comment by ZackJohn** [comment]
Oh, I see.  The bailout is like the guard to prevent jit code run away. But the bailout is based on some assumptions, if one assumption is wrong, the code may not be safe anymore.

**Comment by fatcerberus** [comment]
Yes, the JIT code makes some assumptions about what will happen at runtime, to make it fast for common cases.  If that wasn’t the case we wouldn’t need bailouts at all. :)

Like in the example `for` loops above - it assumes the array won’t shrink during loop execution, which allows it to skip checking if the accesses are in-range for every single array access.  If this is violated the code wouldn’t be memory safe anymore so a bailout check is put at a strategic location to catch it.

**Comment by ZackJohn** [comment]
Exactly! "a strategic location " is a very precise description.
Thank you!
