### ISSUE TITLE
assertion failure in Js::JavascriptFunction::ReparseAsmJsModule

### ISSUE THREAD

**Issue by zhunki** [microsoft/ChakraCore#6236]
````
function Module() {
    'use asm';

    function f() {
    }

    return f;
}

function recur() {
    try {
        recur();
    } catch (e) {
        Module(123456);
    }
}

recur();
````

**Comment by MikeHolman** [comment]
This is by design. We don't want to continue execution if we run out of stack while reparsing an asm.js module after it failed linking, due to risk of objects getting into a bad state in the engine.

Failed linking is a rare case to begin with (it means someone is running invalid asm.js) and it is also rare for your stack to be so low when you are initializing an asm.js module.
