### ISSUE TITLE
A question about infinity string

### ISSUE THREAD

**Issue by YuanWangC** [microsoft/ChakraCore#6340]
When I execute the testcase below, the returncode is -6 and aborted without other information (exception, warning, OOM etc.) provided. This is not friendly enough for users. Maybe you could enhance it.
#### version 
[eaaf7ac](https://github.com/microsoft/ChakraCore/commit/eaaf7ac6beca01ab0d80c05959f3868463043c2d)
#### build platform
`Ubuntu 16.04.6 LTS (Linux 4.15.0-55-generic x86_64)`
#### build step
`./build.sh --debug`
#### testcase
```
var NISLFuzzingFunc =function(){
    var result = "-";
    while(result !== undefined){
        result += result;
    }
};
NISLFuzzingFunc();
```
#### run step
`ChakraCore/out/Release/ch testcase.js`

**Comment by rhuanjl** [comment]
The issue here is that you continually extend the string until your computer is out of memory.

If you compile with the flag EnableFatalErrorOnOOM set to false it will turn off this abort and throw a javascript exception in this case.

HOWEVER default behaviour is intentionally to abort when out of memory as there is no safe and reliable way to recover when out of memory - for instance there may not be enough memory to handle the javascript exception.

**Comment by YuanWangC** [comment]
I have used the command `./build.sh --extra-defines=EnableFatalErrorOnOOM=false` to compile the engine and run this testcase again, but it printed `Aborted` without any exceptions. Did I use the correct compile command?

**Comment by rhuanjl** [comment]
Hmm curious - if you use a testbuild or a debug build and supply the flag `-EnableFatalErrorOnOOM-` at runtime you get the Js error for out of memory. However with a release build setting that at compile time doesn't seem to work (release builds don't accept runtime flags).

That aside as already mentioned this behaviour in release builds is by design as there is no reliable safe way to recover from running out of memory.

**Comment by YuanWangC** [comment]
thanks for your explanation!
