### ISSUE TITLE
Embed ICU from CMake

### ISSUE THREAD

**Issue by ppenzin** [microsoft/ChakraCore#6424]
Current *nix builds allow for embedding of ICU library into the build via `--embed-icu` switch. What this does - it invokes an additional script from the build script, followed by `configure` and `make`:

https://github.com/microsoft/ChakraCore/blob/master/build.sh#L411
https://github.com/microsoft/ChakraCore/blob/master/tools/icu/configure.py

CMake can take care of that via `ExternalProject` module, which would eliminate ICU download script and greatly reduce the corresponding section of the build script.

**Comment by rhuanjl** [comment]
Definitely a +1 from me, --embed-icu is my normal way of building CC to have it function correctly.

**Comment by jackhorton** [comment]
Huh, didnt know about ExternalProject when I wrote this originally. Looks like a good change for xplat, but the configure.py script will need to remain to integrate with msvc properly. Note that we ignore a handful of files in configure.py, but I am not sure if thats strictly necessary in non-node scenarios (which is what the relevant comment says the exclusions are caused by)

**Comment by ppenzin** [comment]
@jackhorton thank you for the input! I dd a quick search on what else was using the configure and only saw a line in `build.sh`. Does it get used in MSVC Andoid builds?

This would end up being a bit involved than I thought originally, as the compile step would build the library (before CC sources). Let's see how that would turn out.

**Comment by rhuanjl** [comment]
As a couple of extra side notes on macOS; icu does come pre-installed so it should in theory be possible to detect and use that version BUT for whatever reason the --system-icu flag to build.sh doesn't work AND providing a path to the pre-installed ICU via the flag for that also doesn't seem to work (builds but fails to load at runtime). Whilst the --embed-icu flag works perfectly.

On Android as far as I know the android build has been broken for sometime.

**Comment by jackhorton** [comment]
configure.py is used in ad-hoc ICU-enabled Windows builds -- its a manual pre-build step if you want to use non-system ICU on Windows. We never got around to using ICU in ChakraCore windows builds due to licensing and build system complexity that we didnt have time to address, but in theory, that will be a requirement if CC wants to stay up to date with the Intl spec, since there just isnt support for some of the primitives required by newer APIs (like `formatToParts`)

**Comment by ppenzin** [comment]
> As a couple of extra side notes on macOS; icu does come pre-installed so it should in theory be possible to detect and use that version BUT for whatever reason the --system-icu flag to build.sh doesn't work AND providing a path to the pre-installed ICU via the flag for that also doesn't seem to work (builds but fails to load at runtime). Whilst the --embed-icu flag works perfectly.

OSX build seems to ignore system ICU, and not setting `ICU_LIBRARIES`.

In fact we are not actively looking for the library, unless `ICU_INCLUDE_PATH` is specified. Even for Linux there is no actual detection of ICU being present on the system.

CMake 3.7 introduced a [module for ICU detection][cm]. But even for older versions, we can put together a mechanism to detect it using `find_library`.

[cm]: https://cmake.org/cmake/help/v3.7/module/FindICU.html
