### ISSUE TITLE
How to get the code coverage of ChakraCore by executing js testcases?

### ISSUE THREAD

**Issue by ty5491003** [microsoft/ChakraCore#6529]
Hi, I'm working on fuzz testing, and now i have a batch of js testcases, i want to get the **code coverage of ChakraCore** by executing testcases. (not coverage of testcases, i don't care it.). Because I want to use the increase of engine coverage as one of my performance metrics.

I've looked at a lot of info, and it looks like it can be done with some C/C++ tools, but I'm not familiar with C/C++, So could you tell if there is such a feature built in ChakraCore? If not,  can you give me some advice about how to meet my needs?

Thanks guys, I'll be waiting for your reply. :laughing:

**Comment by ppenzin** [comment]
The engine can only give you data on JavaScript it runs, not on its own sources, for that you would need an external tool (with compiler support).

Assuming you have access to Linux environment, [gcov][g] is a classic example of a code coverage tool for native code. However, since ChakraCore uses Clang instead, you probably want to take a look at the [Source Code Coverage][scc] in Clang docs. That is probably the path of least resistance. You can conditionally add instrumentation flags that Clang supports via CMake.

On Windows, this needs to be a Visual Studio plugin, and looks like there are options. I guess you can also use `llvm-cov`, but you would first have to change the build to use LLVM instead of MSVC toolchain.

[scc]: https://clang.llvm.org/docs/SourceBasedCodeCoverage.html
[g]: https://en.wikipedia.org/wiki/Gcov

**Comment by ty5491003** [comment]
@ppenzin 
Thanks for your advice. I will try to do it with clang first, thank you again.

**Comment by ppenzin** [comment]
@ty5491003 we will be happy to support coverage in the official builds - if you are going to be able to turn it on, we can help you with build plumbing (CMake options and so forth). Also if you have any questions about builds - feel free to ask.
