### ISSUE TITLE
More specific SyntaxError message 

### ISSUE THREAD

**Issue by jianchun** [Microsoft/ChakraCore#767]
Eval this script:

``` javascript
function f(){}; f(f(1,
```

Chakra:

``` javascript
SyntaxError: Syntax error
```

V8:

``` javascript
function f(){}; f(f(1,
                     ^

SyntaxError: Unexpected end of input
```

Can Chakra output a more specific **message** than `Syntax error`? (e.g. other existing Chakra SyntaxError messages match `/^(Expected|Unterminated)/`). node matches SyntaxError message and starts `multi-line` mode if an expression appears incompleted.

**Comment by Oceanswave** [comment]
+1

**Comment by dilijev** [comment]
Confirmed this continues to repro:

```
>eshost --tags jsvu -x "function f(){}; f(f(1,"
#### jsvu-ch
SyntaxError: Syntax error

#### jsvu-d8
SyntaxError: Unexpected token ;

#### jsvu-sm
SyntaxError: expected expression, got ';':

#### jsvu-jsc
SyntaxError: Unexpected token ';'
```

**Comment by dilijev** [comment]
This message seems to come from

```
>git grep "\"Syntax error\"" *.h
lib/Parser/perrors.h:LSC_ERROR_MSG( 1002, ERRsyntax        , "Syntax error")
```

`>git grep ERRsyntax` returns 46 results in `lib/Parser/parse.cpp`, which `git blame` shows are mostly @boingoing's edits.

**Comment by dilijev** [comment]
This is too broad and not actionable at this time with our current priorities. /cc @kfarnung @agarwal-sandeep

**Comment by jackhorton** [comment]
Why close this?

**Comment by dilijev** [comment]
Signal to noise ratio in the issue tracker mainly (where Signal = immediately actionable with clear measurable value). The idea is to use NiceToHave to track issues like this even after they are closed.

**Comment by jackhorton** [comment]
That seems like a really easy way to fade into oblivion... we have 300 issues open, theres already plenty of noise for any one person looking through issues without filtering by tag. I would say this is no less important than any of the PlatformAgnostic refactoring work I tracked, but I want to keep those open because I know ill never look at them again if theyre closed, nor will any external contributor. I would vote strongly in favor of keeping these nice to have/sev3 issues open unless we know for a fact that we will never implement them (for example, having an external C++ API would probably be nice, but JSRT is so ingrained in Core and IActiveScript in Full that we would likely never consider implementing yet another, nonetheless supporting it).

**Comment by kfarnung** [comment]
I agree with the sentiment, but this is a really broad issue opened two years ago that requires very intricate changes to the parser code.

There are a bunch of similarly broad issues that were opened when the project went open source and have been basically untouched since. There comes a point where if the issue is important enough it will come back up again. Having some issues linger is fine, but there comes a point where you have to decide whether having them clutter the issue tracker is the right thing to do.

We know there's a balance and we're working on finding it.

**Comment by dilijev** [comment]
@jackhorton FWIW we (the triage team) had a spirited debate about this (offline) spanning from Wednesday-Friday :)

You are correct that with the current number of issues open, this particular issue doesn't improve things much, but we're far from done with cleaning up the tracker.
