### ISSUE TITLE
CI/Test related commits

### ISSUE THREAD

**Issue by obastemur** [Microsoft/ChakraCore#937]
For the test/CI related work, IMO we better have a separate branch (can be forked from linux) and we do the work there. Once it's up and running we `squash the commits` and `cherry pick the one` back to linux or whatever the origin branch was. 

Sounds good ?

**Comment by dilijev** [comment]
I'll talk with @mmitche about this since there are additional changes that need to be made for workflow with the CI mechanism that might make this difficult (changes are somewhat tied directly to the branch the changes are targeting). For the moment, we need to unblock the branch so #929 should be merged directly in.

**Comment by obastemur** [comment]
IMO we should have all the stuff done on a forked branch on the same repository. What's technically keeping us from doing that? Otherwise, linux branch is becoming a trial-error place

**Comment by dilijev** [comment]
Taking discussion offline to explain details about the tools.

For the purposes of this issue, I think we can work out a way to be less disruptive for future changes. 

Since the only action to take on this issue is workflow related, I'll close this issue and keep this in mind for future changes.

**Comment by obastemur** [comment]
@dilijev thanks for the details
