### ISSUE TITLE
Various Function constructors should allow single-line comments

### ISSUE THREAD

**Issue by bterlson** [Microsoft/ChakraCore#971]
```js
Function('a//', 'return a;')(1);
```

Expected: returns 1
Actual: SyntaxError

Per 11.4, comments are treated like whitespace and are ignored.

In order to construct something that can toString properly, we can align with the stage 3 [F.p.toString proposal](https://tc39.github.io/Function-prototype-toString-revision/#sec-createdynamicfunction). To wit: 
```js
Function('a//', 'return a;').toString();
/*
function anonymous(a//
) {return a;}
*/
```

**Comment by michaelficarra** [comment]
* The actual `toString` output for that function would have a line feed before the final `}`.
* The single line comment will affect all following parameters since they are parsed together after being joined by `,`, so you might want to have a test that `Function('a//', 'b', 'b')()` throws a ReferenceError.

**Comment by bterlson** [comment]
@michaelficarra thanks for the additional pointers!

Just to confirm, is it intentional that there is no linebreak after the opening curly of the function body? Seems like every implementation adds a line break there.
